### ISSUE TITLE
RTL version of Bootswatch Themes

### ISSUE THREAD

**Issue by unsalkorkmaz** [thomaspark/bootswatch#103]
I would like to give RTL support for my [FirmaSite theme](http://theme.firmasite.com/).
There is some discussions and tools for people thinking on RTL version of bootstrap themes:
https://github.com/twitter/bootstrap/issues/175

I am not a RTL language user so i really cant test it even if i prepare RTL version of bootswatch styles. Is there anyone willing to fully test it or maybe someone have a tested RTL version of bootswatch styles?

**Comment by LazZiya** [comment]
This one looks promising, I tried the online converter but it is not that precise still in beta: https://rtlcss.com/

Fortunately there is rtlcss for bootstrap 4.2 already available http://bootstrap.rtlcss.com/

Would be happy to see all bootswatch themes supporting rtl.
