### ISSUE TITLE
Flaty Card doesnt work.

### ISSUE THREAD

**Issue by AlexGipp** [thomaspark/bootswatch#1032]
![image](https://user-images.githubusercontent.com/33844665/93664951-f8773880-fa72-11ea-83ac-42ed04026619.png)

The style of the navbar gets applied, the style of the card doesn't. 
Does anyone know if I'm doing something wrong or if the style is just broke?

```html
<div class="card">
     <div class="card-body">
          <h4 class="card-title">@repo.Name</h4>
          <h6 class="card-subtitle mb-2 text-muted">@repo.CreatedAt.Date</h6>
          <p class="card-text">@repo.Description</p>
          <a href="@repo.Url" class="card-link">Github</a>
          <a href="#" class="card-link">Another link</a>
      </div>
</div>

**Comment by AlexGipp** [comment]
I just tested a different style (default style) and the cards seem to work just fine.

**Comment by thomaspark** [comment]
Hi @AlexGipp, could there be another style interfering with the card border? Do you have a link to a live demo you can share?

Here's what I see:
https://jsfiddle.net/jbpac2h5/

**Comment by AlexGipp** [comment]
Hello @thomaspark, unfortunately, I don't have a live demo online.

I thought that that may be the issue as well but after trying out things like removeing the old bootstrap style or separating the styles into different folders I'm pretty sure that's not the issue.

Also note that it just worked with the default style so im not really sure what the issue is.

**Comment by dleffler** [comment]
Don't you have to explicitly define the 'border class' in the 'card' wrapper?

**Comment by AlexGipp** [comment]
@dleffler i dont know but like i said, as soon as i switched to a different theme it worked just fine.
