### ISSUE TITLE
Own Themes

### ISSUE THREAD

**Issue by AlexGipp** [thomaspark/bootswatch#1045]
I just thought that it would be cool to make my own bootstrap theme and publish it on bootswatch.
So is it possible to publish self made themes on bootswatch and do you know any good articles on how to make your own bootstrap theme?

**Comment by thomaspark** [comment]
Hey @AlexGipp, we don't have open submissions for themes, but it would be great to have a platform for that. Perhaps in a future spinoff.

Here's the official docs on theming Bootstrap:
https://getbootstrap.com/docs/4.0/getting-started/theming/

Here's an article on Customizing Bootstrap I wrote for Smashing Mag. It's older but most of the principles still apply.
https://www.smashingmagazine.com/2013/03/customizing-bootstrap/

Best way to learn is to take the default Bootstrap or an existing theme, and start playing around it.

**Comment by AlexGipp** [comment]
Awesome thanks for the replie @thomaspark, is it still somehow possible to get a theme merged into bootswatch?

**Comment by thomaspark** [comment]
No worries. I wouldn't rule it out completely, but we wouldn't accept a new theme and the maintenance cost of that unless the theme was absolutely stellar. The best chance is would probably to make a dark version of an existing theme, like with Flatly/Darkly, but that wouldn't be a guarantee either.

**Comment by AlexGipp** [comment]
Challange accepted 😂

**Comment by XhmikosR** [comment]
@thomaspark please try to always link to the latest docs; v4.0 is pretty old. Although in this case it might not matter a lot, I see reports from people still using ancient docs for reference :)

**Comment by thomaspark** [comment]
@XhmikosR updated the link!
