### ISSUE TITLE
Wrong behaviour for slate theme in input-group

### ISSUE THREAD

**Issue by Renkineko** [thomaspark/bootswatch#1046]
Hi,

I have a strange behaviour with the Slate theme, and I need help understand what's going on. The theming works perfectly in cyborg, superhero, classic or darkly, but the base for the real future theme of the website is the Slate theme, so it's bugging me.

Here is a sample code:

```html
<div class="input-group input-group-sm">
	<input type="number" class="numberinput form-control die-number" min="0" max="999" aria-label="Dice number" placeholder="Dice number">
	<div class="input-group-append">
		<label class="input-group-text">D6</label>
	</div>
	<input type="number" class="numberinput form-control bonus-number" min="-999" max="999" aria-label="Bonus" placeholder="Bonus">
	<div class="input-group-append">
		<div class="btn-group-toggle" data-toggle="buttons">
			<label class="btn btn-outline-primary btn-share active" title="Share the result">
				<input type="checkbox" checked="" autocomplete="off">
				Share
			</label>
		</div>
	</div>
</div>
```

The result appearing:

![image](https://user-images.githubusercontent.com/2254151/96260256-188d0f80-0fbf-11eb-94c3-5b05acd7c284.png)

The result expected (like in darkly theme):

![image](https://user-images.githubusercontent.com/2254151/96259577-17a7ae00-0fbe-11eb-8d90-a0d800f77970.png)

Note in the screen, the code sample is in a card-body, but I checked and it doesn't matter. The button in the screen contains an i tag with fontawesome class.

From what I've understood, the issue is due to the size of the button. But I can't change its height without messing up the placement of the i. And I don't understand why this behaviour change this much from a theme to another.

Because the slate will become our main theme, if you have suggestion for a fix I can implement myself, I would appreciate very much.

I tried to put the sample code in the demonstration page, and it seems the problems in your current version is on every theme. I use bootstrap 4.3.1.

Thanks for the awesome work, keep it up :+1: 

Cheers.

**Comment by thomaspark** [comment]
Hey @Renkineko,

I tried your markup with default Bootstrap and the other themes you mentioned, and they seem to have a similar issue. Did you add some custom CSS to fix those?

<img width="689" alt="Screen Shot 2020-10-16 at 11 37 03 AM" src="https://user-images.githubusercontent.com/900407/96278953-1f5a5900-0fa4-11eb-8da7-7d93f08ea266.png">

Are you require to use `.btn-group-toggle` for the share button? If you use just a button, it works:

<img width="685" alt="Screen Shot 2020-10-16 at 11 37 58 AM" src="https://user-images.githubusercontent.com/900407/96279091-3ef18180-0fa4-11eb-8589-445cd482d850.png">

**Comment by Renkineko** [comment]
Hi @thomaspark and thank you for your answer.

I don't have any custom CSS on this sample code, and that's why I'm so lost about it...

I need to keep the button togglable but indeed, it seems I can use a simple button, and I will then do it and check the state of the button instead of checking the prop checked of the input inside. I'll try it monday and let you know.

Thanks a lot for the feedback, i'll inform you of the outcome :) have a nice day/night

**Comment by Renkineko** [comment]
It works like a charm. Thanks again for the good hint!
