### ISSUE TITLE
Update for Bootstrap 4.5.3

### ISSUE THREAD

**Issue by mc2002tii** [thomaspark/bootswatch#1048]
Can you make a new release for Bootstrap 4.5.3 if needed?  Thanks.

**Comment by thomaspark** [comment]
We've updated to 4.5.3!

https://github.com/thomaspark/bootswatch/releases/tag/v4.5.3

**Comment by skylarmt** [comment]
FYI, the API (https://bootswatch.com/api/4.json) still returns `"version": "4.5.2"`

**Comment by thomaspark** [comment]
Thanks, BootstrapCDN hasn't been updated yet.

You can find 4.5.3 on unpkg: https://unpkg.com/browse/bootswatch@4.5.3/
