### ISSUE TITLE
[slate] Incorrect background color for list group on hover

### ISSUE THREAD

**Issue by simondubois** [thomaspark/bootswatch#1057]
Hi Thomas,

First, thank you for your relentless work and the maintenance of the project. So much consistency and fidelity to the original framework!

I have a problem with the them Slate using list group with variant. When hovering the item, the background changes to dark.

**Code sample:**
```
<div class="list-group">
    <div class="list-group-item list-group-item-info">
        Content
    </div>
</div>
```

**Probable cause for such behaviour:**
https://github.com/thomaspark/bootswatch/blob/9f627602be112714c53d13c62a1bb6e49f77091d/dist/slate/_bootswatch.scss#L527-L531

**Desired behaviour:**
Elements with class `list-group-item` are not interactive (excepted links, buttons and classes `list-group-item-action`). Thus, no styling should be changed on hover.
This thought comes from my reading of the related [Bootstrap source](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_list-group.scss).

**Possible solution:**
Remove the following rule:
https://github.com/thomaspark/bootswatch/blob/9f627602be112714c53d13c62a1bb6e49f77091d/dist/slate/_bootswatch.scss#L527-L531

**Comment by thomaspark** [comment]
Hey @simondubois, thanks for the nicely articulated report. Very refreshing. 😄 

As a solution, I'll apply the style to `list-group-item-action` instead of `list-group-item`. Fix incoming.
