### ISSUE TITLE
Change default font size in the simplex theme

### ISSUE THREAD

**Issue by ikatenov** [thomaspark/bootswatch#1058]
This request is related to issue #993. 
Is it possible to set the $font-size-base parameter to 1rem by default too? I've recently upgraded to the latest version of YAF (2.31.9) and found that all texts look very small again. This happened because the $font-size-base is set to 0.8125rem back after your improved theme was integrated into the YAF source. All texts look really small, it's hard to read them. 1rem is a much better choice, believe me. Can you fix that too, PLEASE?

**Comment by thomaspark** [comment]
Hey @ikatenov, the smaller size is a design decision of the theme, and changing it could break other sites actively using it. I recommend override base font size on your own and getting it changed upstream.

**Comment by thomaspark** [comment]
Just a heads up, default font sizes across the themes, including Simplex, will be bumped up in v5. Most of them will be 1rem.
