### ISSUE TITLE
weird <strong> x2 appearing

### ISSUE THREAD

**Issue by nightw0lv** [thomaspark/bootswatch#1059]
after my last update (was outdated 1 month about)
i see in my website stuff like this everywhere 
https://prnt.sc/vf46wy
is it normal?

**Comment by thomaspark** [comment]
Are you using a theme? It's most likely being added by that, as Bootswatch is responsible for just the CSS, not the markup.

**Comment by nightw0lv** [comment]
no actually i use only the classes i made a simple theme by hand, you can see it at itopz.com it has all your themes maybe its my fault but cant tell for sure that is why i asked, it happen after the update
