### ISSUE TITLE
Inclusion of thumbnails

### ISSUE THREAD

**Issue by SamMousa** [thomaspark/bootswatch#1060]
I realize this has been mentioned in several very old and closed issues (#336 ,  #458)..

One of the things mentioned against including demo pages in the dist is bloat, which could be a fair argument for demo pages.

For thumbnails however the story is different; the size is negligible. For example looking at the cerulean theme:
```sh
$ du -sh *
224K	bootstrap.css
184K	bootstrap.min.css
4,0K	_bootswatch.scss
4,0K	_variables.scss
```

The thumbnail (https://bootswatch.com/cerulean/thumbnail.png) adds a mere 17KB to this, which is < 10% of the minimized css. 

Currently there is no clean way to bundle bootswatch and create an interface where users may pick one of the themes.

**Comment by thomaspark** [comment]
Hey @SamMousa, a theme picker seems like a valid argument for thumbnails. I'll look to include them in the next release.

**Comment by XhmikosR** [comment]
IMHO no binary files or previews should be part of the npm package. 99% of the users won't even need this, so why penalize them?

**Comment by SamMousa** [comment]
How are they penalized? It isn't send to their browsers if it's not used.

**Comment by SamMousa** [comment]
@thomaspark did you change your mind or just lost track of this? Seeing as some are against it (imo with invalid reasoning) an alternative would also be to have a separate thumbnails package, not sure if that would add a lot of steps to the release process though..

**Comment by thomaspark** [comment]
@SamMousa, still considering if thumbnails should be added. It's true that a very small minority of users will be using this feature. Perhaps pulling from the [API](https://bootswatch.com/api/4.json) will be a better place for it.

**Comment by SamMousa** [comment]
That adds an external dependency to a production environment, that doesn't make much sense to me.

I feel the arguments against are flimsy to be honest. 

> IMHO no binary files or previews should be part of the npm package. 99% of the users won't even need this, so why penalize them?

Anyone not using a template picker is unlikely to use all templates, so they are already importing a dependency ~30 themes of which they use only 1 or very few... I really don't see the problem of adding a few kilobytes to the package.
One could argue the same for not including the non-minified versions... 

We shouldn't worry so much about the size of the NPM package, but about what is sent to the browser. In this case, that won't change unless people want to display thumbnails...

Currently the size is around 8mb:
```
$ du -sh .
7,8M	.
```

Adding 21 * 17kb will add 357kb to the package, that's about a 4.4% increase in used disk space... Anyone worried about this detail should maybe rethink including 21 themes when they are not using them all instead. Or maybe consider removing the non-minified versions which would bring them down to around 4MB...

@XhmikosR given these numbers do you really feel that strongly about this? And if you do, is it about the principle or about the space?

With minimal effort (using GIMP to resize the thumbnail from 1000x600 to 300x180) its size is ~ 6kb...

**Comment by XhmikosR** [comment]
It's not about disk space per se. It's about contributing to the npm bloat situation. I still don't think thumbnails should be part of the npm package.

**Comment by SamMousa** [comment]
They could be in a separate package as well, but I'd imagine that is more work for the maintainer(s). Isn't the npm bloat in this case mostly caused, for example, by the fact that all themes are in 1 package?

I understand your point about not everyone needing it but it seems an arbitrary line to draw, most people also won't need the unminified CSS file, or any of the SCSS files. A balance has been struck to include them instead of having several packages which pushes the effort to maintainers at no real benefit.

I don't think a < 2% bloat is a valid example of `the npm bloat situation`.

**Comment by thomaspark** [comment]
I understand the utility and convenience of this. But I haven't had any other requests for it. If the demand is there I'll do it.
