### ISSUE TITLE
Minty: Default button is invisible

### ISSUE THREAD

**Issue by pos777** [thomaspark/bootswatch#1061]
```
<button type="button" class="btn btn-primary">Primary</button>
<button type="button" class="btn">Basic</button>
<button type="button" class="btn btn-secondary">Secondary</button>
```

The Basic button is invisible in the Minty theme:
![image](https://user-images.githubusercontent.com/5260725/100743359-41d9f180-33ed-11eb-80c5-6e30136ad5fe.png)

Try it: https://codepen.io/pos777/pen/LYRVrJW

**Comment by XhmikosR** [comment]
This isn't valid markup. `btn` alone doesn't do anything.

**Comment by pos777** [comment]
Thank you for the answer. I have several new question =)
Is it documented restriction?
Does it mean that the https://www.w3schools.com/bootstrap/bootstrap_buttons.asp article is not correct?
What is purpose of the .btn style (https://github.com/twbs/bootstrap/blob/a716fb03f965dc0846df479e14388b1b4b93d7ce/scss/_buttons.scss#L7) if it should not do anything?

**Comment by thomaspark** [comment]
Hey @pos777, `.btn` sets the base button styles, and the button variants add background color.

I recommend the official docs for the most up-to-date and accurate info:
https://getbootstrap.com/docs/4.5/components/buttons/
