### ISSUE TITLE
CDN not working

### ISSUE THREAD

**Issue by dalibor-sanzeru** [thomaspark/bootswatch#1067]
Hi,
CDN mentioned on web and in GIT is not working:

https://www.bootstrapcdn.com/

=> 
This site can’t provide a secure connection
www.bootstrapcdn.com sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

**Comment by thomaspark** [comment]
Closing this issue as bootstrapcdn.com is online now.

But I'll be looking to update docs to point to something like [unpkg](https://unpkg.com/browse/bootswatch@4.5.3/), which stays in sync.
