### ISSUE TITLE
5.0, when?

### ISSUE THREAD

**Issue by williamd5** [thomaspark/bootswatch#1068]
When shall we expect to see Bootstwatch themes for Bootstrap 5.0? Are there going to be new ones? I would personally love to see just different colour schemes, e.g. the colour palette only changed.

**Comment by samihoda** [comment]
Same question!

**Comment by nightw0lv** [comment]
same question too 👍

**Comment by BaEigner** [comment]
+1, I'd love to see the v4 themes updated to v5

**Comment by thomaspark** [comment]
Just updated the themes to 5.0.0 very very beta 1.

Check out the v5 branch for more:
https://github.com/thomaspark/bootswatch/tree/v5
