### ISSUE TITLE
Switch to jsDelivr

### ISSUE THREAD

**Issue by XhmikosR** [thomaspark/bootswatch#1075]
Unfortunately, BootstrapCDN's future is unknown right now, so better switch to jsDelivr.

Just make sure you switch every instance, old docs and everything. And while at it update the API to the latest version.

**Comment by XhmikosR** [comment]
@thomaspark you missed 2.x https://github.com/thomaspark/bootswatch/blob/v4/docs/2/api/themes.json

**Comment by thomaspark** [comment]
Updating v2 now. Had to use gh instead of npm for it.
