### ISSUE TITLE
Minor request for $theme variable

### ISSUE THREAD

**Issue by Banner-Keith** [thomaspark/bootswatch#1078]
I have a minor request to add a variable at the top of each `_variables.scss` file with `$theme = 'themename'` for example `$theme = 'flatly'`

Sometimes we want to add some override for some part of a theme but only if the theme is set to a specific theme name. So maybe we want to override a font size, or a link color but only for flatly. So it's nice to be able to do `@if $theme == 'flatly'`

I would be happy to open a PR with this change if that would be helpful.

**Comment by Banner-Keith** [comment]
Oh and also maybe a variable to indicate if the theme is a dark or light theme.

**Comment by thomaspark** [comment]
Hey @Banner-Keith, just added $theme variable to the v5 branch. I'll consider adding light/dark (the whole light/dark thing may be getting a rework) but holding off for now. You should at least be able to set conditionals to treat dark themes differently by name.

**Comment by Banner-Keith** [comment]
Thank you. This is awesome.
