### ISSUE TITLE
is it possible to use prefers-color-scheme media query to style dark theme?

### ISSUE THREAD

**Issue by godalming123** [thomaspark/bootswatch#1081]

**Comment by thomaspark** [comment]
Dark mode is in the future for all the themes, but we're waiting to follow the lead of Bootstrap on how it's implemented. There's a lot of considerations to be made around that, whether to use `prefers-color-scheme` or a different approach.

**Comment by fxzxmic** [comment]
https://github.com/twbs/bootstrap/blob/main/scss/mixins/_color-mode.scss
Perhaps we can release a separate version for `media-query`?
