### ISSUE TITLE
GitHub release too big for jsDelivr

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [thomaspark/bootswatch#1084]
I'm trying to load this package from [jsDelivr CDN](https://www.jsdelivr.com/package/gh/thomaspark/bootswatch) but it fails because the package is over 50 MB. Are there any files that could be removed to reduce the package size?

**Comment by thomaspark** [comment]
Hey @ParveenBhadooOfficial, you can access cdn here:

https://www.jsdelivr.com/package/npm/bootswatch

**Comment by ParveenBhadooOfficial** [comment]
@thomaspark the light theme (default/official is not here), can you add that so that It'll be easy to use in projectdirectly from this Repo's CDN.

https://github.com/thomaspark/bootswatch/tree/v4/dist
