### ISSUE TITLE
[Sketchy] Issue select on safari

### ISSUE THREAD

**Issue by fabienducret** [thomaspark/bootswatch#1085]
It seems select component has an issue on safari browser : 

<img width="397" alt="Capture d’écran 2021-03-25 à 08 51 07" src="https://user-images.githubusercontent.com/6165166/112437654-76c8d600-8d47-11eb-9526-a88cf4870f16.png">

Theme used : https://bootswatch.com/sketchy/

**Comment by thomaspark** [comment]
Hey @fabienducret, pushing a fix for this now.

**Comment by fabienducret** [comment]
Perfect ! Thanks :)
