### ISSUE TITLE
Flatly navbar styles 

### ISSUE THREAD

**Issue by cpsievert** [thomaspark/bootswatch#1088]
In BS3 -> BS4, the "active link" selector changed from `li.active > a` to `.nav-item > .nav-link.active`, which means this CSS no longer works with BS4 or BS5

https://github.com/thomaspark/bootswatch/blob/8c3aaf30775b4010ca3f42ecd7a7792276fe29f6/dist/flatly/_bootswatch.scss#L12-L26

**Comment by thomaspark** [comment]
Thanks for the bug report @cpsievert! We'll get that fixed up.

**Comment by cpsievert** [comment]
Great thanks! Also, just FYI, I've made quite a few fixes to a handful of themes to make them a bit more themeable via Bootstrap Sass variables. See all the patch files that start with `006-bootswatch-*` here https://github.com/rstudio/bslib/tree/master/tools/patches 

Let me know if you'd be interested in some PRs and I can send some your way. BTW, I work for RStudio and we're very appreciative (and sponsor) of your work!

**Comment by thomaspark** [comment]
Just pushed a fix for v4. I'll take a look at v5 as well.

Awesome! I'd welcome any PRs to fix whatever issues you've come across

By the way, my colleague and good friend, who uses Shiny as a central part of their work, just tipped me off recently that you're supported Bootswatch themes. We're big fans. 🙌
