### ISSUE TITLE
Edit themes to use media hover queries

### ISSUE THREAD

**Issue by exoRift** [thomaspark/bootswatch#1093]
There's an issue with touchscreens where in certain contexts, elements can retain the hover status after being pressed. This is solved with [media queries](https://stackoverflow.com/questions/23885255/how-to-remove-ignore-hover-css-style-on-touch-devices)

Could some of the themes be edited to implement this? (I primarily use Flatly and Darkly)

**Comment by thomaspark** [comment]
Hey @exoRift, I recommend opening an issue upstream with [Bootstrap](https://github.com/twbs/bootstrap). We'd only support this if it's added to there first.
