### ISSUE TITLE
CDN its doesn't work

### ISSUE THREAD

**Issue by EliasLeguizamon123** [thomaspark/bootswatch#1095]
Hi Thomas, i love use bootswatch for my backend proyects, but i trying use this time by CDN and doesn't work, i use this:

`link(href='https://cdn.jsdelivr.net/npm/bootswatch@3.4.0/sandstone/bootstrap.min.css' integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous")`

before, i always use by local .min.css

**Comment by thomaspark** [comment]
Hey @EliasLeguizamon123, double-check your integrity value. This should work:

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@3.4.0/sandstone/bootstrap.min.css" integrity="sha256-VMoCUcye/6tOq8VYNHo1HrbOQNXDIDdMhoxH1dhW5EA=" crossorigin="anonymous">
```

**Comment by EliasLeguizamon123** [comment]
Thanks it's work !
