### ISSUE TITLE
Lumen/Simplex/others badge visibility

### ISSUE THREAD

**Issue by ekrichbaum** [thomaspark/bootswatch#1098]
In v4 "badge badge-secondary" and "badge badge-light" had a dark font for visibility.  Under v5 "badge bg-secondary" and "badge bg-light" do not.  Secondary is subdued close to background, light is invisible. [https://bootswatch.com/lumen/](url)

Previously, in badge-secondary/badge-light color was set #222, with v5 that is not. Assuming that bg- is just for the background color (per docs), it may not be proper to set that value, but does break this particular theme and some others.  btn-secondary/btn-light do set color for those items.

Adding text-dark style does bypass the problem but doesn't allow for theme switching to dark themes without breaking them.  Just seems clumsy compared to previous.

```
        $(document).ready(function () {
            var selectedvalue = $("#selectTheme").val();
            if (selectedvalue == "lumen" || selectedvalue == "simplex" || selectedvalue == "yeti" || selectedvalue == "materia" || selectedvalue == "lux" || selectedvalue == "cerulean") {
                $(".bg-secondary").addClass("text-dark");
            }
        });

```

**Comment by thomaspark** [comment]
Agree it's clumsy for theme switching, but that's the approach taken with Bootstrap 5 as seen [here](https://getbootstrap.com/docs/5.0/components/badge/).

Since `.badge` applies color anyway, might not be the greatest sin to override light `.bg-` classes with color too.

**Comment by ekrichbaum** [comment]
Sure.  Will want to update those pages to make those visible.  The function is functional (hah) at least to add text-dark for me, just doesn't "feel" good having to do that.

**Comment by dleffler** [comment]
This hack completely changes the dark navbar from blue gradient to dark grey.

**Comment by thomaspark** [comment]
You can use `bg-info` with the navbar now to get the dark blue background. We'll update the themes so all navbar backgrounds get the gradient.
