### ISSUE TITLE
Missing definition for dbc.CardDeck

### ISSUE THREAD

**Issue by robin-mueller** [thomaspark/bootswatch#1103]
Hello,

I'm currently working with _plotly dash_ and using the _dash bootstrap components_ (dbc) package for styling and layout of my dashboard.

I've found an issue with dbc.CardDeck where the Cards in it won't align besides each other in one row, but instead are being put underneath each other in multiple rows. This doesn't work with either of the themes, but does indeed when you use the dbc.themes submodule, which effectively just contains CDN links to the theme you want from https://www.bootstrapcdn.com/bootswatch/ .

![assets](https://user-images.githubusercontent.com/83639955/119133664-734a8600-ba3c-11eb-8e2c-7d736b629584.png)
![CardDeckNOTWorking](https://user-images.githubusercontent.com/83639955/119133665-73e31c80-ba3c-11eb-8253-afaedcaec471.png)
![CardDeckWorking](https://user-images.githubusercontent.com/83639955/119133666-73e31c80-ba3c-11eb-929d-3f45c95a4f4c.png)
![SourceNOTWorking](https://user-images.githubusercontent.com/83639955/119133667-747bb300-ba3c-11eb-9f8b-bf3c19ed912a.png)
![SourceWorking](https://user-images.githubusercontent.com/83639955/119133670-747bb300-ba3c-11eb-82b3-a914f5cb6e30.png)

In the pictures you can see, that when I'm using the _external_stylesheets_ argument to load the UNITED theme, dbc.CardDeck is working correctly, but when I'm omitting it and thus using the united-bootstrap.css file in the assets folder, it is not.

Thank you for reading.

Robin

**Comment by alain01** [comment]
Hi,
no card-deck in BT5 
https://getbootstrap.com/docs/5.0/migration/#card

**Comment by thomaspark** [comment]
Yup, sounds like you're using different versions. You can grab v4 here:
https://bootswatch.com/4/

**Comment by robin-mueller** [comment]
Thanks so much!

I copied the card deck part of the v4 theme into a seperate card-deck.css file, since I've got limited css knowledge and thus not able to recreate card decks by myself.
