### ISSUE TITLE
Sketchy swatch hides 2nd level dropdowns

### ISSUE THREAD

**Issue by dleffler** [thomaspark/bootswatch#1105]
Issue only found in the Sketchy swatch (v4 & v5), but the .dropdown-menu overflow is set to hidden which hides any 2nd level menus if you use them.

**Comment by thomaspark** [comment]
I don't believe submenus are supported in Bootstrap 4 or 5. What markup are you using?

You could set `overflow` to `visible` yourself to override it, although it causes dropdown item backgrounds to overflow their parent,

**Comment by dleffler** [comment]
I'll just do it as a local hack. I've been using nested sub-menus in bootstrap and carried over tiny javascript code and styles from v3 which still work in v5.
