### ISSUE TITLE
Flatly bs-table-accent-bg is overriding other colours

### ISSUE THREAD

**Issue by Barbara-358** [thomaspark/bootswatch#1110]
Hi,

The setting for the table class's `bs-table-accent-bg` is now seemingly overriding other colouring settings.

In `https://bootswatch.com/5/flatly/bootstrap.min.css`:
```
 .table {
    --bs-table-bg: transparent;
    --bs-table-accent-bg:#ecf0f1;
    [...]
}
```

This colours the entire table in `#ecf0f1`.
![image](https://user-images.githubusercontent.com/83152238/123353805-afc25200-d5a5-11eb-8518-2b73d6e97d81.png)

I've had this same HTML code for months now, but suddenly, unless I include an override in the `<header>` like this, my table is coloured all blue:
```
.table {
    --bs-table-accent-bg: transparent!important;
  }
```

This is my html:
```
<table class="table table-hover shadow-sm table-bordered border-info">
    <thead class="table-info"> [...] </thead>
    <tbody> [...] </tbody>
</table>
```

This is what it used to look like/looks like if I override `bs-table-accent-bg`:
![image](https://user-images.githubusercontent.com/83152238/123354213-8524c900-d5a6-11eb-8981-0360e7ef94bd.png)

What's changed?

**Comment by Barbara-358** [comment]
looking at the commit log for the latest update, seems it used to be set to transparent but not anymore:
![image](https://user-images.githubusercontent.com/83152238/123355021-22ccc800-d5a8-11eb-8de7-08c46a149f71.png)
![image](https://user-images.githubusercontent.com/83152238/123355106-50197600-d5a8-11eb-894c-4fdf49f5bccb.png)

**Comment by thomaspark** [comment]
Hey @Barbara-358, thanks for the bug report. Will take a look...

**Comment by nickhoffmann7** [comment]
Hey, I have the same problem:
Since a few days the background colors I set on table cells are getting ignored/overwritten.
I just tested it with some themes and it still doesn't seem to work with darkly and sketchy for example (cyborg, journal, minty and morph are working fine though).

**Comment by Barbara-358** [comment]
Hey @thomaspark , the download from the website (https://bootswatch.com/5/flatly/bootstrap.min.css) still has the `--bs-table-accent-bg:#ecf0f1;` CSS. When will that be updated? Thanks, be well.

**Comment by thomaspark** [comment]
Hey @Barbara-358, we'll have to wait till the next Bootstrap version to do a release and update the site, but you can grab the latest from the `v5` branch in the meantime.
