### ISSUE TITLE
quartz select view problem

### ISSUE THREAD

**Issue by catborise** [thomaspark/bootswatch#1112]
hi, quartz is very nice addition. thanks.
but there are some glitches. for example;
![image](https://user-images.githubusercontent.com/1725643/124709101-c8b2f780-df03-11eb-95e4-44d9a1cac22b.png)
form select list does not show appropriately because of color.

**Comment by thomaspark** [comment]
Hi @catborise, can you tell me what OS & browser you're on?

**Comment by catborise** [comment]
it is chrome latest

**Comment by thomaspark** [comment]
Seems to only affect Windows. Just pushed a fix.
