### ISSUE TITLE
Increase contrast between  bg.light & dropdown-menu classes

### ISSUE THREAD

**Issue by jipexu** [thomaspark/bootswatch#1113]
Hi quartz it's nice good job !
Is it possible to make one of this 2 class more dark... to avoid this ... the content of the dropdown become very difficult to read when the two classes meet ...(i would say the bg-light a little more dark will be ok ???)

Thanks

<img width="576" alt="Capture d’écran 2021-07-07 à 17 21 22" src="https://user-images.githubusercontent.com/328101/124786298-e3a75b00-df47-11eb-9668-f2323b32720d.png">

**Comment by thomaspark** [comment]
Hey @jipexu, I can darken `.bg-light` a bit, but in general I'd advise against using it at all for that reason.

**Comment by jipexu** [comment]
@thomaspark  cool thanks !
