### ISSUE TITLE
Bootswatch 5 and iOS 9 Compatibilty

### ISSUE THREAD

**Issue by s22-tech** [thomaspark/bootswatch#1114]
Is Bootswatch 5 compatible with iOS 9?  I can't get the Bootswatch hamburger to open on my iPhone.  It works fine on my Mac running 10.15.3, so it appears to be a problem with older mobile OS'es.  A friend with an older Android can't get it to work, either.  

There are no errors in developer tools.  Apart from that I'm not sure how to test further.

Is there a way to get the hamburger to work for these devices?

Thanks,
Marc

**Comment by thomaspark** [comment]
Bootstrap 5 supports iOS12 and up:

https://getbootstrap.com/docs/5.0/getting-started/browsers-devices/

**Comment by s22-tech** [comment]
Thanks, Thomas.

Does anyone have any suggestions on how to test for the browser or OS to serve either Bootswatch 4 or 5 depending on the visitor?  I read the link above but I was hoping to find a simple solution that only does this one thing.

**Comment by thomaspark** [comment]
No problem. It would be tricky to maintain since the markup for 4 and 5 is different. If older browser support is important for your project, sticking with 4 is may be the way to go.
