### ISSUE TITLE
All dark themes have poor visibility for forms

### ISSUE THREAD

**Issue by badoge** [thomaspark/bootswatch#1121]
Some form elements seem to be using the color scheme from light themes which makes them hard to read on dark themes.

![image](https://user-images.githubusercontent.com/18620902/128490772-c12a1f5d-52c5-4913-a94a-c735ab6bab30.png)
![image](https://user-images.githubusercontent.com/18620902/128491938-63e25354-64e2-45d6-a782-ab1f0fd63e35.png)

**Comment by thomaspark** [comment]
Thanks for the bug report @badoge. Input background colors are set to body background now, and have to be explicitly set to white for dark themes. Just pushed a fix.
