### ISSUE TITLE
Darkly text in input and textarea is unreadable

### ISSUE THREAD

**Issue by safetymonkey** [thomaspark/bootswatch#1123]
In the new Darkly theme for Bootstrap 5.1.0, the text in form fields such as `input` and `textarea` is completely unreadable due to being dark text on a dark background.

This shows up very clearly on the demo page: https://bootswatch.com/darkly/

**Comment by thomaspark** [comment]
Hey @safetymonkey, thanks for the bug report. This was also reported in #1121. It's been fixed, you can grab the latest from the repo for a quick fix or wait for the next release.

**Comment by safetymonkey** [comment]
Great, thank you so much for the quick reply. I searched closed issues but
missed that one somehow.

Thank you again!
