### ISSUE TITLE
Solar theme alert close button blends in with background

### ISSUE THREAD

**Issue by nCubed** [thomaspark/bootswatch#1127]
In the latest release for the Solar theme, the close buttons on all the alerts (except text-light) essentially blend in with the background. This makes the close button basically unusable as they can not be seen unless you know they are they and are looking specifically for the x button.

Adding a background color to the button helps, ex:
```
<button type="button" class="btn-close bg-light" data-bs-dismiss="alert"></button>
```

Theme: Solar
https://bootswatch.com/solar/

Any chance the alert close buttons could be updated so the close button is more visible?

**Comment by thomaspark** [comment]
Hey @nCubed, pushing a fix for this on Solar and Morph now.
