### ISSUE TITLE
Bootstrap v5.1.3

### ISSUE THREAD

**Issue by mike-halford** [thomaspark/bootswatch#1140]
Hi

Not sure this is the correct place to post but are the themes compatible with the recently released v5.1.3 of Bootstrap?

If not are there any plans to update?

Thanks

**Comment by fu-sen** [comment]
Normally, Bootswatch was updated before and after the release of Bootstrap, 
So I was wondering about this.

https://github.com/twbs/bootstrap/releases/tag/v5.1.3
