### ISSUE TITLE
Issue with selected tab's background color in yeti theme

### ISSUE THREAD

**Issue by colin-fsa** [thomaspark/bootswatch#1167]
When using the yeti theme the currently selected tab's background color is not always correct. This issue can actually be seen on the example webpage: https://bootswatch.com/yeti/

When first loading the page the 'Home' tab is selected, but then when clicking on profile the contents are changed but the background color of the profile tab is not changed. The color changes once the user clicks elsewhere on the page.

Initial page load:
![image](https://user-images.githubusercontent.com/62242803/141649013-3cf9f2e6-68bb-4478-8bec-fb125eb1bf6a.png)

User clicks on profile tab:
![image](https://user-images.githubusercontent.com/62242803/141649036-c3ea4f1b-9078-4d8f-95fa-c06a7c5e3f3a.png)

User clicks in whitespace on page:
![image](https://user-images.githubusercontent.com/62242803/141649056-23f77565-30b4-4bfc-9890-3581187c383d.png)

Thank you for your attention to this and for providing such high quality themes for us to use!

**Comment by thomaspark** [comment]
Hey @colin-fsa, thanks for the bug report. A fix is on the way.
