### ISSUE TITLE
Yeti tabs focused color

### ISSUE THREAD

**Issue by EricGrange** [thomaspark/bootswatch#1170]
The active tab with focus (after a mouse click) looks very similar to non-active tabs, and only becomes whiter when losing focus.
This makes it less obvious which tab is active, after having just clicked on a tab, and this also makes the previous tab "flash" when clicking on an other tab (because it that previous tab loses focus, becomes white, a fraction of second before the new tab gets focus, at which point the previous tab becomes grayish)

Just after clicking on Home
![image](https://user-images.githubusercontent.com/2197210/145597788-e9e1fd86-6802-4a70-8ee9-b91deadc5c9c.png)

Just after clicking on Profile
![image](https://user-images.githubusercontent.com/2197210/145597910-290920dd-3421-46c6-af93-ba526676ae6d.png)

Just after having clicked elsewhere on the page
![image](https://user-images.githubusercontent.com/2197210/145598024-56345476-92d8-4c24-84c9-3798a8c36b2e.png)

**Comment by thomaspark** [comment]
Hey @EricGrange, thanks for the bug report. This sounds similar to #1167, which has been fixed and will be included in the next release.

**Comment by EricGrange** [comment]
Yes, it is exactly the same issue, not sure why I did not find it when checking issues :/

Thanks for your work!
