### ISSUE TITLE
Any reason margin-right on cosmo theme is using me-X instead of mr-X?

### ISSUE THREAD

**Issue by Minipada** [thomaspark/bootswatch#1174]
While writing some code, I noticed that many themes are using me-X for margin right, instead of the common mr-X:
https://github.com/thomaspark/bootswatch/blob/cc9aad99713fc86cc8c6d36e0a6209271644beba/docs/5/cosmo/bootstrap.css#L7030-L7057

I'm no web developer but this seems like a typo (given that e and r are so close and mr is not used).

I will do a PR if it is a mistake.

Thank you

**Comment by alain01** [comment]
Hi,
no, since Bootstrap V4, The system is:

Start - End, no left/Right

So, it becomes for LEFT TO RIGHT Text:
me for mr
and
ms for ml 

See https://getbootstrap.com/docs/5.1/migration/#rtl

It modified for the country using LTR text ;-)

**Comment by Minipada** [comment]
Thanks!
