### ISSUE TITLE
lux scss: method theme-color not found

### ISSUE THREAD

**Issue by rburgst** [thomaspark/bootswatch#1177]
https://github.com/thomaspark/bootswatch/blob/v5/dist/lux/_bootswatch.scss#L32 uses
```
.bg-primary {
  background-color: theme-color("primary") !important;
}
```
However in bootstrap 5.1.3 this method does not seem to be defined.

**Comment by thomaspark** [comment]
Thanks @rburgst, that seems extraneous anyway. I'll push a fix now.
