### ISSUE TITLE
Set :root color-scheme dark or light

### ISSUE THREAD

**Issue by Banner-Keith** [thomaspark/bootswatch#1178]
I have a minor request to add the color-scheme value to :root. This allows the browser to know to make the scroll bar dark and other related effects.

So on all dark themes you'd just have to add:

:root {
    color-scheme: dark;
}

and for light themes you'd add

:root {
    color-scheme: light;
}

I would be happy to open a PR with this change if you're okay with it.

**Comment by thomaspark** [comment]
Hey @Banner-Keith, adding this for the next updating.
