### ISSUE TITLE
Bootswatch 4 - Sandstone input group problem

### ISSUE THREAD

**Issue by slolo2000** [thomaspark/bootswatch#1180]
Hello,

I don't really know if there is a small problem with Sandstone theme but as you can see on the screenshot, input group with prepend or append append has a problem of alignment.

![image](https://user-images.githubusercontent.com/10075509/153226386-0fe68617-57d8-456a-838f-9f790b99dad8.png)

All others themes of Bootswatch 4 work correctly.

Can you fix it please?

Thanks in advance and have a nice day.
And thank you for your work on Bootswatch.

**Comment by thomaspark** [comment]
Hey @slolo2000, it seems to be working ok for me:

<img width="607" alt="Screen Shot 2022-02-09 at 9 41 16 PM" src="https://user-images.githubusercontent.com/900407/153327013-ab83b947-dda0-498d-aec2-8ed4e628c35f.png">

https://jsfiddle.net/cj6dspwz/

**Comment by slolo2000** [comment]
Hello @thomaspark ,

You are absolutely right, I have forgotten to add "input-group-sm" to my class.
I don't know why it works for all others themes but in fact there is no problem.

Sorry for the inconvenient and thanks again for your your on this great repository.
