### ISSUE TITLE
bg-primary color is incorrect

### ISSUE THREAD

**Issue by sushantdhiman** [thomaspark/bootswatch#1185]
With Bootstrap v5, `.badge-*` classes were dropped in favor of `.bg-*` classes https://getbootstrap.com/docs/5.0/migration/#badges

After using v5 sandstone theme, I noticed incorrect badge colors are displayed. It seems for navigation `bg-primary` is overriden https://github.com/thomaspark/bootswatch/blob/0ae2eeba0b1a80877771bd83cbd458b6426d9ac8/dist/sandstone/_bootswatch.scss#L15

Due to this css override, where ever `bg-primary` is used in v5 theme, incorrect color is displayed. Examples

**Card**

![Screenshot_20220315_135617](https://user-images.githubusercontent.com/9989487/158336552-48bc9444-ee74-4cdf-bbd4-33a2e5756672.png)

**Badge**
![Screenshot_20220315_135534](https://user-images.githubusercontent.com/9989487/158336581-f4fb8028-fd54-4e32-9339-44422bb2c00d.png)

**Comment by thomaspark** [comment]
@sushantdhiman, thanks for bringing this to my attention. The bg overrides will be removed in the next release.
