### ISSUE TITLE
Include theme name in minified CSS

### ISSUE THREAD

**Issue by MisinformedDNA** [thomaspark/bootswatch#1187]
Currently, bootstrap.min.css files do not state what theme they are. For those who only use the minified CSS, they may forget what theme they are using. So I think it would be useful to add it to the header.

```css
@charset "UTF-8";/*!
 * Bootswatch v5.1.3 (https://bootswatch.com)
 * Theme: Darkly
 * Copyright 2012-2022 Thomas Park
 * Licensed under MIT
 * Based on Bootstrap
*/
```

**Comment by thomaspark** [comment]
Hey @MisinformedDNA, good suggestion — I'll add it.
