### ISSUE TITLE
Mainpanel below sidebarpanel

### ISSUE THREAD

**Issue by rafanmir** [thomaspark/bootswatch#1190]
Hi, 

I'm building an app with shiny and when I add any bootswatch theme the main panel moves below the sidebar panel. I tried forcing them to stay in the same row using fluidRow and I noticed there seems to be a right margin for both panels (screenshot below). But then I set all margins to 0  (style = "margin: 0 0 0 0"). Is there any other setting I should change so I can have the main panel next to the sidebar panel?

![Screenshot 2022-04-06 100316](https://user-images.githubusercontent.com/86676867/161993119-3d81b60b-ee46-4dac-9953-cbe105b16fe0.jpg)

**Comment by rafanmir** [comment]
I'll try that, thanks.

**Comment by rafanmir** [comment]
Just adding some info in case anyone else has the same issue. This is a problem with the bslib package, and happens with bootstrap versions 4 and 5. It can be fixed if you use sidebarLayout() for the sidebar and main panels: https://github.com/rstudio/bslib/issues/419

**Comment by thomaspark** [comment]
Thanks for the follow-up and resolution.

**Comment by nick-youngblut** [comment]
>Just adding some info in case anyone else has the same issue. This is a problem with the bslib package, and happens with bootstrap versions 4 and 5. It can be fixed if you use sidebarLayout() for the sidebar and main panels

I ran into this problem too. It would help to mention this issue in the main docs, given that many shiny app developers use `sidebarPanel(); mainPanel()`, since it is basically the default for app development.
