### ISSUE TITLE
Request: Add "Copy" button on the preview code snippet's header

### ISSUE THREAD

**Issue by yosuanicolaus** [thomaspark/bootswatch#1191]
Add a "copy to clipboard" button on the preview code's snippets.
It would be nice if we can also block Ctrl+a (select all) from selecting the whole page's text when opening the preview's source code modal.

![Screenshot from 2022-04-26 10-14-50](https://user-images.githubusercontent.com/87525599/165213635-2b534ec8-d2e6-4537-9a94-e100e7007a6e.png)
![Screenshot from 2022-04-26 10-11-48](https://user-images.githubusercontent.com/87525599/165212913-50169056-11e6-4d76-afbe-0bd9c2e4f5c2.png)

Copy to clipboard button example:
![copy_button](https://user-images.githubusercontent.com/87525599/165213938-f8b11f6d-38cd-4564-b5e4-620140fa828c.png)
![Screenshot from 2022-04-26 10-24-29](https://user-images.githubusercontent.com/87525599/165214145-0948d0e9-972d-427e-a2a8-fc89ab60db9c.png)

**Comment by thomaspark** [comment]
Adding a copy button feature!
