### ISSUE TITLE
No bold text for Sketchy theme?

### ISSUE THREAD

**Issue by jslingsby** [thomaspark/bootswatch#1201]
I'm not sure if this is a known issue or by intention, but I'm not getting any bold text for the Sketchy theme? Even in the online demo - https://bootswatch.com/sketchy/ I've looked at it on Ubuntu (Chrome and Firefox) and Mac (Chrome and Safari) and no luck?
![image](https://user-images.githubusercontent.com/1164222/181454262-395aaafe-07a6-434e-bcfc-dd56f232d76b.png)

Oterwise, thanks for great themes!!!

**Comment by thomaspark** [comment]
Good catch @jslingsby, fix inbound!
