### ISSUE TITLE
Sketchy breaks focusing on checkbox & radio inputs

### ISSUE THREAD

**Issue by benjaminpoulin** [thomaspark/bootswatch#1203]
v5.2.0 Sketchy makes radio buttons and checkboxes unfocusable/untabbable, causing tabbing to skip these elements entirely. This issue is present on the [example page](https://bootswatch.com/sketchy/); try tabbing to Checkbox 1/2/3 and Radio 1/2/3. No other themes (including default bootstrap) have this issue.

I've been patching Sketchy with
```css
.btn-check {
    display: inline-block;
    opacity: 0;
}
```
which overrides the Sketchy-specific style
https://github.com/thomaspark/bootswatch/blob/d982c0baf3e425df284cbefa1a12620d6fbaf6e0/dist/sketchy/_bootswatch.scss#L61-L63

**Comment by thomaspark** [comment]
Thanks @benjaminpoulin, fixing the tabbing issue and adding focus styles to radio and checkbox inputs.
