### ISSUE TITLE
Darkly headers and running text now black and hard to read

### ISSUE THREAD

**Issue by PanderMusubi** [thomaspark/bootswatch#1207]
Darkly https://bootswatch.com/darkly/ used to have white headers and white running text. Now it is black and is very hard top read. Please fix this.

**Comment by PanderMusubi** [comment]
Seems to be a problem only in Firefox 104.0.1~1661960476~22.04~f77767e on Ubuntu. Also rendering of any README.md in GitHub with dark theme has this issue. Chrome on Ubuntu does not have that issue.

**Comment by thomaspark** [comment]
Thanks, I can't replicate this on Firefox/Mac 104.0.2. Perhaps you can open a ticket with FF.

**Comment by PanderMusubi** [comment]
Has indeed been fixed in Firefox `104.0.2~1662490162~22.04~faed4ab`.
