### ISSUE TITLE
btn-outline-secondary hard to read on some skins

### ISSUE THREAD

**Issue by barisusakli** [thomaspark/bootswatch#1211]
https://getbootstrap.com/docs/5.2/components/buttons/#outline-buttons

Seems like some skins set the secondary color too close to body-bg color causing the `btn-outline-secondary` buttons to be washed out.

Skins that are affected are cerulean, lumen, yeti. The other light themes all have enough contrast.

**Cosmo skin looks good ($secondary: $gray-800;)**
![image](https://user-images.githubusercontent.com/2583394/190535987-7f1c8a8a-0f7b-4a0f-82fa-081ff518399b.png)

**Washed out on lumen ($secondary: $gray-200)**
![image](https://user-images.githubusercontent.com/2583394/190535668-71fdc45c-fa26-477a-b87d-07dc12528d50.png)

**Default bootstrap ($secondary: $gray-600)**
![image](https://user-images.githubusercontent.com/2583394/190535645-82ff3ae2-9ee6-42d2-8270-86bd55f7ece8.png)

**Comment by thomaspark** [comment]
There can be places where a light-colored outline button is useful, but we'll leave that work for `btn-outline-light`. I do think `bt-outline-secondary` should be usable in the same contexts as `btn-outline-primary`, in this case with light backgrounds. I'll darken text color on Cerulean, Lumen, and Yeti to improve contrast.

**Comment by barisusakli** [comment]
@thomaspark thanks 👍🏼
