### ISSUE TITLE
Sandstone Modal doesn't work

### ISSUE THREAD

**Issue by ElMondaca** [thomaspark/bootswatch#1216]
I've tried to use it on several times in different ways but i can't manage to make it work, i don't know if i'm doing something wrong or not, but i copied the clean code on an empty HTML document (with the propper functional tags) as the main Booststrap way to do it

**Comment by thomaspark** [comment]
Did you include [Bootstrap's JS](https://getbootstrap.com/docs/5.2/getting-started/javascript/) as well?

Try replacing Sandstone with vanilla Bootstrap or a different theme may help you narrow down your issue.

**Comment by ElMondaca** [comment]
I downloaded JS files and then it worked.... thanks a lot!
