### ISSUE TITLE
site footer informations (icons) 

### ISSUE THREAD

**Issue by jipexu** [thomaspark/bootswatch#1217]
Hi
on the footers of the themes ie : https://bootswatch.com/cerulean/
we have
Based on [Bootstrap](https://getbootstrap.com/). Icons from [Font Awesome](https://fontawesome.com/). Web fonts from [Google](https://fonts.google.com/).

Perhaps it will be fine to update the "Icons from" to bootstrap-icons as fontawesome are no more used here ? 

Thanks

**Comment by thomaspark** [comment]
That should absolutely be updated, thanks!
