### ISSUE TITLE
jumbotron issue

### ISSUE THREAD

**Issue by spyhunter99** [thomaspark/bootswatch#1226]
Not sure what's going on here, but i'm using the latest v4.x bootstrap and just screwing around with a hello world site based on the jumbotron sample with a fixed top navbar. Seems like the bootstrap out of the box setup has enough padding it in to move the jumbotron content down below the nav bar, but all of the themes i've tried from bootswatch (which are awesome) do not seem to have this padding in effect. Could it be something with the jumbotron class or perhaps are the bootswatch themes tailored for bootstrap5 or 3 maybe? appreciate any guidance on this

**Comment by spyhunter99** [comment]
hmm i think i answered my own question, bootswatch is for bootstrap5 which has some differences. i examined the samples provided and did some creative copy and pasting and got the desired effect.

**Comment by thomaspark** [comment]
Glad you got it figured out. There are Bootswatch themes for v4 here: https://bootswatch.com/4/
