### ISSUE TITLE
Different list-group-item colors

### ISSUE THREAD

**Issue by christophe-fms** [thomaspark/bootswatch#1228]
Hello,

With bootstrap 5 i use list-group-item-danger to have colored lists, in red (with the slate theme). In the preview there is no examples with colored lists. If you apply the class list-group-item-danger, the list will be in light red (#fcdfde), whereas all the other danger class (buttons, tables, alerts etc) are in "normal" red (#ee5f5b). 
Don't you think it should be the same color ? Final users may not understand why we have 2 different colors for danger events

Best regards

**Comment by thomaspark** [comment]
It will depend on the theme, but in the case of Slate I agree the same red works better.

I'll add the different list-group-item colors to the docs, and update Slate.
