### ISSUE TITLE
[Sketchy] checkbox indeterminate state visually identical to unchecked state

### ISSUE THREAD

**Issue by davebaol** [thomaspark/bootswatch#1234]
Checkbox indeterminate state is visually identical to unchecked state.
It happens only with theme Sketchy.

![image](https://user-images.githubusercontent.com/2366334/216938764-d35521ce-dc88-405f-8b6d-d6915af8bf75.png)

**Comment by thomaspark** [comment]
Fix is on the way:

<img width="234" alt="Screenshot 2023-02-06 at 11 53 55 AM" src="https://user-images.githubusercontent.com/900407/217034213-5690139a-4e4d-4d0f-8273-001c995004da.png">

**Comment by davebaol** [comment]
Great!!!
Thanks a lot @thomaspark
