### ISSUE TITLE
gray-200 is too dark on superhero skin

### ISSUE THREAD

**Issue by barisusakli** [thomaspark/bootswatch#1236]
Hello 
seems like $gray-200 is too dark on superhero skin causing issues when used with a darker gray as background like so
```
.element {
  background: $gray-700;
  color: $gray-200;
}
```

![image](https://user-images.githubusercontent.com/2583394/218287855-e308860f-c80b-4384-856e-13c28d44e668.png)

**Comment by thomaspark** [comment]
Thanks, the grays will be re-ordered:

<img width="247" alt="Screenshot 2023-02-14 at 11 56 58 AM" src="https://user-images.githubusercontent.com/900407/218805303-c85f9373-dfba-4ece-9563-9a10836a0c09.png">

**Comment by barisusakli** [comment]
@thomaspark thanks 👍🏼
