### ISSUE TITLE
Disabled html select formatting is consistent among the themes

### ISSUE THREAD

**Issue by spyhunter99** [thomaspark/bootswatch#1238]
I ran into a few minor issues with html select boxes not having consistent visualization across themes when adding or removing the disabled attributed. Here's some examples

Example for darkly
![image](https://user-images.githubusercontent.com/1975321/221419735-e11f5a95-e39d-48c7-847f-88f906ca6fb4.png)

Solar, note that non disabled are an off white color, and disabled is the default white
![image](https://user-images.githubusercontent.com/1975321/221419827-2ed3263b-e98f-411c-9146-c14477278bf0.png)

Vapor, note that non disabled are dark purple color, and disabled is the default white
![image](https://user-images.githubusercontent.com/1975321/221419868-6e2d767f-be32-44bf-b589-9caf58737f2e.png)

Quartz, in this case both the password box and the select have the disabled flag, select is a white background with disabled and without disabled is a transparent setup
![image](https://user-images.githubusercontent.com/1975321/221419944-03d3586b-4976-421e-9f07-0fea23499c53.png)

Might also be a good idea to edit the bootswatch demo pages to have examples of disabled inputs for all types to verify consistency

**Comment by thomaspark** [comment]
@spyhunter99, thanks for the suggestion. Fix incoming.
