### ISSUE TITLE
Deprecation warnings with latest dart-sass

### ISSUE THREAD

**Issue by rdicroce** [thomaspark/bootswatch#1248]
Beginning with dart-sass 1.62.0, [duplicate flags](https://sass-lang.com/documentation/breaking-changes/duplicate-var-flags) are deprecated and produce a warning. That will become an error in 2.0.0.

Bootswatch has at least 6 places that trigger this warning:

- In the solar theme: navbar-light-color and navbar-light-active-color
- In the litera theme: input-group-addon-bg
- In the flatly theme: nav-link-padding-y and nav-link-disabled-color

**Comment by XhmikosR** [comment]
Will be fixed by #1246

**Comment by simondubois** [comment]
Thank you @thomaspark for this great package well maintained and thank you @XhmikosR for fixing this issue.
Is there any chance to bring this fix to the v4 branch ?

**Comment by XhmikosR** [comment]
We don't support v4-dev anymore upstream, so it's up to @thomaspark if he wants to backport the fixes and cut a new 4.x patch version.
