### ISSUE TITLE
Support for Bootstrap 5.3

### ISSUE THREAD

**Issue by dartie** [thomaspark/bootswatch#1251]
Bootstrap 5.3 introduced support for dark mode. 
Each theme should be available for both light and dark mode using the native Bootstrap implementation [https://getbootstrap.com/docs/5.3/customize/color-modes/#dark-mode](https://getbootstrap.com/docs/5.3/customize/color-modes/#dark-mode)

**Comment by Frischid** [comment]
see also #1229 :+1:

**Comment by dleffler** [comment]
Bootstrap 5.3.0 final has been released

**Comment by thomaspark** [comment]
Bootswatch 5.3.0 has just been released:
https://github.com/thomaspark/bootswatch/releases/tag/v5.3.0
