### ISSUE TITLE
cdn not works

### ISSUE THREAD

**Issue by fiorins** [thomaspark/bootswatch#1260]
Hi, did cdn stopped to work ? I have this link **https://bootswatch.com/flatly/bootstrap.min.css** that doesn't load

**Comment by thomaspark** [comment]
You can use jsDelivr:
https://cdn.jsdelivr.net/npm/bootswatch@5.3.0/dist/flatly/bootstrap.min.css

The site files were moved to:
https://bootswatch.com/5/flatly/bootstrap.min.css

**Comment by fiorins** [comment]
Ok, thanks, I didn't know it!
