### ISSUE TITLE
Morph is messed up

### ISSUE THREAD

**Issue by InsightfulFuture** [thomaspark/bootswatch#1266]
My favorite bootswatch is morph. I would use it for everything, but the button in an input group is so messed up!
![image](https://github.com/thomaspark/bootswatch/assets/109481728/8c3f3acb-3537-4386-a8f2-3a26ac9d2eea)
I think it should look like the file input button or similar:
![image](https://github.com/thomaspark/bootswatch/assets/109481728/bfef4ff4-1a25-4d9e-8b63-37aa9060b7c0)

**Comment by InsightfulFuture** [comment]
Also this: 

https://github.com/thomaspark/bootswatch/assets/109481728/4a1e4a02-e5dc-44d8-8e11-08b37fcdb2e8

**Comment by thomaspark** [comment]
Fix inbound:
<img width="472" alt="Screenshot 2023-07-27 at 5 56 10 PM" src="https://github.com/thomaspark/bootswatch/assets/900407/74082176-7796-4573-8dc4-1313f5cfa1fb">
