### ISSUE TITLE
Table text color is dark on darkly theme

### ISSUE THREAD

**Issue by barisusakli** [thomaspark/bootswatch#1276]
Darkly

![image](https://github.com/thomaspark/bootswatch/assets/2583394/c95aee31-4b51-45e4-ac5c-3393e408b8ce)

vs Cyborg

![image](https://github.com/thomaspark/bootswatch/assets/2583394/56511d32-c8a0-43ad-be03-ed62d5fa9d98)

**Comment by barisusakli** [comment]
@thomaspark seems like superhero and solar have the same issue, not sure if it's already fixed.

superhero
![image](https://github.com/thomaspark/bootswatch/assets/2583394/be05f33b-10ed-45e5-812e-cf4c0b2b5fc9)

solar 
![image](https://github.com/thomaspark/bootswatch/assets/2583394/7598d792-6ac1-4cf4-9446-8b300a720120)

**Comment by thomaspark** [comment]
Superhero was fixed in #1279, just awaiting next release.

I'll push a fix for Solar now.

![Screenshot 2024-01-12 at 9 02 59 AM](https://github.com/thomaspark/bootswatch/assets/900407/19f02b7c-2b1f-4f0e-8b57-988fbee71dc5)
