### ISSUE TITLE
List-group-item too bright with slate theme

### ISSUE THREAD

**Issue by christophe-fms** [thomaspark/bootswatch#1277]
Hello,

Is it possible to darken a little list-group-items for the slate theme ? It is too bright and messages are difficult to read. In earlier versions it was nice (darker).
Best regards (and thanks for your great work)

New version (too light)
![new_list_group](https://github.com/thomaspark/bootswatch/assets/47887993/e9057090-719a-42d1-bffc-a1dab09f5e1f)

Old version (perfect)
![old_list_group](https://github.com/thomaspark/bootswatch/assets/47887993/428e7827-1a46-458d-9aba-e619fba39d69)

**Comment by christophe-fms** [comment]
You're the boss 👍

**Comment by thomaspark** [comment]
Here's the new version btw:

![Screenshot 2023-09-28 at 8 49 27 AM](https://github.com/thomaspark/bootswatch/assets/900407/5e35244b-7786-47f3-9fcd-341689430efb)

Also updated accordions from:

![Screenshot 2023-09-28 at 8 50 07 AM](https://github.com/thomaspark/bootswatch/assets/900407/e1671dba-6d28-4510-8b78-a8fef5923159)

To:

![Screenshot 2023-09-28 at 8 50 27 AM](https://github.com/thomaspark/bootswatch/assets/900407/ed604360-5413-4f47-ac4e-2526fdaf7143)
