### ISSUE TITLE
5.3.2 Superhero table color

### ISSUE THREAD

**Issue by Balkoth** [thomaspark/bootswatch#1279]
Default table color is black and not readable.
Seems this was fixed for darkly in https://github.com/thomaspark/bootswatch/commit/333001ba080b7e83254c2b1f3f619703d18358f8

**Comment by thomaspark** [comment]
Thanks for reporting. Fix on the way:

![Screenshot 2023-10-06 at 9 41 18 AM](https://github.com/thomaspark/bootswatch/assets/900407/c93c3b77-04e3-4815-a696-e0dfca66b99f)
