### ISSUE TITLE
Morph Dark Mode Dialog Readability Issues

### ISSUE THREAD

**Issue by dbq-andersons** [thomaspark/bootswatch#1282]
Good Day,

When Morph is flipped to dark mode, Modals, Popovers, and Toasts have limited readability due to the fonts being too light compared to their background.

![morph-dark-mode-readability](https://github.com/thomaspark/bootswatch/assets/43183321/425ffa0d-2b1b-49e7-af49-53cbb5d582f6)

If I'm missing a switch or something, please let me know.

Cheers,

Bill Anderson

**Comment by thomaspark** [comment]
Pushing styles for these components in dark mode:

![Screenshot 2023-10-23 at 1 48 24 PM](https://github.com/thomaspark/bootswatch/assets/900407/68bff08c-282e-4adc-88ab-1f31fef36479)

**Comment by thomaspark** [comment]
Not a problem, pushing a fix for secondary and light cards in dark mode.

**Comment by dbq-andersons** [comment]
Thanks Thomas!

Have a great day,

Bill
