### ISSUE TITLE
Darkly - Table Text 5.3

### ISSUE THREAD

**Issue by ctgbarcalow** [thomaspark/bootswatch#1287]
The new default table text for Darkly in 5.3 is back on black. I'm not sure that was intended as it's previously been the standard body color up until now.

![image](https://github.com/thomaspark/bootswatch/assets/85701261/ee0ca91b-71b6-474e-ac8c-d23e4c1ad832)

**Comment by thomaspark** [comment]
This was fixed in #1276 and will be merged in the next version.

![Screenshot 2023-11-28 at 8 36 40 PM](https://github.com/thomaspark/bootswatch/assets/900407/54cc2440-64c6-45d0-9e09-5bd3ab2af537)

**Comment by ctgbarcalow** [comment]
Thank you, and sorry for the duplicate.
