### ISSUE TITLE
The input box has an inappropriate background color under a dark theme.

### ISSUE THREAD

**Issue by fxzxmic** [thomaspark/bootswatch#1291]
![image](https://github.com/thomaspark/bootswatch/assets/54622331/6405fe2d-c017-42ad-a183-8d5b3b1cfe2a)
Completely unable to see the characters in the input box.
`background-color: #f7f7f9;`

**Comment by thomaspark** [comment]
Pushing a fix for Lux dark mode now:

![Screenshot 2024-01-14 at 9 52 34 PM](https://github.com/thomaspark/bootswatch/assets/900407/bcc7f889-49de-4149-9150-8a674978ddd1)

**Comment by fxzxmic** [comment]
@thomaspark Is white text and a dark background more suitable for a dark mode page?
