### ISSUE TITLE
Superhero: floating labels are jumpy

### ISSUE THREAD

**Issue by martinburger** [thomaspark/bootswatch#1292]
Theme: Superhero
Version: 5.3.1

If you focus an input field with a floating label, that field slightly increases its height. This causes a vertical form with multiple such input fields to be jumpy.

**Comment by martinburger** [comment]
Thank you for your incredibly quick resolution.

Is there a way to download such fixes via npm? As far as I can see, I can only download versions that are directly tied to the official versions of bootstrap.

However, those versions do not include the latest fixes like the one related to this issue.

**Comment by thomaspark** [comment]
Yes, you should able to use something like this with the hash for the version:

``git+ssh://git@github.com/thomaspark/bootswatch.git#36b93e93619a7c23654b80f053adc5aaf81b1c6a``

**Comment by martinburger** [comment]
Thanks a lot for the tip. You taught me something new. What makes this a great day. 👍

After reading [the fine manual](https://docs.npmjs.com/cli/v10/commands/npm-install), I just found out that the following command is all that is needed:

```bash
❯ npm install 'github:thomaspark/bootswatch#36b93e9'
```
