### ISSUE TITLE
Packagist doesn't auto-update

### ISSUE THREAD

**Issue by marclaporte** [thomaspark/bootswatch#1296]
https://github.com/thomaspark/bootswatch/tags is at 5.3.3

https://packagist.org/packages/thomaspark/bootswatch is at 5.3.1

Thanks!

**Comment by thomaspark** [comment]
Thanks for the heads up. It's updated and should auto-update going forward.

https://packagist.org/packages/thomaspark/bootswatch#v5.3.3
