### ISSUE TITLE
nav-underline are not well handled for active items

### ISSUE THREAD

**Issue by epoupon** [thomaspark/bootswatch#1302]
Hello,

Looks like when using `nav-underline` addition, the active color is not the expected one.
This makes for example the solar theme impossible to use with this modifier.

Thanks!

**Comment by thomaspark** [comment]
Hi @epoupon,

I'm adding a `nav-underline` example to the docs and fixing the active color for dark themes:

![Screenshot 2024-04-17 at 12 35 36 PM](https://github.com/thomaspark/bootswatch/assets/900407/35f654ee-0f58-42ec-b714-986dc1b275a2)
