### ISSUE TITLE
Poor contrast with sketchy in dark mode

### ISSUE THREAD

**Issue by 2dareis2do** [thomaspark/bootswatch#1303]
When using sketchy in dark mode, the breadcrumb trail has really poor contrast.

Please see how it compares to the default mode (all modes)

<img width="678" alt="Screenshot 2024-04-22 at 23 26 29" src="https://github.com/thomaspark/bootswatch/assets/1718370/a61351da-956d-4695-81d8-462e70cbc06f">
<img width="686" alt="Screenshot 2024-04-22 at 23 24 10" src="https://github.com/thomaspark/bootswatch/assets/1718370/8af409fd-2ce9-4b89-b66d-a888b2e0ed36">
<img width="680" alt="Screenshot 2024-04-22 at 23 26 52" src="https://github.com/thomaspark/bootswatch/assets/1718370/b7494562-21ce-48dd-b461-c524592dccb3">
<img width="709" alt="Screenshot 2024-04-22 at 23 23 13" src="https://github.com/thomaspark/bootswatch/assets/1718370/285bafb1-00c0-4bc1-aa76-49bad4298126">

**Comment by 2dareis2do** [comment]
From what I can see the breadcrumb is set to `#333` as opposed to test-primary that appears closer to `#555`, the same as the secondary colour. Similar issue with active tab which has the same colour
 
<img width="1311" alt="Screenshot 2024-04-22 at 23 43 34" src="https://github.com/thomaspark/bootswatch/assets/1718370/4584f95e-5843-42eb-b4ac-f61ecdcae042">
<img width="1321" alt="Screenshot 2024-04-22 at 23 46 46" src="https://github.com/thomaspark/bootswatch/assets/1718370/9cb65acc-7992-40e9-ab39-cc1c7b94ec13">
<img width="1311" alt="Screenshot 2024-04-22 at 23 48 37" src="https://github.com/thomaspark/bootswatch/assets/1718370/d842f6ee-049d-4eae-b8cd-310164b8c2c5">

**Comment by thomaspark** [comment]
I'm pushing some changes to Sketchy. Here's how it's looking in dark and light mode now:

![Screenshot 2024-04-22 at 9 20 09 PM](https://github.com/thomaspark/bootswatch/assets/900407/7a0200f5-a0d9-4c55-a971-d1aa64d758a3)

![Screenshot 2024-04-22 at 9 21 40 PM](https://github.com/thomaspark/bootswatch/assets/900407/5f4039bd-53a3-4966-adac-e897d5815d89)

**Comment by 2dareis2do** [comment]
That contrast looks much better.

Thank you.
