### ISSUE TITLE
`th`'s color is not set in v5

### ISSUE THREAD

**Issue by bblanchon** [thomaspark/bootswatch#1308]
Hi!

Thank you very much for this fantastic project!

I've been using v4 for a while, but after upgrading to v5, I noticed the contrast was too strong on table headers.
I inspected all the themes to check the `color` assigned to `th`, and they are all either full black or full white, nothing in between.

Here is a comparison of the `th`'s color between v4 and v5:

| Theme     | v4                   | v5                   |
|:----------|:---------------------|:---------------------|
| Cerulean  | `rgb(73, 80, 87)`    | `rgb(0, 0, 0)`       |
| Cosmo     | `rgb(55, 58, 60)`    | `rgb(0, 0, 0)`       |
| Cyborg    | `rgb(255, 255, 255)` | `rgb(255, 255, 255)` |
| Darkly    | `rgb(255, 255, 255)` | `rgb(255, 255, 255)` |
| Default   | `rgb(33, 37, 41)`    | `rgb(0, 0, 0)`       |
| Flatly    | `rgb(33, 37, 41)`    | `rgb(0, 0, 0)`       |
| Journal   | `rgb(34, 34, 34)`    | `rgb(0, 0, 0)`       |
| Litera    | `rgb(52, 58, 64)`    | `rgb(0, 0, 0)`       |
| Lumen     | `rgb(34, 34, 34)`    | `rgb(0, 0, 0)`       |
| Lux       | `rgb(85, 89, 92)`    | `rgb(0, 0, 0)`       |
| Materia   | `rgb(68, 68, 68)`    | `rgb(0, 0, 0)`       |
| Minty     | `rgb(136, 136, 136)` | `rgb(0, 0, 0)`       |
| Pulse     | `rgb(68, 68, 68)`    | `rgb(0, 0, 0)`       |
| Sandstone | `rgb(62, 63, 58)`    | `rgb(0, 0, 0)`       |
| Simplex   | `rgb(33, 37, 41)`    | `rgb(0, 0, 0)`       |
| Sketchy   | `rgb(33, 37, 41)`    | `rgb(0, 0, 0)`       |
| Slate     | `rgb(255, 255, 255)` | `rgb(255, 255, 255)` |
| Solar     | `rgb(131, 148, 150)` | `rgb(255, 255, 255)` |
| Spacelab  | `rgb(119, 119, 119)` | `rgb(0, 0, 0)`       |
| Superhero | `rgb(235, 235, 235)` | `rgb(255, 255, 255)` |
| United    | `rgb(51, 51, 51)`    | `rgb(0, 0, 0)`       |
| Yeti      | `rgb(34, 34, 34)`    | `rgb(0, 0, 0)`       |

As you can see, all the dark themes use `rgb(255, 255, 255)`, and all the light themes use `rgb(0, 0, 0)`.
I don't think that's intentional.

Please let me know if you want me to create a PR.

Best regards,
Benoit

**Comment by bblanchon** [comment]
Visual comparison:

![image](https://github.com/user-attachments/assets/daa8745b-d7e6-4f89-af45-8f9c7860846f)

**Comment by thomaspark** [comment]
@bblanchon, thanks for opening this issue.

I find the black/white color of v5 to be bolder, more readable, and more fitting for headings, and am inclined to keep them. But I welcome discussion on it!

**Comment by bblanchon** [comment]
I think the whole point of themes is to get out of the default "corporate" look of Bootstrap and Sketchy is a perfect example.
Minty brings a soft feminine touch, and I believe the text color is an essential part of it.

Look at the rest of the theme, you'll not see any other pure black element.

![image](https://github.com/user-attachments/assets/a341e56d-1fcd-4a80-95ae-df1893a8cec8)

**Comment by juliareymann** [comment]
Hi 
I jump on the conversation; I also use this theme, and I much prefer the previous version with the grey. It's a better good looking. I like the Camaieu effect.
So, if it's possible to go back to grey instead of black, I would really appreciate it.
Thank you

**Comment by thomaspark** [comment]
All around fair points.

@bblanchon, if you're up for it, I'd welcome to a PR for this.
