### ISSUE TITLE
Question about card and vr on vapor theme

### ISSUE THREAD

**Issue by ga1008ne** [thomaspark/bootswatch#1318]
are ```.card``` styling on vapor themes supposed to works like this?
![Screenshot 2024-11-05 120348](https://github.com/user-attachments/assets/5a20f7e5-4156-4ed2-b711-e8a9d3db377c)

and 
``` <div class="vr"></div> ```
they are invisible?
![Screenshot 2024-11-05 131451](https://github.com/user-attachments/assets/46334aa7-8683-4f51-8957-60af336fdecd)
![Screenshot 2024-11-05 132932](https://github.com/user-attachments/assets/99274f11-b73d-479f-ab0d-b6be977c052f)

**Comment by thomaspark** [comment]
A bg color class like `bg-primary` should be added to the card.

`.vr` should be visible. I'll post a fix for that shortly.

**Comment by ga1008ne** [comment]
Thanks for reply sir

i don't think you need ```bg-primary``` for ```.card``` bg color because when you look at 
the screenshot i posted before on the second ```.card``` it has ```--bs-card-bg: var(--bs-body-bg);``` with the same ```.card```

or maybe the styling on vapor theme intended to be the same with quartz theme for ```.card```?
![Screenshot 2024-11-06 100837](https://github.com/user-attachments/assets/ce248acf-ba91-421d-a009-99f64d677eb1)

**Comment by ga1008ne** [comment]
Thanks for reply sir

sorry if i misunderstood but i don't think you need class like ```.bg-primary``` for ```.card``` isn't? unless you want to be set to spesific color?
because if you look on screenshot i posted it had 2 ```.card``` styling that say ```background-color: transparent;``` and the 2nd ```.card``` say ```--bs-card-bg: var(--bs-body-bg);```
but actually i can just override ```background-color: transparent;``` by using custom css to ```--bs-card-bg: var(--bs-body-bg);```

so i thought maybe the ```.card``` styling is similar to quartz themes for vapor themes
![Screenshot 2024-11-06 100837](https://github.com/user-attachments/assets/6bddb7b7-199e-4502-93de-1a07362ff4af)
