### ISSUE TITLE
Cyborg: Error: 3.5rem and 0 are incompatible

### ISSUE THREAD

**Issue by pglombardo** [thomaspark/bootswatch#1319]
Hi @thomaspark - I bundle these themes in [Password Pusher](https://github.com/pglombardo/PasswordPusher) and it has been great and much appreciated.

With a recent update `cyborg` is reporting:

```
sass --quiet-deps ./app/assets/stylesheets/application.bootstrap.scss:./app/assets/builds/application.css --no-source-map --load-path=node_modules --load-path=app/assets/stylesheets --load-path=vendor/stylesheets
13:54:47 css.1    | Error: 3.5rem and 0 are incompatible.
13:54:47 css.1    |      ╷
13:54:47 css.1    | 2615 │   height: calc(3.5rem + calc(0 * 2));
13:54:47 css.1    |      │                ^^^^^^^^^^^^^^^^^^^^
13:54:47 css.1    |      ╵
13:54:47 css.1    |   app/assets/stylesheets/themes/selected.css 2615:16      @use
13:54:47 css.1    |   app/assets/stylesheets/application.bootstrap.scss 12:1  root stylesheet
13:54:47 css.1    | error Command failed with exit code 65.  
```

I'm using the raw `.css` files.  I could switch over to the `.scss` but haven't tried that yet.

Not sure if it is a theme bug or something needs to be updated on my side.

**Comment by thomaspark** [comment]
Hi @pglombardo, I just pushed a fix for this. Can you confirm the css/scss error is resolved for you?

**Comment by pglombardo** [comment]
Confirmed.  I pulled the update in https://github.com/pglombardo/PasswordPusher/pull/2942 and all looks good now.  Thanks @thomaspark!
