### ISSUE TITLE
Bootswatch API Version

### ISSUE THREAD

**Issue by dbtek** [thomaspark/bootswatch#271]
3.2.0 update does not appear on http://api.bootswatch.com/3/. API is still on 3.1.1.

**Comment by dbtek** [comment]
Hi @thomaspark,

I guess it's happening again. API is on 3.3.2. Is it more reliable or convenient to use github releases api for [bootswatch-dist](https://github.com/dbtek/bootswatch-dist)?

**Comment by thomaspark** [comment]
Hey @dbtek, sorry about that, oversight on my part — forgot to restart the app.

I've updated the API, but would have to say releases is more reliable.

**Comment by dbtek** [comment]
Much thanks @thomaspark.
