### ISSUE TITLE
Material Design theme

### ISSUE THREAD

**Issue by nickserv** [thomaspark/bootswatch#276]
I think that Google's [Material Design](http://www.google.com/design/spec/material-design/introduction.html) would make an interesting candidate for a bootswatch theme.

I have started work on this since I'm curious what it would look like with Bootstrap and I want to learn to create my own bootswatch, though I would be interested in eventually submitting my theme if there is an interest and I can complete it.

Note that the Material Design spec involves some things like animations and new kinds of components that could be difficult to replicate completely without implementing new features. However, I think this would still at least look nice with existing Bootstrap features, in the spirit of themes like Yeti and Cyborg.

**Comment by dandv** [comment]
@FezVrasta vs. Paper - how do they compare?

Would love a darker version of Paper!
