### ISSUE TITLE
paper - buttons - rounded buttons support

### ISSUE THREAD

**Issue by rayshan** [thomaspark/bootswatch#303]
Would be nice to have an option. Reference:
http://www.google.com/design/spec/components/buttons.html#

**Comment by thomaspark** [comment]
Add-on seems the way to go. If you allow for JS add-on, the potential for material-design-like stuff expands greatly too.

For now, please style up your own rounded buttons if needed.

**Comment by homerjam** [comment]
Totally see your point about keeping to the bootstrap api for simplicity. My preference would be for a non js addon - theres a number of alternatives on that front that are framework specific. The great thing about bootswatch is that its framework agnostic.
