### ISSUE TITLE
Paper - general suggestions for improvement

### ISSUE THREAD

**Issue by kristenmills** [thomaspark/bootswatch#304]
While the paper theme looks nice, it seems to be lacking some of the qualities of the material design that I think could be implemented and still conforming to generally qualities of bootstrap/bootswatch themes.  Animations are not really present at all.  Maybe the floating labels should raise. Ink for the buttons and tabs and other things you click on. I'd also work on the checkboxes and radio buttons. Finally, there is a list of colors that Google recommends for a palette. It would be cool if we could use those. 

I can take a stab at some of these changes but I just wanted to address them first.

**Comment by runar** [comment]
Has there been any development on this since October? :)

**Comment by nahtnam** [comment]
Not that I know of.

**Comment by thomaspark** [comment]
Closing this in favor of more specific feature-based issues like #393. Feel free to continue discussion though.
