### ISSUE TITLE
Tag names causing bower error on windows

### ISSUE THREAD

**Issue by rwhitmire** [thomaspark/bootswatch#325]
when trying to restore package ~3.2.0+4, I get the following error:
ENORESTARGET Tab/branch ~3.2.0+4 does not exist.

The '+' seems to be the culprit. I realize this is probably a bower bug, but the plus symbol seems like a strange convention and I can see how it might clash with URL encoding. Maybe you could change that convention for future releases?

**Comment by cyrilchaponeverysens** [comment]
Why was that close ?
