### ISSUE TITLE
Update Paper Buttons

### ISSUE THREAD

**Issue by ghost** [thomaspark/bootswatch#329]
Hey!

Just a quick suggestion for improvements:

The buttons in Paper should have this animation in the background: http://material-design.storage.googleapis.com/videos/animation-responsiveinteraction-inkreactions-notouchripplepressandrelease_large_xhdpi.webm

**Comment by dandv** [comment]
The [Polymer Paper ripple effect](https://elements.polymer-project.org/elements/paper-ripple?active=paper-ripple&view=demo:demo/index.html) does take into account the location of the tap/click.

**Comment by net** [comment]
The JS could be optional.

**Comment by thomaspark** [comment]
Haven't looked around, but I expect there are some JS libraries that handle this. If anyone has tried using them with Paper, let us know how that goes. If there are issues, I'm willing to get things compatible on this end.
