### ISSUE TITLE
Add config.json

### ISSUE THREAD

**Issue by wpsmith** [thomaspark/bootswatch#340]
Is it possible to add the config.json files??

**Comment by N6REJ** [comment]
@jenil27 huh?  thats as clear as mud.  I'm making a template based off darkly with some customization's and having a few issues that probably would not be an issue if I customized the .less and recompiled it.  When I went to see if there was some kind of an "import" i.e. modify what you have now, it requested the config.json ergo me coming here

**Comment by thomaspark** [comment]
@N6REJ, are you talking about importing to Bootstrap's customize feature (http://getbootstrap.com/customize/) or a different tool?

**Comment by N6REJ** [comment]
yes, I'd like to be able to take a variables/bootswatch.less and import 
it and then change only what I dont' like
Bear

**Comment by thomaspark** [comment]
Sorry, that is not supported as the themes make more extensive changes than is possible with the official Bootstrap customizer.
