### ISSUE TITLE
Select inputs in Paper are missing arrows in Chrome

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/bootswatch#358]
With the use of `-webkit-appearance: none;` to remove border-radius in webkit, the select arrow is missing in Paper.

As stated in #348, one idea is to remove the default select style for all browsers and add our own arrows using :before/:after pseudoelements. A bonus is that we can make these arrows consistent with the ones on the dropdowns.

Relevant for Firefox: https://gist.github.com/joaocunha/6273016/

**Comment by thomaspark** [comment]
Firefox supports -moz-appearance now, but then I discovered selects don't allow before/after pseudo-elements.

Hacky as it is, my fix is to use a base-64 encoded background image for the arrows.

**Comment by hebbet** [comment]
i think that is the best.
