### ISSUE TITLE
Fullscreen mode on Cyborg produces a different template (or base template) look

### ISSUE THREAD

**Issue by jancel** [thomaspark/bootswatch#379]
When going into fullscreen mode on Chrome (at least), the computed values on the HTML element seem to come from the standard bootstrap, they aren't the same colors from Bootswatch theme.

```slim
    footer.footer.text-center
      ul.list-inline.text-muted
        li &copy;Picture This
        li
          a href="tel:+13148675309"
            i.fa.fa-phone
            |&nbsp;(314) 857-5309
        li Saint Charles, MO. 63303
```

Fullscreen mode

![screen shot 2014-12-31 at 2 36 31 am](https://cloud.githubusercontent.com/assets/157374/5586511/f3cdd750-9095-11e4-94ac-fa951042c23c.png)

Not fullscreen mode

![screen shot 2014-12-31 at 2 36 09 am](https://cloud.githubusercontent.com/assets/157374/5586512/f93e3c66-9095-11e4-9c2d-2b8bf2b9e143.png)

**Comment by thomaspark** [comment]
Can you provide a link of this in action? I can't imagine what could be causing this except for custom styles.

**Comment by jancel** [comment]
I can. I've actually added some CSS to mask it, but if you go here (http://picturethis.io/#/slides/jtv), click the cog in the lower right and toggle fullscreen OR double click the photo slide show, the very bottom footer (that has my location) is actually not using the cyborg template, but a default bootstrap with some over-riding classes to make it look like it's from Cyborg.

**Comment by thomaspark** [comment]
The culprit is the margin-bottom on body. Setting the background color of html (which you've already done), or using padding-bottom instead should fix it.

I could set html's background color within the theme, but want to avoid it as it's not the behavior in vanilla Bootstrap.
