### ISSUE TITLE
New theme suggestion

### ISSUE THREAD

**Issue by jenil27** [thomaspark/bootswatch#382]
Hey @thomaspark 

Do you want me to make some theme using this style/color?
 
![image](https://cloud.githubusercontent.com/assets/971411/5719269/f2393090-9b3c-11e4-8310-30b1dea5acc9.png)

**Comment by thomaspark** [comment]
Rather than creating a new theme, perhaps you can add some of the nice touches to [Sandstone](http://bootswatch.com/sandstone/)? Ignoring the background color, it shares many similarities with it.

**Comment by nicolasmccurdy** [comment]
@thomaspark Agreed.

**Comment by jenil27** [comment]
That works.

Thomas, can you share a few stats of theme usage/downloads so that we can enhance the themes that are not doing well? What do you think?

**Comment by thomaspark** [comment]
Sure, here's the rundown for second half of 2014. Though keep in mind that some themes are niche by their very nature, and there's nothing wrong with that.

Theme | Views | Downloads
-----------|---------|------
Cerulean | 11% | 15%
Flatly | 10% | 11%
Cosmo | 9% | 8%
Yeti | 7% | 6%
Paper | 7% | 5%
Superhero | 6% | 10%
Darkly | 6% | 5%
Cyborg | 6% | 5%
Simplex | 6% | 5%
Slate | 5% | 7%
Sandstone | 5% | 5%
Lumen | 5% | 4%
Spacelab | 5% | 5%
United | 5% | 6%
Journal | 4% | 2%
Readable | 4% | 3%

**Comment by jenil27** [comment]
Thanks!
