### ISSUE TITLE
Single select html element in Firefox with the Paper theme looks odd

### ISSUE THREAD

**Issue by PranayShah** [thomaspark/bootswatch#387]
Does not look really good and does not look intentionally so either. So is most probably a bug.

**Comment by hebbet** [comment]
Could you provide a screenshot?

**Comment by thomaspark** [comment]
Nothing jumps out at me, can you provide more details? Here's a screenshot.

![screen shot 2015-01-22 at 4 16 49 pm](https://cloud.githubusercontent.com/assets/900407/5864739/3fb6d9b4-a252-11e4-84ff-29a31a9411b2.png)

**Comment by nicolasmccurdy** [comment]
I'm noticing that the dotted border around the original field and the gray border around the highlighted option seem kind of off, but are they like that when there are multiple options?

**Comment by thomaspark** [comment]
Looks the same with multiple options, and not much different from other themes.

**Comment by PranayShah** [comment]
Okay the screenshot attached by Thomas is how it looks in my case as well.
To me the caret and the enclosing container which seems slightly raised and
the color of it little odd were the reason I posted this. In Chrome for
instance with the Paper theme there is no caret and looks much more
sophisticated to me. Just my opinion.

**Comment by thomaspark** [comment]
Thanks for the follow-up. select elements don't have much flexibility in how they can be styled, but we did make some strides with #358. It should be more consistent across browsers now. Here's how it looks in Firefox — notice the caret on the right:

![screen shot 2015-01-22 at 11 01 54 pm](https://cloud.githubusercontent.com/assets/900407/5869676/c89e01fc-a28a-11e4-9381-080c7a4c000b.png)

**Comment by PranayShah** [comment]
Thanks. Looks much better now in my opinion.
