### ISSUE TITLE
Padding issue with .navbar-brand

### ISSUE THREAD

**Issue by rdahbura** [thomaspark/bootswatch#388]
The bootswatch.less file includes a modification to the padding on the .navbar-brand class that causes the vertical padding to be asymmetrical when changing the base font size. It becomes especially noticeable when reducing the font size. The lines are:

&-brand {
  padding: 18.5px 15px 20.5px;
}

The bootstrap theme includes a calculation based on line height and font size that keeps the brand centered vertically. I'm not sure why it's being overridden but it would be nice to remove that, assuming the above explanation makes sense.

Thanks.

**Comment by hebbet** [comment]
Maybe you make a pull request :) 
Not sure what themes you mean

**Comment by thomaspark** [comment]
This is mainly an issue with Flatly and Darkly. Getting rid of hard-coded values.

**Comment by rdahbura** [comment]
Great! Thank you!
