### ISSUE TITLE
_bootswatch.scss seems to break node sass sourcemap

### ISSUE THREAD

**Issue by marani** [thomaspark/bootswatch#389]
I tried to use scss files by importing them & `bootstrap-sass-official` from my index.scss, the below works but it is unable to produce sourcemaps (browser doesn't seem to detect, or maybe generated sourcemaps is broken). I use `gulp-sass`, which is a gulp adapter for node-sass.

**With `_bootswatch.scss`**
```
// this is my index.scss
@import "../../bower_components/bootswatch/lumen/_variables.scss";
$icon-font-path: "../../bower_components/bootstrap-sass-official/assets/fonts/bootstrap/";
@import "../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap";
@import "../../bower_components/bootswatch/lumen/_bootswatch.scss";
```
--> chrome inspect

![image](https://cloud.githubusercontent.com/assets/2355027/5794163/48c8634a-9f9d-11e4-9367-aa38980e064e.png)

**Without `_bootswatch.scss`, problem is gone**
If I remove `_bootswatch.scss` from my index.scss, the sourcemaps is able to work.
```
// this is my index.scss
@import "../../bower_components/bootswatch/lumen/_variables.scss";
$icon-font-path: "../../bower_components/bootstrap-sass-official/assets/fonts/bootstrap/";
@import "../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap";
//@import "../../bower_components/bootswatch/lumen/_bootswatch.scss";
```
--> chrome inspect
![image](https://cloud.githubusercontent.com/assets/2355027/5794181/ed5c980e-9f9d-11e4-8582-14ef06637eef.png)

Extra info:
- bootswatch version 3.3.1+2
- bootstrap-sass-official version 3.3.1
- Problem is the same for any theme.
- If I remove `_variables.scss`, problem still occurs (no scss map appears in chrome inspector), if I remove both lumen variables & bootswatch, there's no problem.

**Comment by thomaspark** [comment]
Tested it out and it's working as expected for me:

![screen shot 2015-01-22 at 9 11 03 pm](https://cloud.githubusercontent.com/assets/900407/5868706/573b72ba-a27b-11e4-9f01-b92974aa1c03.png)

Here's the gulpfile I used:
```
var gulp = require('gulp');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('sass', function() {
  gulp.src('./index.scss')
    .pipe(sourcemaps.init())
    .pipe(sass())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('./css'));
});
```

**Comment by marani** [comment]
Thanks for the response!
It turns out there were problems with my overly complicated gulp settings, sometimes it works, sometimes it doesn't & it's not only bootswatch causing the problem...
So I'm closing it for now.
