### ISSUE TITLE
Upgrade themes to latest Bootstrap V 3.3.2

### ISSUE THREAD

**Issue by mewsoft** [thomaspark/bootswatch#390]
Greetings,
The new Bootstrap version 3.3.2 has some fixes and updated the Glyphicon fonts to 1.9, some new icons has been added and missing from all themes here.
Thanks

**Comment by thomaspark** [comment]
Done! 7e6070630176d8a802c4837345d5998eac7c1d7a

**Comment by mewsoft** [comment]
I just want to say, thank you for your excellent work.
