### ISSUE TITLE
Paper: add material design style checkboxes and radio buttons

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/bootswatch#393]
Add material design-style checkboxes and radio buttons as specified here: http://www.google.com/design/spec/components/switches.html#switches-checkbox

![components_switches_check3](https://cloud.githubusercontent.com/assets/900407/5911821/da6a6fea-a598-11e4-81de-fa7bc04fe28a.png)

![components_switches_radio3](https://cloud.githubusercontent.com/assets/900407/5911830/f1a66f74-a598-11e4-8595-c8f435df69a7.png)

Addresses parts of #304.

**Comment by nahtnam** [comment]
Add floating labels:
![](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7SGthNmdNaFZhT00/components_textfields_labels3.png)

**Comment by thomaspark** [comment]
@nahtnam, can you add that as a separate issue? I have a feeling that will require its own discussion.

**Comment by nahtnam** [comment]
#394

**Comment by ryanwalters** [comment]
#395 
Created material checkbox and radio buttons. Working in Chrome.

**Comment by transbetty** [comment]
It looks like material design checkboxes / radios are supported only in Webkit browsers. The rest shows browser default style, example: IE 11
![image](https://cloud.githubusercontent.com/assets/6896794/9569409/f51b579c-4f6a-11e5-8b73-440630c2c146.png)

Is it because the CSS used is supported only in Webkit, or browser-specific prefixes are missing?

**Comment by thomaspark** [comment]
The material design style ones are created using ::before and ::after pseudoelements on the checkbox and radio inputs, which are only supported in Webkit.

More info here: http://stackoverflow.com/questions/12831620/is-the-before-pseudo-element-allowed-on-an-inputtype-checkbox#answers-header

**Comment by transbetty** [comment]
Thanks for the explanation.
