### ISSUE TITLE
Paper: Add floating labels to text fields.

### ISSUE THREAD

**Issue by nahtnam** [thomaspark/bootswatch#394]
Add floating labels:
http://www.google.com/design/spec/components/text-fields.html#text-fields-floating-labels
![Floating labels](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7SGthNmdNaFZhT00/components_textfields_labels3.png)

**Comment by ryanwalters** [comment]
@thomaspark I'm guessing additional Javascript is out of the question on this one? Even if it's only 3 lines...

http://jsfiddle.net/RyanWalters/z9ymd852/

**Comment by thomaspark** [comment]
Afraid so, as is any custom markup.

It's looking like this isn't possible right now, but your solution is really nice. If you're cool with it, I'd like to include it in a Bootswatch blog post about Paper. I'm sure many people would be interested.

**Comment by ryanwalters** [comment]
Figured as much, kind of a bummer. Feel free to include it in your blog post (attribution would be a nice bonus ;).

**Comment by nahtnam** [comment]
Maybe these links will help?

http://snook.ca/archives/html_and_css/floated-label-pattern-css

http://codepen.io/boast/pen/pLjld

**Comment by ryanwalters** [comment]
The pen doesn't seem to work for me in Chrome. But the big downside to that method that I see is that the markup changes from what Bootstrap recommends.

**Comment by thomaspark** [comment]
@ryanwalters, would definitely will credit you for this and the checkboxes/radio buttons.

@nahtnam, I considered that approach, but it requires changing the markup pattern (input before label) to use a sibling selector `input:focus ~ label`.

**Comment by nahtnam** [comment]
@ryanwalters Did you type something in the form? Its working for me.

**Comment by nahtnam** [comment]
@thomaspark So its not possible to implement?

**Comment by thomaspark** [comment]
Not currently in pure css. A parent or pre-sibling selector would change that. Closing for now.
