### ISSUE TITLE
Remove indet when hovering over a button

### ISSUE THREAD

**Issue by nahtnam** [thomaspark/bootswatch#396]
Hey!

When you put your mouse over a button, a weird indent come off the sides.

This isnt part of the material design, and looks awkward.

**Comment by thomaspark** [comment]
Can you post a screenshot? Not sure what you mean by weird indent.

If you're referring to the inset shadow, that's similar to the effect under "buttons in motion" here:
http://www.google.com/design/spec/components/buttons.html

**Comment by nahtnam** [comment]
When you hover over a button, two semi circles come out of the side. Kind
of like this: ![](http://i.imgur.com/SL0St8n.png)

If you look at every other material design framework out there, they do not
have this.

**Comment by thomaspark** [comment]
Well, there's at least one now. :wink: And check the link I posted.

**Comment by nahtnam** [comment]
IMO, they are ugly and take away from the design. I dont know why good added it...
