### ISSUE TITLE
Couple panel issues - Superhero and Readable themes (v3.3.2)

### ISSUE THREAD

**Issue by xcartmods** [thomaspark/bootswatch#397]
Just thought I'd post a couple things I found while messing around...

(v3.3.2)

(1) No panel borders if using ul.list-group or table within panel using "Readable" theme.

(panel-default is fine, all others don't have a border)

(2) Panel HR tags not visible (indistiguishable from background colour) using "Superhero" theme.

I've put up a demo with theme switcher (see ISSUES panel) - http://www.xcms.co.uk/bootstrap

All other themes seem fine.

Thank you for Bootswatch !

**Comment by thomaspark** [comment]
Thanks for the great test page. Fixes on the way.

**Comment by xcartmods** [comment]
no worries, thanks for all you do :)
