### ISSUE TITLE
Browse button in file input field is misplaced

### ISSUE THREAD

**Issue by Gitward** [thomaspark/bootswatch#398]
When changing input fields to `type="file"`, the browse-button is misplaced (shown for [darkly](http://bootswatch.com/darkly/)):
![layout_darkly](https://cloud.githubusercontent.com/assets/8510849/5956582/97ae4352-a7af-11e4-9184-3f5f73362ab1.png)

Solution might be:
http://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3/

Browser: Firefox 35.0.1

**Comment by thomaspark** [comment]
Can you link to a demo of this, and what browser you're seeing it in?

Here's what I'm seeing:
![screen shot 2015-01-29 at 11 35 14 am](https://cloud.githubusercontent.com/assets/900407/5961484/eceee1e6-a7aa-11e4-82ba-fe8f0447a148.png)

**Comment by Gitward** [comment]
The Browser is Mozilla Firefox 35.0.1 (Ubuntu Linux 14.10)

I haven't uploaded a website yet, but an easy way to reproduce is as follows:
- Go to http://bootswatch.com/darkly/
- Inspect an input field with firebug or another `inspector`:
![step1](https://cloud.githubusercontent.com/assets/8510849/5973007/29ba228a-a863-11e4-8efa-9a2b7009e86e.png)
- Change the type of the input-field to `file`: 
![step2](https://cloud.githubusercontent.com/assets/8510849/5973026/728c20a8-a863-11e4-863a-0a5be32b1fe9.png)

**Comment by thomaspark** [comment]
Thanks for the screenshots. Do you have the same problem with default Bootstrap? Might be something that should be fixed upstream.

**Comment by ZaLiTHkA** [comment]
This does happen with the default Bootstrap as well, but it's specific to Firefox (or perhaps the Gecko rendering engine specifically). Neither the original pages or the theme files have this issue on Chrome 40.

**Comment by thomaspark** [comment]
Thanks for the link, @ZaLiTHkA. Recommend opening an issue for this with Bootstrap.
