### ISSUE TITLE
Button group margins in Paper theme

### ISSUE THREAD

**Issue by oliversalzburg** [thomaspark/bootswatch#400]
IMHO, the default -1px margin in button groups does not work well with Paper. We use 0 in our version:

````
.btn-group {
	.btn + .btn,
	.btn + .btn-group,
	.btn-group + .btn,
	.btn-group + .btn-group {
		margin-left: 0;
	}
}
````

You can see that the buttons overlap:

![](http://i.imgur.com/TxSMlij.png)

This is especially bad on hover, because the button being hovered over has the z-index increased:

![](http://i.imgur.com/xiGa351.png)

This results in a 1px wide line flipping between the color of one button or the other.

**Comment by thomaspark** [comment]
Agreed, pushing a fix for this and margin-top for btn-group-vertical. Thanks.

**Comment by oliversalzburg** [comment]
Awesome. Thanks :)
