### ISSUE TITLE
Themes don't pass bootlint 3.3.2

### ISSUE THREAD

**Issue by kitsguru** [thomaspark/bootswatch#402]
Your theme examples don't pass the bootlint test on version 3.3.2.

Makes it tough to use the copy and paste aspects - which is extremely helpful so it would be great to fix it.
On the alerts, dismissible is spelled incorrectly as dismissable
There is a cancel button on the forms that does not have a type="reset"
There is also an issue with the navbar, and use of col-*

**Comment by thomaspark** [comment]
Thanks, fixing the markup to pass bootlint and updating the navbar code.
