### ISSUE TITLE
Text Input visible through modal

### ISSUE THREAD

**Issue by Braza** [thomaspark/bootswatch#403]
<input type="text" class="form-control" placeholder="Search for..." id="search_input">

![image](https://cloud.githubusercontent.com/assets/5665515/6189868/0d71ef98-b3af-11e4-80f6-2a1e8402dbfa.png)

**Comment by Braza** [comment]
BTW, modals no longer grey out the background...

**Comment by thomaspark** [comment]
Check that you're on the latest version of both bootstrap.css and bootstrap.js.

**Comment by Braza** [comment]
Hi Thomas,

Bootstrap.css is "Bootswatch v3.3.2"
Bootstrap.js is "Bootstrap v3.3.2"

**Comment by Braza** [comment]
It seems to have random z order issues with modal windows in general, not the search input..
![image](https://cloud.githubusercontent.com/assets/5665515/6199563/bf30fc80-b45c-11e4-9c49-86b1ffa15ca5.png)

**Comment by thomaspark** [comment]
Can you provide a link to a live demo?

**Comment by Braza** [comment]
No, but I'll try to figure something out on Monday.

**Comment by Braza** [comment]
![search-z-index](https://cloud.githubusercontent.com/assets/5665515/6212502/1b3bab24-b5f7-11e4-995f-ac7962e32ebb.jpg)
![modal-z-index](https://cloud.githubusercontent.com/assets/5665515/6212504/1ceab5fa-b5f7-11e4-99b3-f726048b1f83.png)

I cant publish it to the internet, but I made couple of screenshots with z-index of modal and search elements. It seems to me that it might be something with the animation divs indices?

**Comment by Braza** [comment]
ok it was my backbone code generated modal indices. thanks for supporting this stuff

**Comment by thomaspark** [comment]
Glad you were able to pin down the issue.
