### ISSUE TITLE
A couple lumen issues

### ISSUE THREAD

**Issue by jbohren** [thomaspark/bootswatch#404]
On FireFox and Chrome (latest stable) on Linux

- [ ] `.btn-group-vertical` --  Buttons shift in vertical position on rollover.
- [ ] `.nav-tabs .nav-justified` -- Tabs expand both from the top and bottom instead of just expanding upward.

Both of these issues can be seen on the [demo page](http://bootswatch.com/lumen/). The  `.nav-tabs .nav-justified` can be seen by bringing up the browser's dev tools and adding the`nav-justified` class to the example tabs.

**Comment by thomaspark** [comment]
Thanks, fixes are on the way.

**Comment by jbohren** [comment]
Awesome, thanks!

Love the theme, btw: http://rosindex.github.io
