### ISSUE TITLE
Paper: input addon after input causes input field to shift left

### ISSUE THREAD

**Issue by lowerends** [thomaspark/bootswatch#414]
When using the ```input-group-addon``` in a ```.horizontal``` form without an addon *before* the input, the input field get's shifted to the left and is no longer left-aligned with other, normal input form-groups. The HTML below can be used to reproduce the problem.

````
<div class="form-group ">
    <label for="field" class="col-sm-4 control-label">Field</label>
    <div class="input-group col-sm-8">
        <input class="form-control" name="field" type="text" value="text" id="field">
        <span class="input-group-addon">addon</span>
    </div>
</div>
````
Using input-addons on both sides of the input is working correctly though.

**Comment by thomaspark** [comment]
This also affects vanilla Bootstrap. Separating the `input-group` and `col-sm-8` should fix it:

```
<div class="form-group ">
    <label for="field" class="col-sm-4 control-label">Field</label>
    <div class="col-sm-8">
        <div class="input-group">
            <input class="form-control" name="field" type="text" value="text" id="field">
            <span class="input-group-addon">addon</span>
        </div>
    </div>
</div>
```

**Comment by lowerends** [comment]
I can indeed confirm that separating the ```input-group``` and ```col-sm-8``` fix it. Thanks!
