### ISSUE TITLE
Customizing

### ISSUE THREAD

**Issue by ircer** [thomaspark/bootswatch#421]
Hi, 

I want to use the great Paper theme, but I want to change the primary colour to #2aa648.

What is the simplest method to do it? (Ofcourse I can't do a find and replace in Notepad, because some are gradients and whatnot).

Basically primary and navbar-inverse etc. should all be green instead of blue.

**Comment by nicolasmccurdy** [comment]
You should open `variables.less` (or `_variables.scss`), modify the colors for the you want to change, and recompile the CSS for that theme.

**Comment by thomaspark** [comment]
Here are the steps for how to do that: https://bootswatch.com/help/

**Comment by ircer** [comment]
@nicolasmccurdy @thomaspark is there a way to do this online? I don't have anything on that page installed, I'm on Windows ...

**Comment by thomaspark** [comment]
There are web-based Bootstrap customizers you could use for this:
http://bootstrap-live-customizer.com/
http://bootswatchr.com/
