### ISSUE TITLE
Paper: something not right

### ISSUE THREAD

**Issue by clod986** [thomaspark/bootswatch#424]
Sorry if I cannot make a pull request, but are you sure about this piece of code?

<pre>
.progress-bar:last-child:before {
  display: block;
  content: 'div::before';
  position: absolute;
  width: 100%;
  height: 100%;
  left: 0;
  right: 0;
  z-index: -1;
  background-color: #cae6fc;
}
</pre>
it my firefox it writes DIV::BEFORE inside the brogressbar. It can be seen only if you increase the progress-bar height, which of course I did :)

**Comment by thomaspark** [comment]
Thought we had corrected this. Fix inbound!
