### ISSUE TITLE
Glyphicons in 3.3.4

### ISSUE THREAD

**Issue by genichyar** [thomaspark/bootswatch#427]
When I use https://maxcdn.bootstrapcdn.com/bootswatch/3.3.4/cerulean/bootstrap.min.css and try to insert glyphicon-circle-arrow-up it shown a square instead the icon.
This bug repeats with some other glyphicons and bootswatch's themes.
There is no such bug in 3.3.2.

**Comment by jenil27** [comment]
This is a issue with MaxCDN, check https://github.com/MaxCDN/bootstrap-cdn/issues/527

**Comment by thomaspark** [comment]
Thanks @jenil27.

**Comment by jmervine** [comment]
@thomaspark I was wondering if perhaps you can help me debug this. I simply copy the files from bootswatch.com and ensure the mime types are correct. The process I've followed is the same I've followed with past releases.

**Comment by jmervine** [comment]
Okay, it would appear that there's a `bootswatch v3.3.4+1` update that I was unaware of.
