### ISSUE TITLE
Flatly's LESS is broken on npm

### ISSUE THREAD

**Issue by tkazec** [thomaspark/bootswatch#428]
See https://github.com/thomaspark/bootswatch/commit/0b99e59d9ba103694240d1a1e0f9ffdfaaaea709#commitcomment-10342908

This is a ParseError in LESS 2.4.0.

**Comment by thomaspark** [comment]
This has been fixed and the version number bumped to `3.3.4+1`.

Unfortunately, there's not much to be done for npm, which doesn't allow versions to be republished and ignores the build number after +. Sorry about that.

Recommend bower if possible, which does recognize `3.3.4+1` as a new release.
