### ISSUE TITLE
Modals have wrong z-index

### ISSUE THREAD

**Issue by kamil7x** [thomaspark/bootswatch#429]
Today I found, that `modal-dialog` class have no z-index set in all theme, and `modal-backdrop` is in front of dialog.

This is only on my site, and not on Bootswatch (Source Code modal). I don't know why, i didn't change z-index for that class. Firefox's Developer Tools shows that it's not set.

On original Bootstrap's CSS it's ok.

**Comment by thomaspark** [comment]
Make sure your bootstrap.css and bootstrap.js are the same version. There have been many changes to how modals are handled in the last few updates.

**Comment by drmonty** [comment]
current npm deploys 3.3.2-css files.

**Comment by thomaspark** [comment]
Ah, good call, although that's only if you're using Flatly. Try updating to latest build `v3.3.4+1`.
