### ISSUE TITLE
Paper: Panel heading without .panel-title

### ISSUE THREAD

**Issue by juniwalk** [thomaspark/bootswatch#432]
When you don't use `.panel-title` in the `.panel-heading`, the color of the text is the same as the color of the background and therefore the text is not readable.

This applies to:
- `.panel.panel-success`
- `.panel.panel-warning`
- `.panel.panel-danger`
- `.panel.panel-info`

*Use of `panel-title` is not mandatory. [Link](http://getbootstrap.com/components/#panels-heading)*

**Comment by thomaspark** [comment]
The way I read it, using plain text (or in a div or span) within a `panel-heading` does not require `.panel-title`. But using `h1`-`h6` or `a` does if you want them styled properly.

Relevant snippet:

> Easily add a heading container to your panel with .panel-heading. You may also include any &lt;h1>-&lt;h6> with a .panel-title class to add a pre-styled heading.

**Comment by juniwalk** [comment]
Well my problem is when you use plain text without `.panel-title` node the text is not readable.

**Comment by thomaspark** [comment]
It's working for me. Only difference is you get the base font size:

![panel](https://cloud.githubusercontent.com/assets/900407/6870931/971ff316-d475-11e4-9e98-5b339bbe6281.png)

My code:

```
<div class="panel panel-primary">
  <div class="panel-heading">
    Panel primary
  </div>
  <div class="panel-body">
    Panel content
  </div>
</div>
```

**Comment by juniwalk** [comment]
Well you've used `.panel-primary` which I've listed as working properly. Switch to `.panel-warning` and you should see what I mean.

```html
<div class="panel panel-warning">
    <div class="panel-heading">Panel warning</div>
    <div class="panel-body">Panel content</div>
</div>
```

**Comment by thomaspark** [comment]
Ah, my mistake. I'll reopen and get this fixed. Thanks.

**Comment by juniwalk** [comment]
I thank you.
