### ISSUE TITLE
[Paper] Panel headings should be white

### ISSUE THREAD

**Issue by cmfcmf** [thomaspark/bootswatch#433]
The font color of the panel headings is incorrectly set to the panel color, if the panel's title isn't wrapped into `h4.panel-title`.

You can see the issue here: http://jsbin.com/julavelone/1/edit?html,output.

**Comment by thomaspark** [comment]
Just fixed in #432. Check out http://jsbin.com/kicogijahe/1/edit?html,output.

**Comment by cmfcmf** [comment]
Oh thanks. Sorry for not looking through the other issues :smirk:
