### ISSUE TITLE
[Paper] Problem with navbar-fixed-top

### ISSUE THREAD

**Issue by KeSch** [thomaspark/bootswatch#434]
First of all, thank you very much for your great bootswatch themes.

Unfortunately, I have a litte problem with the navbar. It should be fixed and stays at the top, but if I set the class to `navbar-fixed-top` the next element (in my case a jumbotron) sticks to the navigation and that's not what I've expected.

The screenshot below should explain it clearly:
![navbar-fixed-top](https://cloud.githubusercontent.com/assets/1071887/6991091/63bac7aa-da81-11e4-8872-488ed82ebee6.PNG)

However, if I set the nav class to `navbar-fixed` the jumbotron and its margins looks great. But the navigation doesn't stays at the top when scrolling and that's not what i want.

Another screenshot to clarify it:
![navbar-fixed](https://cloud.githubusercontent.com/assets/1071887/6991120/96e8aa60-da82-11e4-986b-0ec4f533b173.PNG)

You can also take a look at my site: http://educatorly.net/eduquiz/

Cheers,
KeSch

**Comment by jenil27** [comment]
Hi @KeSch,

This is how Bootstrap works, when you make the navbar fixed, it attaches itself to the top. We then need to add a padding top to the body greater than the height of the navbar (i.e 70px)

Check this for reference http://getbootstrap.com/examples/navbar-fixed-top/

Hence this is not an issue. Hope this helps.

Cheer!

**Comment by KeSch** [comment]
Hey @jenil27,

thank you, this explains a lot. ;)

Cheers,
KeSch
