### ISSUE TITLE
Missing bootswatch in bower index

### ISSUE THREAD

**Issue by vasiliy0s** [thomaspark/bootswatch#435]
Please publish repo info global bower index

**Comment by vasiliy0s** [comment]
...and add `main` entries (css, sass, less) to `bower.json`

**Comment by thomaspark** [comment]
Problem is, no specific css/sass/less is really the `main`. See #263 and #324 for previous discussions.

I'm not sure what you mean by global bower index. This? http://bower.io/search/?q=bootswatch

**Comment by vasiliy0s** [comment]
Sorry, it's my mistake of searching. For 'main' entry you are right. Thanks.
