### ISSUE TITLE
Input height is incorrect

### ISSUE THREAD

**Issue by heaven** [thomaspark/bootswatch#438]
All three variables: `$input-height-base`, `$input-height-large`, and `$input-height-small` calculated incorrectly because of the different border width.

The next code was simply copied from bootstrap's variables definition:
```sass
//** Default `.form-control` height
$input-height-base:              ($line-height-computed + ($padding-base-vertical * 2) + 2) !default;
//** Large `.form-control` height
$input-height-large:             (ceil($font-size-large * $line-height-large) + ($padding-large-vertical * 2) + 2) !default;
//** Small `.form-control` height
$input-height-small:             (floor($font-size-small * $line-height-small) + ($padding-small-vertical * 2) + 2) !default;
```

You can see `+ 2` at the end, I assume this is the double border width (up and bottom). In bootstrap it is 1px, so here we have 2. I was trying the flatly style and the border width here is 2px, so we should do `+ 4` instead.

As result the input's inner height is calculated incorrectly, you can see it is 16px, when should be 18px:
![input](https://cloud.githubusercontent.com/assets/126732/7131334/121c3652-e2a8-11e4-9164-53d84a5d468b.jpg)

If you remove the css height attributes from `.input-sm` and `.form-control` you'll see something like this:
![input2](https://cloud.githubusercontent.com/assets/126732/7131416/44310644-e2a9-11e4-9e96-561a92239f2e.jpg)

This does work on text inputs because of the `box-sizing: border-box`, but if you use third party libraries like chosen, which do copy basic input styles but replace the height attribute with min-height (because those can expand when you select more choices), those controls become 2px taller than the default text inputs.

**Comment by heaven** [comment]
I was able to fix by adding this to my bootstrap.scss:
```sass
// Import flatly variables
@import "bootswatch/flatly/variables";

//** Fix incorrect input height – https://github.com/thomaspark/bootswatch/issues/438
$input-height-base: $input-height-base + 2;
$input-height-large: $input-height-large + 2;
$input-height-small: $input-height-small + 2;

// ...

/* Buttons
----------------------------------------------------------------------------- */
//** Fix incorrect input height – https://github.com/thomaspark/bootswatch/issues/438
.btn {
  border-width: 2px;
}
```

**Comment by thomaspark** [comment]
@heaven, let me know if this fixes what you're describing.

**Comment by heaven** [comment]
@thomaspark I believe it does, thank you.
