### ISSUE TITLE
text-info inside alert-info is invisible (background is same as text color)

### ISSUE THREAD

**Issue by fleaflicker** [thomaspark/bootswatch#440]
In this screenshot, I wrapped the word "important" in a `<span class="text-info">`
![untitled](https://cloud.githubusercontent.com/assets/682081/7208757/fe534e1a-e510-11e4-86eb-3a182eb577a8.png)

**Comment by fleaflicker** [comment]
This actually affects any text-* inside the same alert-* level.

**Comment by fleaflicker** [comment]
See also #242 , fixing may be outside the scope of this project

**Comment by thomaspark** [comment]
Yeah, setting `.text-info` to blue is the expected behavior, and I'd say contextually inferring anything past that is beyond scope.
