### ISSUE TITLE
[Paper] Extra 2px on navbar dropdown-menu's

### ISSUE THREAD

**Issue by Panman8201** [thomaspark/bootswatch#445]
This seems like a bug to me but perhaps not. When opening a dropdown in the navbar, there is space between the bottom of the `navbar` and the actual `dropdown-menu`. There is specific styling for this, so it's either intended or an error. Perhaps it's needed when the navbar is collapsed (small screens).?. The offending line is:

https://github.com/thomaspark/bootswatch/blob/979847f28d689bb93e5ff8cc9beb20a2a89c4f6b/paper/bootswatch.less#L33 

https://github.com/thomaspark/bootswatch/blob/979847f28d689bb93e5ff8cc9beb20a2a89c4f6b/paper/_bootswatch.scss#L33

**Comment by thomaspark** [comment]
Thanks, I'll be removing this margin.
