### ISSUE TITLE
Ensure the links look good on navbar background

### ISSUE THREAD

**Issue by dandv** [thomaspark/bootswatch#447]
I've run into this [issue while using several Bootswatch themes with a navbar login library for Meteor.js](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/issues/110): links displayed over the navbar's background in narrow width layouts are impossible to read because their color is the same as the background.

The issues occur with the cerulean and united themes. A reproduction repo is at https://github.com/dandv/accounts-ui-bootstrap-3-with-themes

![image](https://cloud.githubusercontent.com/assets/33569/7340583/91caa1c6-ec45-11e4-9c3a-2cbb8e2f8e7d.png)

**Comment by thomaspark** [comment]
@dandv, thanks for creating that repo — super helpful. Let me know if you spot any other issues.
