### ISSUE TITLE
.dropdown-menu carat never goes the same height at the .btn next to it.

### ISSUE THREAD

**Issue by lexbi** [thomaspark/bootswatch#449]
Hi Thomas,

First off cheers for doing these themes, they are an amazing contribution to the community.

My problem:

For some reason the "carat" within a `.dropdown-menu` doesn't ever seem to become the same height as the rest of the `.btn` next to it looks very strange.

I have disabled all my custom css on the page so its just your bootstrap.min.css and the bootstrap.js/bootswatch.js but just looks really odd.

I've copied/pasted the code from your example template. exactly the same:

    <div class="btn-group">
        <a href="#" class="btn btn-primary">Download</a>
        <a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="#">MP3 (320kbps)</a></li>
            <li><a href="#">WAV (Uncompressed, 16Bit, 44.1kHz)</a></li>
        </ul>
    </div>

Looks like this:
![screenshot 2015-05-03 07 59 10](https://cloud.githubusercontent.com/assets/2337910/7444051/cbc28012-f16b-11e4-8744-bac2597374e6.png)

Seen this before? Sorry if its a dupe, couldn't find anything.

**Comment by thomaspark** [comment]
Haven't seen this before. Here's what I get:

![screen shot 2015-05-04 at 12 52 20 am](https://cloud.githubusercontent.com/assets/900407/7448979/d78730c8-f1f7-11e4-8f2d-0d10cc242cae.png)

http://jsbin.com/qebavufelu/1/edit?html,output

**Comment by lexbi** [comment]
Found my problem. 

Stupidly I forgot to add in a doctype.

I am a dumb.
