### ISSUE TITLE
$icon-font-path variable causes error with bootstrap-sass/Ruby on Rails

### ISSUE THREAD

**Issue by noinkling** [thomaspark/bootswatch#453]
I haven't checked the other themes, but in `paper/_variables.scss` is this line:

```
$icon-font-path:          "../fonts/";
```

This causes an error in Rails/Sprockets when used with `bootstrap-sass`. If you check [their default variable file](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L83) the line looks like this:

```
// [converter] If $bootstrap-sass-asset-helper if used, provide path relative to the assets load path.
// [converter] This is because some asset helpers, such as Sprockets, do not work with file-relative paths.
$icon-font-path: if($bootstrap-sass-asset-helper, "bootstrap/", "../fonts/bootstrap/") !default;
```
As noted, this is part of a workaround to help with differing path helper functions between build systems.

Simply removing/commenting out the line in the theme fixes it. I don't think it makes sense for the theme to override this variable, but I guess it's probably just a result of converting from LESS.

There are also a lot of other variables that are the same as the Bootstrap defaults. While I guess it doesn't hurt to have them (as long as versions match!), they do seem kinda redundant.

**Comment by cvrebert** [comment]
@noinkling Does your error look like https://github.com/twbs/bootstrap-sass/issues/930#issuecomment-117561219 ?

**Comment by noinkling** [comment]
I believe it looked something like that, yes.

**Comment by cvrebert** [comment]
@thomaspark Ping?

**Comment by thomaspark** [comment]
Thanks for the reports, fix on the way.
