### ISSUE TITLE
Version 3.3.4+1 breaks modal display

### ISSUE THREAD

**Issue by irax-xx** [thomaspark/bootswatch#454]
Not sure how, but the compiled bootstrap.css file in the new version differs from v3.3.2 in the definition of .modal-backdrop:

```
 .modal-backdrop {
-  position: absolute;
+  position: fixed;
   top: 0;
   right: 0;
+  bottom: 0;
   left: 0;
+  z-index: 1040;
   background-color: #000000;
 }
```

The offending line seems to be the `z-index: 1040`, which puts the modal behind the backdrop, effectively disabling it. 

Of course, might be something in my setup also, would appreciate pointers if that is the case.

**Comment by thomaspark** [comment]
Make sure to update `bootstrap.js` to match the version of the css. There have been changes in how modals are handled between recent versions. See also #429.
