### ISSUE TITLE
please include demo page in top level dist

### ISSUE THREAD

**Issue by jieryn** [thomaspark/bootswatch#458]
This will help developers using bower that want to refer their application users to the demo page for the exact version they have deployed. Thank you.

**Comment by thomaspark** [comment]
I think most devs would prefer to keep the bower package limited to the css/less files.

If you need a demo, I recommend building a simple one yourself or linking to bootswatch.com.

**Comment by jieryn** [comment]
Then why do we include the 25kb thumbnail.png?

**Comment by thomaspark** [comment]
There's a good argument to remove the thumbnails, but it's still there for now due to inertia / fear of breaking things that might rely on it.

**Comment by jieryn** [comment]
Ok, I will drop this PR and issue if I can rely on that thumbnail.png being there, I guess...
