### ISSUE TITLE
HTML5 Slider Bars

### ISSUE THREAD

**Issue by Wargog** [thomaspark/bootswatch#460]
As you may already know, HTML5 supports slider bars for selecting values in a range on a slider. Bootswatch as far as I can tell has no support for these on any of the themes.

**Comment by thomaspark** [comment]
Bootswatch themes are reskins of Bootstrap, so sliders would only be supported if Bootstrap adds support for them. Not sure if that's in store for v4...

**Comment by Wargog** [comment]
Oh, alright. The only reason I worry about it is because I can find almost nothing when searching for it on the internet.

**Comment by thomaspark** [comment]
Haven't used it myself, but this plugin seems quite customizable:

https://github.com/seiyria/bootstrap-slider

**Comment by coliff** [comment]
Bootstrap v4 supports range sliders now.
https://getbootstrap.com/docs/4.3/components/forms/#range

Would be cool for Bootswatch to add to the 'kitchen sink' demo pages for each theme.

**Comment by thomaspark** [comment]
@coliff, agreed!

**Comment by thomaspark** [comment]
Added in 778c0ef07c4f29780656b1ee7baa6cc7d6dd6c51.
