### ISSUE TITLE
Include the fonts from upstream as a git submodule

### ISSUE THREAD

**Issue by dandv** [thomaspark/bootswatch#465]
Hi Thomas,

I'm packaging Bootswatch for Meteor and noticed that [the fonts](https://github.com/thomaspark/bootswatch/tree/gh-pages/fonts) are *copied* from [upstream](https://github.com/twbs/bootstrap/tree/master/fonts). It would be easier IMO to keep these fules updates and track changes if the twbs repo was included as a git submodule.

For example, right now, the fonts appear to be version 3.3.2:

![image](https://cloud.githubusercontent.com/assets/33569/7791967/7a00b59c-025e-11e5-8c13-640c35f5133c.png)

**Comment by thomaspark** [comment]
Hey @dandv, the git submodule idea is similar to our current setup with the package under `bower_components/bootstrap/`.

The trouble is that whether using Bower or a git submodule, the entire project is placed in a subdirectory. What I need instead is for the font files to be located at `../fonts/` relative to the theme files.

Right now, I'm copying the files over manually, which makes it really easy for them to get out of sync, as you've noticed.

I'm wondering if there would be any issues if I instead created a symlink to the font files in the bootstrap package.

**Comment by thomaspark** [comment]
Symlinks added in 06885df3cfbb7d498f59dc5ac61a4cc1cc4f6dc2.
