### ISSUE TITLE
Should the CSS load the font?

### ISSUE THREAD

**Issue by dandv** [thomaspark/bootswatch#466]
The [CSS loads the Glyphicons font](https://github.com/thomaspark/bootswatch/blob/gh-pages/cerulean/bootstrap.css#L267) whether the user wants this or not. Is there an easy way to optionally not load Glyphicons?

Demand for this is shown by [this Meteor package](https://atmospherejs.com/twbs/bootstrap-noglyph) that loads Bootstrap without the Glyphicons.

**Comment by thomaspark** [comment]
Probably not as easy as you're hoping for. It would work the same as Bootstrap: remove the `@import "glyphicons.less";` line from `bootstrap.less` and then recompile.

I'd be ok with someone creating a noglyph version of Bootswatch, but would rather not support it myself in the main project.
