### ISSUE TITLE
Consider naming wrap numbers with _ instead of +

### ISSUE THREAD

**Issue by dandv** [thomaspark/bootswatch#467]
Seems like the more standard way. From [Meteor's docs](http://docs.meteor.com/#/full/writingpackages):

> Meteor supports the convention of using _ to denote a wrap number

**Comment by thomaspark** [comment]
I like that wrap numbers are explicitly recognized this way, but is `_` a Meteor-specific thing?

The `+` is part of the official semver spec as a build number (see [point 10 here](http://semver.org/)) and seen as a valid, distinct, and later version by package managers like Bower that use semver. I don't think that's the case with `_` (yet).
