### ISSUE TITLE
Animated bottom border of input elements on focus

### ISSUE THREAD

**Issue by dandv** [thomaspark/bootswatch#470]
Would this be within the scope of Bootstwatch?

Here's the [Polymer Paper demo](https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-textarea).

**Comment by thomaspark** [comment]
Yes, but only if it can be pulled off with just CSS. I'm thinking it's possible using pseudo-elements + transitions.

The other consideration is that Paper is not a direct port of Polymer / Material Design. Paper right now already has an animated bottom border for inputs, but it works slightly differently. Do people prefer the Polymer animation?

**Comment by dandv** [comment]
Here's a [solution using CSS only](http://jsfiddle.net/muicss/Lrw1me3e/), indeed with pseudo-elements.

**Comment by vizo** [comment]
@dandv it's not just css, it has also ˙<span class="bar"></span>`.
