### ISSUE TITLE
Invalid version field when doing "npm install"

### ISSUE THREAD

**Issue by jamesmbowler** [thomaspark/bootswatch#474]
This is the error I'm seeing:

npm ERR! Couldn't read dependencies.
npm ERR! Error: Invalid 'version' field: 3.3.4+1
npm ERR! 'version' Must be X.Y.Z, with an optional trailing tag.

Checking out a prior version, v3.3.4, works fine.

**Comment by thomaspark** [comment]
Is bootswatch being used as a dependency in a project? Version field should be set to 3.3.4 as build metadata (whatever trails `+`) is ignored by npm.

**Comment by jamesmbowler** [comment]
No .. I was just following the install instructions on the bootswatch site .. Ubuntu, 12.04.

**Comment by thomaspark** [comment]
Tested on Mac, cloning repo and running `npm install` doesn't give me any errors.

Could you try opening `package.json` and setting `version` to `3.3.4`? I wonder if that changes anything...

**Comment by jamesmbowler** [comment]
I did the same thing by checking out v3.3.4, and it did work with no issues.

**Comment by thomaspark** [comment]
Updated to 3.3.5 on npm. Should be good (for now).
