### ISSUE TITLE
Theme fiddles not working

### ISSUE THREAD

**Issue by cyberbit** [thomaspark/bootswatch#478]
The new JSFiddle links for themes go to the correct fiddles, but the resources are pulling from SSL which is having problems. It works with normal HTTP, though.
![image](https://cloud.githubusercontent.com/assets/7350183/8255081/12d70416-1663-11e5-908d-ba9c49605221.png)

**Comment by thomaspark** [comment]
Are you on XP by any chance? Do IE or Firefox work for you?

**Comment by cyberbit** [comment]
Funny, yes. o.O I don't have FF on my work (XP) machine, and IE8 won't open JSFiddle whatsoever. Tried it on my Win 8.1 machine, works flawlessly in all browsers. Is this a Chrome + XP issue you've seen before?

**Comment by thomaspark** [comment]
I believe this is an issue with XP using SSLv3. bootswatch.com uses CloudFlare, [which disables it](https://blog.cloudflare.com/sslv3-support-disabled-by-default-due-to-vulnerability/), as do most browsers.

You won't be able to get it working for IE on XP, but might have luck with Firefox. Some more info:
http://superuser.com/questions/826729/disable-sslv3-in-major-browsers
