### ISSUE TITLE
wrong color of checkbox- and radio-labels in form-group with validation in Cosmo and Lumen

### ISSUE THREAD

**Issue by marten-seemann** [thomaspark/bootswatch#479]
Adding the CSS class `has-success`, `has-warning` or `has-error` to a `form-group` containing inline checkbox- or radio-labels renders these labels invisible, since the color is set to white (`#fff`).

See the attached screenshot of the Lumen demo page, where I added `has-error` to some of the `form-group`s.
![screen shot 2015-06-19 at 17 30 44](https://cloud.githubusercontent.com/assets/1478487/8263555/e58d702a-16a9-11e5-9fe6-cba5b718ae60.png)
Here the text is "only" practically unreadable, however, in practice often a white background is used, so that the text becomes completely invisible.

The font color is also set to white in a couple of the dark themes (e.g. in Slate), which may be considered either a design choice or an inconsistency, since the `help-block`s are colored red. Anyway, this does not render the form unusable, since the text is still readable due to the dark background.

**Comment by thomaspark** [comment]
Thanks for the bug report!
