### ISSUE TITLE
Using the Cosmo theme, there is no mixin named box-shadow

### ISSUE THREAD

**Issue by Tareck117** [thomaspark/bootswatch#480]
When running the sass compilation on the Cosmo theme, I get the following error : 

```
Error in plugin 'gulp-sass'
Message:
   \style\theme\_bootswatch.scss
  194:12  no mixin named box-shadow
```

**Comment by thomaspark** [comment]
Are you compiling `_bootswatch.scss` directly by any chance? You should import it (and `_variables.scss`) into `_bootswatch.scss`.

**Comment by Tareck117** [comment]
I am not sure I understand your comment correctly ? I should import `_bootswatch.scss` and `_variables.scss` into what exactly ?

**Comment by thomaspark** [comment]
You should import them into the main file of bootstrap-sass, not compile them directly.

**Comment by thomaspark** [comment]
To follow up, you should create your own scss file which might look roughly like this:

```
@import "bower_components/bootswatch/cosmo/_variables.scss";
@import "bower_components/bootstrap-sass-official/assets/stylesheets/_bootstrap.scss";
@import "bower_components/bootswatch/cosmo/_bootswatch.scss";
```

**Comment by wendellm** [comment]
Could you please open this issue again I am having the exact same problem. I have the files setup as indicated in previous comment and I do use webpack but it does not matter. If I require the scss files doing it the webpack way or import them into my main scss doing it the sass way, I both get the same error message namely:

    Module build failed: 
    undefined
              ^
          No mixin named box-shadow

    Backtrace:
    	stdin:16
          in C:\cs\cs-shell-new\node_modules\bootswatch\paper\_bootswatch.scss (line 16, column 12)
    Error: 
    undefined
              ^
          No mixin named box-shadow

    Backtrace:
    	stdin:16
          in C:\cs\cs-shell-new\node_modules\bootswatch\paper\_bootswatch.scss (line 16, column 12)
        at options.error (C:\cs\cs-shell-new\node_modules\node-sass\lib\index.js:277:32)
     @ ./~/bootswatch/paper/_bootswatch.scss 4:14-247 13:2-17:4 14:20-253

At line 16 i find nothing but near it I indeed find the usuage of the mixin box-shadow according to [this](http://stackoverflow.com/questions/17098818/what-is-wrong-with-my-box-shadow-sass-mixin) article I should put comma's between the parameters which I did but that didn't help either. Suggestions?

**Comment by thomaspark** [comment]
Can you try updating the Bootswatch files to the latest version manually? The npm package might not have the fix for this yet.

**Comment by arttus** [comment]
I grabbed the latest version of bootstrap-sass   "version": "3.3.6"

// Drop shadows
//
// Note: Deprecated `.box-shadow()` as of v3.1.0 since all of Bootstrap's
// supported browsers that have box shadow capabilities now support it.

@mixin box-shadow($shadow...) {
  -webkit-box-shadow: $shadow; // iOS <4.3 & Android <4.1
          box-shadow: $shadow;
}

**Comment by thomaspark** [comment]
Thanks for the info @arttus. Looks like the box-shadow mixin is still available in `_vendor-prefixes.scss` but will be removed in v4.

**Comment by IvanGanev** [comment]
Hi, I have exactly the same problem. The theme "paper" and "readable" not working, is issued the same error. But "united" is working fine. Is there something to do?
