### ISSUE TITLE
paper text fields and areas are a bit hard to see

### ISSUE THREAD

**Issue by cpg** [thomaspark/bootswatch#481]
i love the paper theme. however, i keep on modding it a little so that the text areas and the text fields (and even the selectors) can be seen a little more, otherwise they are indistinguishable (until selected, when the beautiful blue bottom border appears), hence here is my suggestion:

```
  background-color: #fff;
  border: 1px solid #ddd;
  padding: 2px;
```

granted this may not work within panels or other perfectly white surfaces.

not sure what to do there in general, but i have put some of my panels with a #F9F9F9 background color.

**Comment by thomaspark** [comment]
Thanks for the suggestion, but keeping as is for now.
