### ISSUE TITLE
about commit 06885df : replace fonts with symlinks and bower opinionated about symlinks handling...

### ISSUE THREAD

**Issue by optyler** [thomaspark/bootswatch#483]
After the commit 06885df3cfbb7d498f59dc5ac61a4cc1cc4f6dc2 we started to get 404 http errors with the glyphicons fonts...

As you can see on the official bower documentation [about ignored files](http://bower.io/docs/creating-packages/#ignore) symlinks are automaticly ignored...

> Note: symbolic links will always be ignored. However bower.json will never be ignored.

So, after a `bower install --save bootswatch` fonts are not loaded due to previous citation...

To make it work, all our devs should create links manually `ln -s ../bootstrap/fonts .` ... any idea on how to solve this in a better way?

**Comment by thomaspark** [comment]
Ah, didn't realize Bower ignored symlinks. Dropping symlinks and adding a Bower postinstall script that copies over the font files whenever Bootstrap package is updated.
