### ISSUE TITLE
From 3.3.4 to 3.3.5: Now my page is white..?

### ISSUE THREAD

**Issue by IngwiePhoenix** [thomaspark/bootswatch#484]
I am using the `cyborg` theme and originally had myself set up like this:

- WebPack with `sass-loader` and the `extract-text-plugin`, so that I can code my CSS in SCSS and export it into a single CSS.
- [bower.json](https://github.com/DragonsInn/BIRD3/blob/master/bower.json#L47-L48) set to download the correct versions.
- And then my [bootstrapper.scss](https://github.com/DragonsInn/BIRD3/blob/master/web-lib/bootstrapper.scss) to generate the styles.

With this setup, I updated my local code to 3.3.5. And suddenly, white borders, backgrounds and such everywhere...

What has changed, that this no longer works? For the time being, I probably will downgrade to 3.3.4...

**Comment by thomaspark** [comment]
There haven't been any major changes to Cyborg aside from the minor version bump.

The only major change was fixing the `$icon-font-path` file for SASS to match Bootstrap-SASS and support asset loaders (see #453).

**Comment by IngwiePhoenix** [comment]
Weird. Updating to 3.3.5 caues my design to completely break...

**Comment by thomaspark** [comment]
Just pushed a fix related to asset loader in SASS (ceefe110c1f64b9ebca41215d02c6e50e45d9e19). Can you try using this file and see if it fixes your problem?

https://raw.githubusercontent.com/thomaspark/bootswatch/gh-pages/cyborg/_variables.scss

**Comment by IngwiePhoenix** [comment]
Ill give it a try now!

**Comment by IngwiePhoenix** [comment]
Nope. I still get the borders being white and such.

In `~3.3.5`: https://www.dropbox.com/s/fjav17ca5x3jgtb/Screenshot%202015-07-19%2011.28.26.png?dl=0
In `3.3.4`: https://www.dropbox.com/s/d94ks1xu05j1sum/Screenshot%202015-07-19%2011.29.08.png?dl=0

I forgot to scroll down, causing you to see the white buttons that should be grey due to the Cyborg theme. For these screenshots, I also left `bootstrap-sass` at `~3.3.5`. So I am pretty much lost. Can you verify that the variables in `cyborg/_variables.scss` are correct?

**Comment by thomaspark** [comment]
It seems to be correct. I also tried creating panels and buttons with sass and they were styled as expected.

In your main scss file, can you check the order of your imports? Cyborg's `_variable.scss` should be imported before Bootstrap's `_bootstrap.scss`.
