### ISSUE TITLE
[Paper] Floating buttons

### ISSUE THREAD

**Issue by benjamincanac** [thomaspark/bootswatch#485]
Do you plan in implementing the material floating buttons ?

https://www.google.com/design/spec/components/buttons-floating-action-button.html

**Comment by xd1936** [comment]
There may be some code and resources to draw from at [Google's Material Design Lite repo](https://github.com/google/material-design-lite).

**Comment by thomaspark** [comment]
I don't intend to implement floating buttons specifically as Paper is meant to be a 1:1 conversion of Bootstrap, which doesn't have an equivalent.

It might be possible convert an existing Bootstrap class to be round buttons though, such as `btn-sm` or `.label`, if it doesn't stray too far from its semantics. See #303 for previous discussion.
