### ISSUE TITLE
Undefined variable: "$bootstrap-sass-asset-helper"

### ISSUE THREAD

**Issue by mouradsm** [thomaspark/bootswatch#486]
When I compile sass file I'm getting this error 

[10:31:50] gulp-notify: [Laravel Elixir] Sass Compilation Failed!: resources/vendor/bootswatch/yeti/_variables.scss
  79:21  Undefined variable: "$bootstrap-sass-asset-helper".

**Comment by thomaspark** [comment]
Just pushed ceefe110c1f64b9ebca41215d02c6e50e45d9e19. Can you see if this fixes the problem?

https://raw.githubusercontent.com/thomaspark/bootswatch/gh-pages/yeti/_variables.scss

**Comment by mouradsm** [comment]
Solved! Thanks!
