### ISSUE TITLE
text-rendering: optimizeLegibility causes problems in many older Android browsers

### ISSUE THREAD

**Issue by mzaslavsky** [thomaspark/bootswatch#489]
text-rendering: optimizeLegibility is known to cause problems for many Android users. Older browsers may be slowed down by the option (https://bocoup.com/weblog/text-rendering/) and newer browsers have more specific alternatives for kerning (e.g. https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings).

In Android 2.x you'll get rectangles wherever white-space would be. Some Android 4.x browsers have been known to have unclickable links or even crash. (references http://stackoverflow.com/search?q=[android]+optimizelegibility). Some language fonts won't work at all. These are just some of the reasons the CSS property was removed from Bootstrap core (https://github.com/twbs/bootstrap/search?q=optimizelegibility&type=Issues&utf8=%E2%9C%93).

**Comment by thomaspark** [comment]
Thanks for bringing this to my attention. Seems like the niceness of text rendering is outweighed by some serious glitches.
