### ISSUE TITLE
Paper: incorrect display of input-group-addons within has-error

### ISSUE THREAD

**Issue by m-burst** [thomaspark/bootswatch#491]
![image](https://cloud.githubusercontent.com/assets/3243475/8728430/b8181196-2bed-11e5-973c-cfad898f0f9e.png)
On the bootswatch website, it looks correctly. 
I'm using freshly downloaded version from NPM, also tried version from BootstrapCDN. 
It seems that some styles are missing in the NPM and CDN distributions.

**Comment by thomaspark** [comment]
Can you try downloading from this repo or bower? Should have the corrected versions.

**Comment by m-burst** [comment]
Yes, this repo has the corrected version. 
Are you planning to update the NPM package? I'm using NPM for my project and it would be great to keep everything in the same place.

**Comment by thomaspark** [comment]
Unfortunately the package can't be updated until the next version number bump due to how NPM works. Bower should have the latest though.

**Comment by m-burst** [comment]
Found another problem with paper inputs: `readonly` inputs within `.has-error` or `.has-success` do not get the colored underline.
This time I'm using the version from the repo.
