### ISSUE TITLE
[Yeti] Pagination style problem with Laravel

### ISSUE THREAD

**Issue by kscheung** [thomaspark/bootswatch#496]
I am using Laravel with Yeti theme, however, the default pagination block generated by it has a problem with this theme.

The disabled and active link is larger than other page links. The cause of it could be the generated element inside `li.disable` and `li.active` is `span` instead of `a`. 

Bootstrap itself has defined the `padding` for both `span` and `a` under `.pagination-sm`. So I think the theme should override for both tags too.

This is the sample default pagination code generated by laravel
```html
<ul class="pagination pagination-sm">
	<li class="disabled"><span>«</span></li>
	<li class="active"><span>1</span></li>
	<li><a href="http://some-url?page=2">2</a></li>
	<li><a href="http://some-url?page=3">3</a></li>
	<li><a href="http://some-url?page=4">4</a></li>
	<li><a href="http://some-url?page=5">5</a></li>
	<li><a href="http://some-url?page=6">6</a></li>
	<li><a href="http://some-url?page=7">7</a></li>
	<li><a href="http://some-url?page=8">8</a></li>
	<li><a href="http://some-url?page=2" rel="next">»</a>
	</li>
</ul>
```

**Comment by thomaspark** [comment]
Thanks for the bug report, fix inbound.
