### ISSUE TITLE
Support for Bootstrap 4

### ISSUE THREAD

**Issue by travisdahlke** [thomaspark/bootswatch#499]
With the release of Bootstrap 4 alpha, when can we expect the bootswatch themes to be updated? I know it probably makes sense to wait for a beta before spending too much time on it.

**Comment by thomaspark** [comment]
Yeah, I think it makes sense to wait for beta. If I recall correctly, v3 had some big changes during alpha.

**Comment by cyberbit** [comment]
+1 on this. Can't wait to see how it all works out with the new built-in switches and stuff. Could make it trivial to have a light and dark version of each theme.

**Comment by dtamm** [comment]
+1, really appriciate it! @thomaspark if we can help you with this, let us know!

**Comment by RobLoach** [comment]
Bootstrap 4 also uses SASS natively, so changing some of those variables will make life easier.

**Comment by jdtzmn** [comment]
+1

**Comment by kraymond70** [comment]
+1

**Comment by jgog** [comment]
I'm in for help too @thomaspark

**Comment by jasoncavett** [comment]
I would be happy to provide any testing that I can once this issue is being worked. Thank you for a great theme!

**Comment by nmocruz** [comment]
+1

**Comment by wesleyfsmith** [comment]
+1 awesome to hear that bootstrap 4 support is being looked at once it's stable

**Comment by jipexu** [comment]
+1 i have already play with both BS4 and boostwatch and update and change something so i can help and test

**Comment by TheCoder4eu** [comment]
+1 BS4 Alpha is advancing slowly, so I guess it's best to wait for beta.

**Comment by bapatel1** [comment]
+1

**Comment by RobLoach** [comment]
You you want to show your desire for Bootswatch to upgrade to Bootstrap 4, then [Add a GitHub Reaction](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) rather then commenting `+1`.

![https://cloud.githubusercontent.com/assets/25792/13683303/d55b8b7e-e6ba-11e5-9b31-59a8db92e456.gif](https://cloud.githubusercontent.com/assets/25792/13683303/d55b8b7e-e6ba-11e5-9b31-59a8db92e456.gif)

Commenting +1 just adds unnecessary noise to the thread. Thanks.

**Comment by Celti** [comment]
For what it's worth, it's relatively easy to grab the Bootstrap 3 SCSS version of whatever theme you want and update it to 4 by hand.

**Comment by robcresswell** [comment]
Given that 3 has now ended support, seems like it might be a good time to start working on this?

**Comment by robcresswell** [comment]
Any news/updates here on v4? Accepting pull requests? Should we fork? Radio silence is not good :(

**Comment by julmot** [comment]
Ping @thomaspark 

@Celti What exactly did you change?

**Comment by thomaspark** [comment]
Hey all, even though v4 hasn't left alpha yet, I'm going to start work on upgrading the themes over the next couple of weeks. So you'll be able to jump to v4 now if you want to, and we'll be ready to go for beta.

**Comment by jipexu** [comment]
yes great new !! The last change bs04 bs05 still had some classe name change hope it will be less and less in the next bs alpha ...

**Comment by springuper** [comment]
@thomaspark great!

**Comment by jsantana90** [comment]
awesome +1

**Comment by thomaspark** [comment]
Bootswatch v4 (well, a preview of...) is here! You can check out the latest progress at https://github.com/thomaspark/bootswatch/tree/v4.

Of course it goes without saying that this is very much a work-in-progress. If you spot any bugs, now is a great time to report them, but please check the bug on vanilla Bootstrap first to make sure it's not an upstream issue.

Some notes:
* Builds are based on Bootstrap v4.0.0-alpha.5. I'll try to keep it updated with each new version, but hopefully things are stabilizing and we're close to beta.
* Readable has been removed in v4.
* Paper has been renamed to Materia.

**Comment by mika76** [comment]
Awesome! Any chance there is an online version to peruse?

**Comment by thomaspark** [comment]
Good idea, just put them up temporarily here: http://bootswatch.com/4-alpha/

**Comment by jsantana90** [comment]
would it be okey if I target http://bootswatch.com/4-alpha/materia/bootstrap.min.css for the css instead of having to download it?

**Comment by thomaspark** [comment]
You can hotlink it for testing/playing around, but would definitely advise against it for production since I plan to take the link down eventually.

**Comment by DavidJBerman** [comment]
Requesting that you please incorporate Readable in Bootswatch for BS4 - We love it and are using it in production.

(Also, thanks for everyone's hard work on this incredible project).

**Comment by thomaspark** [comment]
Hey @DavidJBerman, thanks for your reply. I just added a new theme to the v4 branch called Litera that is a spiritual successor to Readable. It uses the same color palette, similar fonts, and incorporates a lot of the same features like a serif body font. Please test it out and hopefully it makes the port to BS4 seamless for you.

![thumbnail](https://cloud.githubusercontent.com/assets/900407/21290450/ac679008-c488-11e6-98db-9204b58aa087.png)

**Comment by jipexu** [comment]
cool !

**Comment by DavidJBerman** [comment]
Thank you very much @thomaspark much abliged!

I am hoping someone will make a bs3 -> bs4 shim.  It doesn't make sense to me to sweep through all pages of an existing site to replace classes like push-right in order to add new pages that take advantage of cards or other new features.

**Comment by robcresswell** [comment]
Any chance of an alpha release to a CDN or distribution point like NPM? Would be great to let people test this via their existing toolchains installs instead of using source

**Comment by julmot** [comment]
You might use RawGit as a dev CDN

**Comment by fulldecent** [comment]
Here is a CDN-usable version for people that want a drop-in replacement:
https://cdn.rawgit.com/thomaspark/bootswatch/v4/flatly/bootstrap.min.css

And here is a SRI version:

    <link rel="stylesheet" href="https://cdn.rawgit.com/thomaspark/bootswatch/v4/flatly/bootstrap.min.css" integrity="sha384-mLoAoVVKI5Ylfekhi0wRovakSfJXZJd/4G/hFADK5cB5L6R2JYjur4rRdGS9czwd" crossorigin="anonymous">

**Comment by WuglyakBolgoink** [comment]
any news?

**Comment by jasondt** [comment]
is there a v4 api yet?

**Comment by thomaspark** [comment]
Not yet, will update when v4 hits beta.

**Comment by lightdot** [comment]
Nearly two years after the alpha, Bootstrap v4.0.0-beta is here. Finally.

**Comment by jenil** [comment]
[This](https://getbootstrap.com/docs/4.0/migration/) is going to be a lot of work, @thomaspark lmk if you need a hand, I'm happy to help 🙃

**Comment by jipexu** [comment]
some class changes but not too much ..

**Comment by robcresswell** [comment]
@jipexu, there's much more to it than that. A lot of the variables have changed and that's what themes rely on. Don't underestimate the time it takes to put together several good themes, especially when its being done for free.

**Comment by jipexu** [comment]
yes i known.. but the step between te 2 lasts releases of BS is less than the past ...

**Comment by thomaspark** [comment]
Hey guys, sorry for the slow response, been traveling out of the country the past couple weeks. I'm thrilled (and mostly relieved) Bootstrap is hitting beta.

Wanna do an update for at least v4-beta.1 soon so people have something to work with. Hopefully there will be fewer and fewer major changes, which means keeping the themes synced with each beta release will be feasible. Let me tell you, it's been a lot of work keeping alphas in sync.

One change I'd like to make is to `_variables.scss`. Rather than being a copy of Bootstrap's `_variables.scss`, it will only hold modified variables which should make maintenance much easier. Don't see any issues with it...

Will try updating a couple of themes on the `v4` branch to see what it entails. Once that's done I'll welcome others to lend a hand. :wink: @jenil

**Comment by Inurias** [comment]
I’m currently working on a project on which I originally planned to use a Bootswatch theme.
The project is based on Bootstrap 4 Beta and I need to decide what I will eventually use in the next few days.

Do you happen to know a rough estimate as to when Bootswatch will be available for Bootstrap 4 Beta?

**Comment by TheMissingNTLDR** [comment]
Just wondering if this is released for Bootstrap4 Beta? I recently raised this on [StackOverflow](https://stackoverflow.com/questions/46043845/incorporating-bootstrap4-theme-in-a-ruby-rails-website) and which directed me to this thread! Ofcourse I will try [v4 Branch](https://github.com/thomaspark/bootswatch/tree/v4) (made for BS4_alpha6) first and see if this works in BS4_Beta!! Thanks!

**Comment by taniarv** [comment]
I have been using Bootswatch before (cosmo theme) and I was planning to use it in a new project using bootstrap 4 beta. 
If I use the _variables.scss available in https://bootswatch.com/4-alpha/cosmo/ I get an error in spacers block. 
```
(x: 0, y: 0) isn't a valid CSS value.
```
In order to get it working, I have to replace the spacers block with the following 
```
$spacers: (
  0: 0,
  1: ($spacer * .25),
  2: ($spacer * .5),
  3: $spacer,
  4: ($spacer * 1.5),
  5: ($spacer * 3)
) !default;
```

**Comment by robcresswell** [comment]
@TheMissingNTLDR @taniarv The last release of Bootswatch was for Alpha.6, not Beta. If you read the comments / check the tags, you can see there is no Beta release yet. There were a lot of changes between Alpha and Beta; some may cause errors like you noted above, but there will also likely be a lot of missing styles / colours that simply fall back to the Bootstrap defaults because of the various changes, so the themes will look weird, even if they "work"

**Comment by shadowcodex** [comment]
Hey @thomaspark thanks first for all the work you have put into this! Do you have an estimate of when you will get time to start the v4.beta.1 work? I'm starting work on a v4 component library / ui kit. Would love to include bootswatch themes as options for it.

**Comment by AmirSavand** [comment]
It would be **AWESOME** if we'd know when will it be completed to support v4 beta.

**Comment by tkuther** [comment]
Ported my application to Bootstrap 4-beta, and while I was at it, did a vim&sed warfare over bootswatch, too. See #685 . It's a start, but of course only a small part of the work.

I can really feel now how much work it is for @thomaspark to keep the themes updated. Huge thanks for that! Oh, and I _love_ sketchy .. how cool is that!

**Comment by TheCoder4eu** [comment]
Hi @thomaspark , just in case you missed it, beta2 is out! 
https://blog.getbootstrap.com/2017/10/19/bootstrap-4-beta-2/

**Comment by jipexu** [comment]
... yes is on the fire  ...

#693

**Comment by garymoon** [comment]
Jeez, there needs to be a `:O` reaction. Amazing.

**Comment by thomaspark** [comment]
Hey @TheCoder4eu, thanks for the heads up. Figures b2 would come out as I was in the midst of updating to b1. 😛 

Actually the work to go from b1 to b2 should be much less than a6 to b1. I'm pretty far along — have the preview pages done and going through the themes now. Hoping to have b2 done by this Monday.

@jipexu, I'll push what I have soon and take a look at your branch to see how we can merge our work together. One change I've made is the approach for `_variables.scss` to only include the variables that have been modified. This should cut down on maintenance work as each version of the variables file changes things up.

**Comment by AmirSavand** [comment]
@thomaspark Can't wait to create some themes for our blogging platform (gonevis.com).

BTW people, +1 seems like a useless comment but actually, some developers say it keeps them motivated.

**Comment by robcresswell** [comment]
@AmirSavand I've not heard that. Many projects explicitly ask you to use GH reactions like thumbs up to avoid email spam. If we all sent in +1s they'd have a constant stream of useless emails :)

**Comment by AmirSavand** [comment]
@robcresswell I totally agree, I never heard till I've read about it on reddit.

**Comment by jipexu** [comment]
@thomaspark  yes i am sure you will find better approch for the variable ...mine was a little be cahotic ... and i dont know enough the theme to see all the small rendering mistake ...
because sometimes i (we) used the gray scale as a other color scale .... so is not always easy to maintain so no prob take what you need or only use as base ... i done just to have something that work quickly ... and it was a good exercice to play scss with koala !

**Comment by TheCoder4eu** [comment]
Hi @thomaspark , just in case you missed it, beta2 is out! 
https://blog.getbootstrap.com/2017/10/19/bootstrap-4-beta-2/

Theming reference page:
http://getbootstrap.com/docs/4.0/getting-started/theming/

**Comment by TheCoder4eu** [comment]
@thomaspark  , yes, in the blog post they admit the delta between alpha6 and beta was brutal, and they promise changes between betas/final will not have the same impact.

**Comment by TheCoder4eu** [comment]
Btw @thomaspark thanks for the big effort you are doing to support v4!!!!

**Comment by thomaspark** [comment]
OK, I might have been optimistic about getting it all done today, but making good progress. Just pushed what I have to the [v4 branch](https://github.com/thomaspark/bootswatch/tree/v4).

Updated themes include cerulean, cosmo, cyborg, darkly, flatly, journal, litera, materia, and yeti. The rest will be coming soon!

**Comment by utopianknight** [comment]
+1 for paper theme

**Comment by paulbhartzog-ps** [comment]
> OK, I might have been optimistic about getting it all done today, but making good progress. Just pushed what I have to the v4 branch.
> 
> Updated themes include cerulean, cosmo, cyborg, darkly, flatly, journal, litera, materia, and yeti. The rest will be coming soon!

Delighted these are updated but how do we access them via CDNs like maxcdn?

thx

**Comment by robcresswell** [comment]
@thomaspark If you want to open issues for each missing theme, I'm sure we could divide up the work and take them on. I've got time to help out, and I've been using Bootstrap / Bootswatch for years; please don't feel you have to do all the work by yourself.

**Comment by robcresswell** [comment]
@utopianknight Comments like that are incredibly unhelpful. For a start, I'm fairly sure the "Paper" theme is identical to "Materia", and if not, just leaving a +1 with "do some free work for me" is a terrible attitude.

**Comment by paulbhartzog** [comment]
Just wanted to say thx to anyone who helps out on this. :-)

**Comment by thomaspark** [comment]
Hey all, thanks for the support!

@robcresswell, I'll be ok updating the themes myself, but help with markup on the `index.html` pages would be welcome. Issues like #698 and updating any markup I've missed to v4, or better yet, a grunt task that rebuilds all of the preview pages from template using something like grunt-html-build and the metadata in `/api/4.json`.

**Comment by nickmccurdy** [comment]
Sweet, can we please get `4.0.0-beta.2` published on npm? It seems to be tagged in the repo but not on npm.

**Comment by thomaspark** [comment]
@nickmccurdy, done! https://www.npmjs.com/package/bootswatch

**Comment by nickmccurdy** [comment]
Awesome, thanks! I'm looking forward to testing this out for a production site.

Is it intentional that the theme directories are now in a `dist` folder instead of the top level folder?

**Comment by thomaspark** [comment]
Yup there was a bit of a reorg for the repo, `dist` for the themes, `docs` for the site, so they don't get mixed up with all the meta files.

**Comment by nickmccurdy** [comment]
Nevermind I noticed that upstream now does that too, so it makes sense to keep it consistent. 😄

**Comment by YoungZeeZee** [comment]
Hi All,

I am very new at Bootstrap/bootswatch and do not have any background knowledge about things. My website collapsed on Saturday later noticed that the "min.css" got an extra "4" in the link. Now it works better but some features are still not working. i.e: dropdown menus from bootswatch. It does nothing and have a problem with "Basic Collapsible" feature,  "bootstrap.min.js" is not working well with bootswatch.
Could you please tell me what happened and what can i do now?

Thank you in advance for your help.
Regards,
ZeeZee

**Comment by thomaspark** [comment]
Hey @YoungZeeZee, if you haven't changed anything on your site yet, you should stick with version 3. You would just need to change your theme's url to add a 3 instead of 4. So something like https://bootswatch.com/3/flatly/bootstrap.min.css.

Better yet, go with this url as it's meant to be used this way: https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css

**Comment by YoungZeeZee** [comment]
Hi @thomaspark ,

Thank you for your quick response.
I have changed "4" to "3" and it works :)
When i started using bootswatch i added the link without any number so it was "https://bootswatch.com/superhero/bootstrap.min.css". 

Thank you again.

Kind regards,
Young ZeeZee

**Comment by YoungZeeZee** [comment]
Hi,
I am sorry I noticed that the dropdown menu is still not working (using "buttons" and "navs". I have just added them. Please see attached printscreen. Did i miss something?
![screen shot 2017-11-07 at 17 47 50](https://user-images.githubusercontent.com/26717395/32506109-09b58a48-c3e4-11e7-89ac-92e8af0dc8ac.png)
.

**Comment by jipexu** [comment]
you seems to have a probleme with js ...

**Comment by lightdot** [comment]
@YoungZeeZee, do not hotlink to repository files, this is a bad practice. As suggested, use a CDN:
https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/superhero/bootstrap.min.css
or download the files to the server where your web page is hosted and link them locally. Same goes for .js files.

**Comment by TheCoder4eu** [comment]
Hi @thomaspark , I just noticed that beta3 is out!

In the Blog post:
https://blog.getbootstrap.com/2017/12/28/bootstrap-4-beta-3/

they say it is the last release before Final!
Kind Regards!

**Comment by thomaspark** [comment]
Hey @TheCoder4eu, update for v4-beta.3 was just pushed in #765!

**Comment by TheCoder4eu** [comment]
@thomaspark Great! thank you!!!
