### ISSUE TITLE
[sandstone] Progress bars start after end cap

### ISSUE THREAD

**Issue by nemequ** [thomaspark/bootswatch#500]
I'm using the Sandstone theme, and I have [a bunch of progress bars](https://quixdb.github.io/squash-benchmark/#results-table).  Unfortunately, the left end cap is always filled in, even when the width is set to 0%.

**Comment by thomaspark** [comment]
It looks like you're adding a `padding-left: 1em` to `.progress-bar` via `.result-bar`, which is causing this. You can wrap your text in a span and then apply the padding to that instead.

**Comment by nemequ** [comment]
Done, thanks!  Sorry about blaming your project (and making you debug mine).

**Comment by thomaspark** [comment]
No worries, your project looks great btw.
