### ISSUE TITLE
invalid-meta

### ISSUE THREAD

**Issue by schel4ok** [thomaspark/bootswatch#501]
I have invalid meta warning in the end of download
```
bower progress      bootswatch#gh-pages Resolving deltas: 100% (4441/4441), done.
bower invalid-meta  bootswatch is missing "main" entry in bower.json
bower resolved      git://github.com/thomaspark/bootswatch.git#15748399fc
```

**Comment by thomaspark** [comment]
Thanks for the heads up. In the case of Bootswatch, it doesn't make sense to assign any one file as main. So as long as it's optional, we'll avoid setting it. See also #324 and #473 .
