### ISSUE TITLE
Glyphicons not loading in Bootswatch 3.3.5

### ISSUE THREAD

**Issue by isabelleflores** [thomaspark/bootswatch#502]
For example, `GET file:////src/node_modules/bootswatch/fonts/glyphicons-halflings-regular.woff2 net::ERR_FILE_NOT_FOUND`

Dropping down to 3.3.4 fixes the issue.

**Comment by thomaspark** [comment]
Are you using `npm` by any chance? There was an issue with the fonts being included for 3.3.5 — see #493.

If you're using `bower` or git clone, they should be there.

**Comment by isabelleflores** [comment]
Ah yes looks like that's what the issue was!

**Comment by thomaspark** [comment]
Thanks, should be fixed in the next release. Sorry about that!

**Comment by MrHubble** [comment]
@thomaspark I am having a similar problem to this issue with 3.3.6. I am using bootstrap-sass in my Rails app:

````
@import "bootstrap-sprockets";
@import 'bootstrap';
@import "bootswatch_superhero.min";
@import "bootswatch_superhero_variables";
````

In another closed issue you replied:
>Check the path to the font files in your generated CSS. You may need to adjust @icon-font-path variable in flatly/variables.less.
https://github.com/thomaspark/bootswatch/issues/409#issuecomment-77417738

Would that be relevant here? If yes, are you able to suggest what I set for `$icon-font-path: '?what goes here?';`

Thanks for the great themes.
