### ISSUE TITLE
Paper floating labels cross browser issues

### ISSUE THREAD

**Issue by kramer65** [thomaspark/bootswatch#504]
I really love the bootswatch paper theme and I now also want to add the floating labels as described in this blogpost. Unfortunately, the floating labels don't show up so nice in combination with the placeholders in different browsers.

Only Chrome seems to be fine:

![schermafbeelding 2015-09-01 om 10 26 36](https://cloud.githubusercontent.com/assets/596581/9599481/9c7e28fa-5094-11e5-942b-2df6541c42d2.png)

but as you can see below, firefox and safari look horrible. 

Does anybody know how I can make this work well on all major browsers? All tips are welcome!

![schermafbeelding 2015-09-01 om 10 27 22](https://cloud.githubusercontent.com/assets/596581/9599498/b1a99142-5094-11e5-86d4-6d31654c497c.png)

![schermafbeelding 2015-09-01 om 10 28 19](https://cloud.githubusercontent.com/assets/596581/9599506/c03f5c3c-5094-11e5-8989-9d588f747821.png)

**Comment by thomaspark** [comment]
Essentially you have to add vendor prefixes to a bunch of things. This should work in Firefox and Safari (haven't tested IE):

http://jsfiddle.net/bootswatch/25jwefd2/

**Comment by kramer65** [comment]
Awesome, thank you!
