### ISSUE TITLE
Can't tell between focused and unfocused checkbox in the Paper theme

### ISSUE THREAD

**Issue by dandv** [thomaspark/bootswatch#505]
To reproduce, focus the Password field at https://bootswatch.com/paper/ and tab to the next field (the checkbox).

![image](https://cloud.githubusercontent.com/assets/33569/9600221/a601681a-504e-11e5-9e97-fd6d8f4a3910.png)

By comparison, in United, Superhero, Yeti and other themes, there's an `outline: 5px auto -webkit-focus-ring-color`:

![image](https://cloud.githubusercontent.com/assets/33569/9600316/58808750-504f-11e5-94c8-7945143528f6.png)

Maybe the outline is not the prettiest, but it helps with accessibility when using keyboard navigation.

**Comment by thomaspark** [comment]
Thanks for the suggestion, we should be able to give focused checkboxes some sort of feedback like this for Paper as well.

**Comment by thomaspark** [comment]
Focused checkboxes will now have a colored border:
<img width="101" alt="screen shot 2015-09-01 at 1 47 21 pm" src="https://cloud.githubusercontent.com/assets/900407/9611845/fe7b7d3a-50af-11e5-9c6e-808ec64c0e8d.png">

**Comment by dandv** [comment]
Thanks! This is better than the [Polymer Paper implementation](https://www.polymer-project.org/0.5/components/paper-elements/demo.html#paper-checkbox) now.

**Comment by dandv** [comment]
Nevermind my comment above. [Turns out](https://github.com/PolymerElements/paper-checkbox/issues/58#issuecomment-136887401) the current demo for Polymer Paper elements is at https://elements.polymer-project.org/elements/paper-checkbox?view=demo:demo/index.html, and the focused checkbox does have a circle around it.
