### ISSUE TITLE
Composer dependency

### ISSUE THREAD

**Issue by sagikazarmark** [thomaspark/bootswatch#506]
The composer package could depend on the composer package for bootstrap:

https://packagist.org/packages/twbs/bootstrap

You could use the special `self.version` constraint if you want to depend on the same version.

**Comment by thomaspark** [comment]
Good catch. Is `self.version` documented anywhere? I'm wondering how build metadata is handled, e.g., whether Bootswatch v3.3.5+2 would resolve to Bootstrap v3.3.5 or not.

**Comment by sagikazarmark** [comment]
I found this links relevant, haven't read the issue carefully though:

https://getcomposer.org/doc/04-schema.md
https://github.com/composer/composer/issues/578
