### ISSUE TITLE
Imports from third party locations should be a variable

### ISSUE THREAD

**Issue by hurgleburgler** [thomaspark/bootswatch#507]
I would <3 to use the Bootswatch themes on an open source application, Openstack Horizon, that might sit behind a network firewall.

I know that I will have to package up the resources myself (fonts), but it would be awesome if we could make this import to take a variable name that can be changed based on the environment as needed, but just defaults to the value it is now.

Until then, I fear the packagers for the project won't allow us to use it.

**Comment by mrunge** [comment]
yeah, bootswatch wouldn't be usable in a closed environment, self hosted and disconnected from the internet.

**Comment by thomaspark** [comment]
Hi @hurgleburgler, we should be able to accommodate this. Is it enough to have a less/sass variable with the import url, which you can override to point to your self-hosted fonts? Or do you need the web fonts to be packaged up with Bootswatch?

**Comment by hurgleburgler** [comment]
Its enough to just have a variable that points to it, since we will probably have to do the packaging of the other assets ourselves as well.  Thanks @thomaspark !

**Comment by thomaspark** [comment]
How's this? You should be able to override the value of `@web-font-path` at any point afterwards.

```
@web-font-path: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700";

.fonts(@path) {
  @import url("@{path}");
}
.fonts(@web-font-path);
```

**Comment by hurgleburgler** [comment]
@thomaspark I think that will work.

**Comment by untitaker** [comment]
I tried this in LESS, and it doesn't seem that this prevents the original webfont from being loaded, it includes both files instead.

**Comment by thomaspark** [comment]
Can you share a demo of this? It's loading just the one for me.

**Comment by untitaker** [comment]
I'm sorry, I did something wrong I think. However, the last line in your example will import the same font a second time.
