### ISSUE TITLE
Form Styling seems broken

### ISSUE THREAD

**Issue by MeirionHughes** [thomaspark/bootswatch#508]
The given example for a form (I copied the code directly from the example) doesn't seem to get the correct padding/margins as is. 

http://jsfiddle.net/g1q7jxzf/94/

remove ``` "class="form-horizontal" ``` and the padding appears correct;

http://jsfiddle.net/g1q7jxzf/95/

Am I missing something?

**Comment by thomaspark** [comment]
On the example page, the form is wrapped in a well to give it padding and background:

http://jsfiddle.net/bootswatch/u0u2cttq/

**Comment by MeirionHughes** [comment]
yeah that's it.
