### ISSUE TITLE
Issue with Glyphicons

### ISSUE THREAD

**Issue by yifeiwu** [thomaspark/bootswatch#509]
I'm using version 3.3.5 with Rails 4. When I try to use a glyphicon nothing shows up or the wrong symbol is displayed. Any ideas?

**Comment by thomaspark** [comment]
There was an issue with icon fonts in v3.3.5 (see #493), so you might have to grab the font files and place them in the right path manually. Will be fixed in the next version. Sorry about that!

**Comment by yifeiwu** [comment]
Ahh thanks, thought it might be just me.
