### ISSUE TITLE
npm install includes bower_components directory

### ISSUE THREAD

**Issue by dandv** [thomaspark/bootswatch#512]
```sh
npm install bootswatch
ls node_modules/bootswatch/bower_components
```

Is this intended? Should that directory be node_modules, or added to `.npmignore`? `package.json` doesn't have any `dependencies`.

**Comment by thomaspark** [comment]
`/bower_components/` could be added to `.npmignore`.

There's actually a bunch of files that could be ignored. Basically the same list as in `bower.json` except swapping `bower.json` for `package.json`.

**Comment by thomaspark** [comment]
This should take effect in the next version.
