### ISSUE TITLE
Affix position doesn't reset when scrolling back up

### ISSUE THREAD

**Issue by martinsifra** [thomaspark/bootswatch#513]
This problem has benn fixed up with https://github.com/twbs/bootstrap/issues/9342. With latest original bootstrap.css everything goes well, but with latest Flatly CSS is there still this issue.

**Comment by thomaspark** [comment]
Can you post a demo in jsfiddle/jsbin? There shouldn't be any difference in how it's handled with Flatly.

**Comment by martinsifra** [comment]
Here is my project, where the issue appears: http://dev.elastickelano.cz/order/. Before AJAX is everything OK, but if you call AJAX (change input with number or click button "Přepočítat") the affix stop working. Changed is only some ements inside ```<div id="sidebar">``` not all the elelement. With latest original CSS is everything OK.

**Comment by thomaspark** [comment]
Can you post a link of it with original bootstrap? It doesn't seem to be working right with either for me.

**Comment by martinsifra** [comment]
Here is the Bootstrap version:http://orig.elastickelano.cz/order/. If you'll have some 500 errors on requests, delete cookies. The app have some issues on backend :-)

**Comment by thomaspark** [comment]
Thanks for the link. I think I was able to replicate the issue with standard Bootstrap, so the problem is probably somewhere in your affix code. Here's a gif of what I see:

![affix](https://cloud.githubusercontent.com/assets/900407/9854400/b90b2e9a-5ad6-11e5-905c-6268757a51fd.gif)

**Comment by martinsifra** [comment]
I see. I've tried it in fullscreen and issue didn't appear. I can solve the problem as someone wrote "affix-bottom {position: relative}" however is weird, if they solved this issue as solved. I use the standard way, how to use affix. Nothing more…
