### ISSUE TITLE
libsass support broken

### ISSUE THREAD

**Issue by hbj** [thomaspark/bootswatch#514]
It is not possible anymore to compile the sass files with libsass, it exits with the following error:

```
@import directives are not allowed inside mixins and functions
```

This is due to the `web-font` mixin. I suggest to replace the mixin with a simple import to fix it.

**Comment by thomaspark** [comment]
Relevant note:
https://github.com/thomaspark/bootswatch/commit/913f54b9483b99fa12c7feccfa18ee5cc0206043#commitcomment-13277848

Possible workaround mentioned in it:
https://github.com/penman/Sass-Web-Fonts/issues/14

**Comment by hbj** [comment]
This worked for me (for the paper theme):

```
$web-font-path: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" !default;

@import url("#{$web-font-path}");
```

Tested with `node-sass@3.3.3` which uses `libsass@3.2.5`.

**Comment by tyleriguchi** [comment]
Created a pull request (#515) using @hbj's fix.

**Comment by thomaspark** [comment]
Thanks for the pull request! Instead of manually fixing the SASS files though, the fix should be made to the Grunt task here: https://github.com/thomaspark/bootswatch/blob/gh-pages/Gruntfile.js#L206

This task is used to convert the LESS source to SASS so only one has to be maintained.

**Comment by hbj** [comment]
I think actually that the changes need to be done in the respective `bootswatch.less` files of the themes.

**Comment by cjsewell** [comment]
I tried for a while to make this work happily with LESS and SASS but the only way I could get it to work is to do as @thomaspark suggested and make the Grunt convert_less task do the work.

Pull request submitted with required SASS and Gruntfile.js changes here https://github.com/thomaspark/bootswatch/pull/516

**Comment by thomaspark** [comment]
Very nice, @cjsewell's changes seem to do the trick.
