### ISSUE TITLE
Add links to component sections

### ISSUE THREAD

**Issue by megapctr** [thomaspark/bootswatch#519]
Though section headings do have `id` attributes, there's no link to these - you have to add url hash manually. E.g. if you wanted to compare typography between two themes, you'd have to append `#type` to their urls (and before that, open dev toolbar and look up the id of the section).

Adding a table of contents would be helpful, or perhaps headings could just link to themselves.

**Comment by thomaspark** [comment]
Thanks for the suggestion. Gonna add a table of contents.
