### ISSUE TITLE
Incorrect usage of semver in release versioning

### ISSUE THREAD

**Issue by warpech** [thomaspark/bootswatch#520]
According to [semver 2.0 spec](http://semver.org/):

> Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence.

What this means is that my bower client does not really know if version `v3.3.5+4` is newer than `v3.3.5+3`. They are treated equal.

**Comment by thomaspark** [comment]
Strict semver ignores build metadata, but if I recall correctly, bower does use it to determine precedence (npm does not).

The main alternative is for Bootswatch version numbers to fall out of step with Bootstrap, but that seems more trouble than anything else. I feel this is one area where semver could be improved.

**Comment by warpech** [comment]
Or use prerelease notation, but that also has it's pitfalls.

**Comment by tandrewnichols** [comment]
Possibly related . . . if I run `bower install bootswatch --save`, bower adds (currently) `"bootswatch": "^3.3.6+1"`. I have bower_components in gitignore, so if I later run just `bower install`, I get this error:

```
bower bootswatch#^3.3.6+1          ENORESTARGET Tag/branch ^3.3.6+1 does not exist
```

(even though the "additional details" _does_ include "v3.3.6+1"). If there is any semantic versioning strategy you can use that would make install work as expected, that would be awesome.
