### ISSUE TITLE
Superhero font weight

### ISSUE THREAD

**Issue by jgillich** [thomaspark/bootswatch#522]
Superhero uses the Lato font together with a font weight of 300, which makes it really hard to read:
![screenshot from 2015-10-10 09-30-58](https://cloud.githubusercontent.com/assets/347965/10409920/f55d2514-6f31-11e5-8df6-e1de3bd6b943.png)
Others seem to have the [same problem](https://www.reddit.com/r/web_design/comments/2t1wpl/is_it_just_me_that_finds_it_extremely_difficult/) with this font, too. I propose changing the font weight to 400.  Would you accept a PR?

**Comment by thomaspark** [comment]
Yes, I'd accept a PR for this. Let me know if you have any questions about modifying the LESS or building the CSS/SASS.
