### ISSUE TITLE
paper - shadows on panels

### ISSUE THREAD

**Issue by mika76** [thomaspark/bootswatch#523]
There seems to be a big lack of height in the paper theme, which googles material design uses quite a bit.

**Comment by thomaspark** [comment]
The panel's shadow doesn't seem too far off from Google's guidelines:

<img width="431" alt="screen shot 2015-10-12 at 2 08 15 pm" src="https://cloud.githubusercontent.com/assets/900407/10434935/c3d79f46-70ea-11e5-8bba-619a9a06fb56.png">

<img width="398" alt="screen shot 2015-10-12 at 2 08 27 pm" src="https://cloud.githubusercontent.com/assets/900407/10434936/c6cb3424-70ea-11e5-9289-00e4c6dd122c.png">

But a lot of Paper's effects are intentionally toned down from the material design guidelines.
