### ISSUE TITLE
Lumen - contents shift when you hover over a button (Chrome and Opera)

### ISSUE THREAD

**Issue by DeltaMeter** [thomaspark/bootswatch#524]
Like the title says, whenever you mouse over a button, it seems to shrink an tiny bit, causing everything below it to shift up a pixel or two. 
This bug shows up on Chrome and Opera. It is fine on Edge, Firefox, and Safari (according to a friend).
[Here's a gfycat of the problem.](http://gfycat.com/SpeedyPettyChevrotain)

**Comment by thomaspark** [comment]
Can you post the HTML snippet causing this? Is your button wrapped in a div?

**Comment by DeltaMeter** [comment]
Mostly just copied and pasted from the examples on bootswatch.com

    <h3 class = "text-center">Motion in One Dimension</h3>
    <hr>
    <div class = "col-md-6 col-md-offset-3 stage-selector">
        <div class = "dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Number of Stages
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labeslledby="dropdownMenu1">
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
            </ul>
        </div>
    </div>
    <div class = "col-md-6 col-md-offset-3">
        <div class = "well stages">
            <form class = "form-horizontal" action = "/motion/onedimension" method = "POST" autocomplete="off">
                <fieldset>
                    <input type = "hidden" class="form-control" name="stages" value="1">
                    <div class="form-group">
                        <label class = "control-label col-md-2">x</label>
                        <div class = "col-md-8">
                            <input type = "text" class="form-control" name="1distance">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputName" class = "control-label col-md-2">v0</label>
                        <div class = "col-md-8">
                            <input type = "text" class="form-control" name="1initialVelocity">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputName" class = "control-label col-md-2">vf</label>
                        <div class = "col-md-8">
                            <input type = "text" class="form-control" name="1finalVelocity">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputName" class = "control-label col-md-2">a</label>
                        <div class = "col-md-8">
                            <input type = "text" class="form-control" name="1acceleration">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputName" class = "control-label col-md-2">t</label>
                        <div class = "col-md-8">
                            <input type = "text" class="form-control" name="1time">
                        </div>
                    </div>
                    <div class = "col-md-4 col-xs-offset-4">
                        <input class = "btn btn-success btn-block" type="submit" value="Calculate!">
                    </div>
               </fieldset>
            </form>
        </div>
    </div>

This simple one doesn't work either:

    <div class="jumbotron">
        <h1>Welcome to Physics Help</h1>
        <p>Here you can learn more about specific physics concepts and use our custom calculators.</p>
        <p><a class="btn btn-primary btn-lg">About us</a>
    </div>

**Comment by thomaspark** [comment]
I tested your snippets on Win/Chrome and wasn't able to replicate this issue. Here are the demos I tried:

http://jsfiddle.net/gqhenoox/70/
http://jsfiddle.net/gqhenoox/71/

Can you test if you're getting it with these links? Also try updating your theme to the absolute latest: http://bootswatch.com/lumen/bootstrap.css

**Comment by DeltaMeter** [comment]
Ok. It only shows up as long as I zoom in with Chrome. If my zoom level is at 110% or lower, then it doesn't show the stuttering, but if I zoom in more, it becomes apparent.

**Comment by thomaspark** [comment]
This seems to be an issue with how Chrome handles non-integer border widths, which can be caused by zooming. One workaround is to set the height of the container like so:

http://jsfiddle.net/gqhenoox/74/
