### ISSUE TITLE
paper theme has dual entry for alert-success, -danger, -info, etc.

### ISSUE THREAD

**Issue by cfblaeb** [thomaspark/bootswatch#526]
In the paper theme, alert-success, alert-info, alert-danger, etc have a dual entry where the first correctly sets background and text color, but the second sets the text color to the same color as the background thus rendering the text invisible.
Example:
<span class="input-group-addon alert-success">OK</span>

Fix:
Delete the second entry.

**Comment by thomaspark** [comment]
Alerts in Paper display ok for me:

<img width="1163" alt="screen shot 2015-10-13 at 12 15 44 pm" src="https://cloud.githubusercontent.com/assets/900407/10460812/2b697a30-71a4-11e5-8df4-854fd50a786c.png">

Can you post a screenshot or demo of what you're seeing?

**Comment by cfblaeb** [comment]
I'm seeing a block of the correct color, but where the text is also that color.
Here is an example: https://jsfiddle.net/j4anfkwx/

**Comment by thomaspark** [comment]
Be sure to add both `alert` and `alert-info` classes, and you should be good to go.
