### ISSUE TITLE
table-bordered has no borders in lumen

### ISSUE THREAD

**Issue by tepez** [thomaspark/bootswatch#529]
Lumen [makes](https://github.com/thomaspark/bootswatch/blob/gh-pages/lumen/_bootswatch.scss#L201) (almost) all borders in a table transparent, so `table-bordered` doesn't work as expected:

![image](https://cloud.githubusercontent.com/assets/3265649/11169422/e6cd53f2-8bbf-11e5-9fae-3d631628d385.png)

Maybe re-apply the borders for table-bordered table?

**Comment by thomaspark** [comment]
Thanks!

**Comment by tepez** [comment]
Great. Thanks for the quick fix!
