### ISSUE TITLE
Lumen and Sandstone: font-size is constant for all button sizes

### ISSUE THREAD

**Issue by tepez** [thomaspark/bootswatch#530]
The font size of all buttons of all sizes is the same in these themes.

I've checked all other themes and it seems like they are the only ones with constant font-size so I assumed it might be a mistake.

If this is intentional, feel free to close the issue and I'll just override this in my own files.

![image](https://cloud.githubusercontent.com/assets/3265649/11301973/371af77e-8fa3-11e5-96b4-bc8f16cd09bf.png)
![image](https://cloud.githubusercontent.com/assets/3265649/11301986/45d3c48a-8fa3-11e5-809e-70fad201491b.png)

**Comment by thomaspark** [comment]
It is intentional for these themes to have the same font size. Thanks for the bug report anyhow!
