### ISSUE TITLE
Where am I supposed to include the _bootswatch.scss file?

### ISSUE THREAD

**Issue by ryanmortier** [thomaspark/bootswatch#531]
I realize I'm supposed to swap the `_variables.scss` file with the original bootstrap file. But where do I include the `_bootswatch.scss` file?

**Comment by thomaspark** [comment]
You want to include `_bootswatch.scss` at the end. One way is to reference them all kinda like it's done in `global/build.scss`.

**Comment by ryanmortier** [comment]
Great, thank you!

**Comment by marsman12019** [comment]
@thomaspark Include it at the end of what? I still find this incredibly unclear.

**Comment by thomaspark** [comment]
Did you take a look at `global/build.scss`? You'll want to create a new SASS file that has the following imports:

```
@import 'path_to_bootswatch/_variables.scss'
@import 'path_to_bootstrap/_bootstrap.scss'
@import 'path_to_bootswatch/_bootswatch.scss'
```

Compile your file to generate the theme.
