### ISSUE TITLE
Provide config.json for Bootstrap Customiser

### ISSUE THREAD

**Issue by ArktekniK** [thomaspark/bootswatch#532]
In order to customise themes found in Bootswatch easily, it would be very useful to have a config.json to load in to http://getbootstrap.com/customize/

Could these please be provided?
(Currently want to customise Superhero)

Thanks

**Comment by ArktekniK** [comment]
Just noticed issue #340.
I assume this is still a no, then?

**Comment by thomaspark** [comment]
Unfortunately it still isn't supported.
