### ISSUE TITLE
add outline in theme paper

### ISSUE THREAD

**Issue by ztvMark** [thomaspark/bootswatch#534]
can add outline in theme paper for buttom default?
      outline: none;
      outline-offset: none;

with bostrap and rails it looks ugly the border

@mixin btn($class,$bg){
  .btn-#{$class} {
    background-size: 200%;
    background-position: 50%;

```
&:focus {
  background-color: $bg;
  outline: none;
  outline-offset: none;
}

&:hover,
&:active:hover {
  background-color: darken($bg, 6%);
  outline: none;
  outline-offset: none;
}

&:active {
  background-color: darken($bg, 12%);
  @include gradient-radial(darken($bg, 12%) 10%, $bg 11%);
  background-size: 1000%;
  @include box-shadow(2px 2px 4px rgba(0,0,0,.4));
}
```

  }
}

**Comment by thomaspark** [comment]
I'm reluctant to remove outline because it can hurt accessibility. But it's pretty simple to override it with your own CSS. You can also use `<a>` instead of `<button>`, which doesn't have the outline.
