### ISSUE TITLE
Glyphicons broken in v3.3.6 on BootstrapCDN

### ISSUE THREAD

**Issue by goodsoft** [thomaspark/bootswatch#538]
When including CSS from https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/sandstone/bootstrap.min.css everything works fine and all icons are displayed correctly.
Changing URL to https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/sandstone/bootstrap.min.css shows generic "missing character" glyphs.

I noticed that woff2 file in 3.3.6 became two times larger than before.

**Comment by thomaspark** [comment]
Thanks, could you open an issue for this at https://github.com/MaxCDN/bootstrap-cdn/?

**Comment by goodsoft** [comment]
Closing this issue as the problem appears to be at MaxCDN's side.

**Comment by jdorfman** [comment]
apologies @thomaspark

**Comment by thomaspark** [comment]
Appreciate the quick fix, @jmervine @jdorfman!

**Comment by jdorfman** [comment]
=)
