### ISSUE TITLE
API alias broken

### ISSUE THREAD

**Issue by markcarver** [thomaspark/bootswatch#539]
http://api.bootswatch.com/3/ is no longer pointing to https://bootswatch.com/api/3.json

**Comment by thomaspark** [comment]
Unfortunately that alias went away with the end of AppFog's free tier. You should point directly to the other URL now: http://news.bootswatch.com/post/131219814698/changes-to-bootswatch-api

**Comment by markcarver** [comment]
That's unfortunate :(

Sorry for creating this issue, I don't follow your blog (even though I probably should). I've created a PR that links to that blog post so others are aware of it.

**Comment by thomaspark** [comment]
Thanks for the PR!
