### ISSUE TITLE
Some letters are being cutoff in headers with overflow hidden with many styles

### ISSUE THREAD

**Issue by lipis** [thomaspark/bootswatch#541]
Here is the example with Cerulean: https://jsfiddle.net/2juc773f/ (notice the `g`, `j`, etc)
<img width="420" alt="screen shot 2015-12-27 at 00 34 15" src="https://cloud.githubusercontent.com/assets/125676/12008279/b675aaaa-ac31-11e5-9929-15112966edfd.png">

**Comment by lipis** [comment]
http://githubstats.lip.is/thomaspark :dancer:

**Comment by thomaspark** [comment]
Thanks, I'll push a fix. Neat site by the way!

**Comment by lipis** [comment]
:+1:

**Comment by lipis** [comment]
will you make a new release?

**Comment by thomaspark** [comment]
Just tagged v3.6.6+1: https://github.com/thomaspark/bootswatch/releases

**Comment by lipis** [comment]
:+1: Also [Flatly](https://jsfiddle.net/2juc773f/1/), [Darkly](https://jsfiddle.net/2juc773f/2/) and possibly more have the same issue...

**Comment by thomaspark** [comment]
Also standard Bootstrap. Might be worth opening an issue upstream.

https://jsfiddle.net/2juc773f/7/

**Comment by lipis** [comment]
Didn't think of standard Bootstrap :) Will do..

**Comment by lipis** [comment]
https://github.com/twbs/bootstrap/issues/18714
