### ISSUE TITLE
Better colour choice for inverted navbar

### ISSUE THREAD

**Issue by afwd** [thomaspark/bootswatch#544]
Should approx. line 28 not include a colour choice for the hover state of the inverted navbar?

Putting the following inside `&-inverse {` would fix this.
```
.navbar-nav > li > a {
    border-right: 1px solid rgba(0, 0, 0, 0.2);
    border-left: 1px solid rgba(255, 255, 255, 0.1);
    
    &:hover {
      @include btn-shadow-inverse($navbar-inverse-bg);
    }
  }
```
This would correctly use the inverted colour to get the hover state, rather than the `navbar-default-bg`.

This makes the theme easier to customise.

**Comment by thomaspark** [comment]
Can you mention which theme this is for? Thanks.

**Comment by afwd** [comment]
Slate - appologies
