### ISSUE TITLE
Paper: Text on Anchor Buttons inside alerts are not visible

### ISSUE THREAD

**Issue by hurgleburgler** [thomaspark/bootswatch#552]
When using an anchor button (i.e. `<a class="btn btn-primary">Foobar</a>`) inside of an alert container, you cannot see the text on the button.

See here:
https://i.imgur.com/HQGefIh.png

This is due to Paper's special link styling inside alerts:
.alert a:not(.close), .alert .alert-link {
    color: #fff;
    font-weight: bold;
}

I believe if its changed from .alert a:not(.close) to .alert a:not(.close):not(.btn) this will fix the issue.

**Comment by thomaspark** [comment]
Thanks @hurgleburgler for the bug report!
