### ISSUE TITLE
.has-error is overwritten in superhero

### ISSUE THREAD

**Issue by muratsu** [thomaspark/bootswatch#554]
Instead of using $brand-danger color #d9534f, superhero theme is using the value #ebebeb which is previously declared. It's also possible to see multiple entries for .has-error in final css file.

screenshot:
![Imgur](http://i.imgur.com/Z5T9bhM.png)

**Comment by thomaspark** [comment]
Thanks for the report. Pushing a fix...

<img width="387" alt="screen shot 2016-03-11 at 5 19 15 pm" src="https://cloud.githubusercontent.com/assets/900407/13717146/94aad424-e7ad-11e5-85c8-349eb0048dfc.png">
