### ISSUE TITLE
All widgets of the theme Paper that have the &close; element are crased

### ISSUE THREAD

**Issue by Loyalsoldier** [thomaspark/bootswatch#555]
All widgets of the theme `Paper` that have the `&close;` are crased.

And I use `&times;` HTML entity instead. That's all right. I want to know if it's a bug or a mistake?

![_20160317104316](https://cloud.githubusercontent.com/assets/10487845/13834838/2228b37e-ec2d-11e5-87c6-9ca7e4c621f3.png)

The snapshot above is copied from Bootswatch website's theme `Paper` demo.

**Comment by thomaspark** [comment]
Thanks, you're right that it should be `&times;` instead. I'll push a fix for this now.
