### ISSUE TITLE
Paper: inputs with buttons not aligning properly in IE

### ISSUE THREAD

**Issue by michaldudak** [thomaspark/bootswatch#557]
An input grouped with button is not aligned properly - the bottom edge of the button is 1px lower than it should be:

IE11 (incorrect):
![image](https://cloud.githubusercontent.com/assets/4696105/14200224/a4cdb294-f7e9-11e5-8ce1-45b6443e374d.png)

Chrome (correct):
![image](https://cloud.githubusercontent.com/assets/4696105/14200232/b826789e-f7e9-11e5-8c77-b570b98fb69e.png)

**Comment by mika76** [comment]
I'd just add that it's not really great in Chrome either

Unfocused is ok I guess...
![unfocused](https://cloud.githubusercontent.com/assets/229311/23102695/5928b644-f6ae-11e6-9759-5ac0d9628777.PNG)

But focused looks bad...
![focused](https://cloud.githubusercontent.com/assets/229311/23102696/5b97db76-f6ae-11e6-95de-31a5105e976a.PNG)

**Comment by thomaspark** [comment]
Thanks for the bug report. So on IE the button's a pixel too low, on Chrome a pixel too high. 😖  I'll see what can be done about it.
