### ISSUE TITLE
Register your themes as bower packages

### ISSUE THREAD

**Issue by mbrig-co** [thomaspark/bootswatch#558]
For me it would be very helpful if you have registered you Bootstrap themes with custom and short names or tags for a quick and easy install, update and etc... through bower something like:
`bower install bw-bootstrap-flatly --save`
or
`bower install bs-bootswatch-flatly --save`
and the same for others, would be very preferred from my point of view.

Thanks in advance

**Comment by thomaspark** [comment]
Check out bootswatch-dist, sounds like it's exactly what you're looking for:

https://github.com/dbtek/bootswatch-dist

**Comment by mbrig-co** [comment]
Thanks, yes it is what exactly I was expecting.
