### ISSUE TITLE
check boxes and radio buttons are not working on firefox 

### ISSUE THREAD

**Issue by imadulhaque** [thomaspark/bootswatch#559]
Paper theme's check boxes and radio buttons are not working on firefox (i am using latest one). Any idea how can I get that working?

**Comment by thomaspark** [comment]
Unfortunately haven't been able to get the same effects working in Firefox. But it should at least fallback properly to the default check boxes and radio buttons.

If anyone can get it working, happy to accept a pull request!

**Comment by frassinier** [comment]
I've got a possible solution by using a additional `span` (and by using its pseudo-elements) with a fallback [right there](http://talend.surge.sh/theme/#forms). Does it could interest you?

**Comment by frassinier** [comment]
Feel free to reject (and close my PR) if is too far from Bootstrap markup

**Comment by thomaspark** [comment]
Hey @frassinier, I do want to get it working on Firefox but yes, trying to avoid additional markup on theme-specific basis. Cheers.

**Comment by frassinier** [comment]
:ok_hand: At least, if someone is interested, it's here.
