### ISSUE TITLE
Paper css file on bootswatch.com & maxcdn.bootstrapcdn.com/bootswatch/ do not match

### ISSUE THREAD

**Issue by coreybrett** [thomaspark/bootswatch#560]
These two files are not identical.

http://bootswatch.com/paper/bootstrap.css
https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/paper/bootstrap.css

The differences begin after line 7354.
I'm not sure which on is correct.

**Comment by thomaspark** [comment]
BootstrapCDN is likely a few commits behind, missing some small bug fixes. It should match v3.3.6 (not v3.3.6+1) here: https://github.com/thomaspark/bootswatch/releases
