### ISSUE TITLE
other resources for customized theme

### ISSUE THREAD

**Issue by coreybrett** [thomaspark/bootswatch#561]
After following the Customization instructions on https://bootswatch.com/help/, and rebuilding the Paper theme, I noticed all my Glyphicons were missing. What other directories in the tree aside from the customized theme's directory do I need to include in my project?

**Comment by thomaspark** [comment]
You'll also need Glyphicons installed at `/fonts/`, though you can change this by modifying `@icon-font-path` in `variables.less`.
