### ISSUE TITLE
icons are rolling over on buttons

### ISSUE THREAD

**Issue by imadulhaque** [thomaspark/bootswatch#563]
Hi,

My buttons have pngs images on them set from a png sprite and changing images based on positions on sprite. But images are changing with rolling effect on buttons. How can I remove this effect to just have images without any effect.

Thanks,
Imad.

**Comment by thomaspark** [comment]
Can you mention what theme you're using, and post a link to a live demo either on your site or somewhere like JSBin/JSFiddle?

**Comment by imadulhaque** [comment]
Sorry about that, I was using paper theme. But I fixed it by setting transition to none as follows:

    -moz-transition-property: none;
    -webkit-transition-property: none;
    -o-transition-property: none;
    transition-property: none;

**Comment by thomaspark** [comment]
Glad you worked it out. Thanks for the fix.
