### ISSUE TITLE
Yamm! mega menu links not visible on mobile using Bootswatch Paper inverted navigation bar

### ISSUE THREAD

**Issue by ghost** [thomaspark/bootswatch#566]
Desktop:

![cxgq4](https://cloud.githubusercontent.com/assets/19187213/15068037/73094752-136c-11e6-9cc4-50d2a5c40920.png)

Mobile:

![tpdtv](https://cloud.githubusercontent.com/assets/19187213/15068039/75eb2792-136c-11e6-921d-beecadb24fcc.jpg)

**Comment by alex-jch** [comment]
@thomaspark any idea?

**Comment by thomaspark** [comment]
Hi @alex-jch, can you post a link to the live version or a demo (on JSBin or JSFiddle)? Generally 3rd party libraries aren't supported but I'll take a look and fix it if it's straightforward.

**Comment by alex-jch** [comment]
@thomaspark sure. I'll get a demo sorted soon and post the link. At the moment I switched to `navbar-default` and the issue is sorted, so it just seems an issue with `navbar-inverse`.

**Comment by alex-jch** [comment]
@thomaspark hope this works https://jsfiddle.net/2yccgrby/

**Comment by wifiextender** [comment]
Have you tried adding the following to your `yum-content` class ?

```css
background-color: #FFF;
```

**Comment by thomaspark** [comment]
@wifiextender, thanks for the suggested fixes. The result looks very nice.

**Comment by alex-jch** [comment]
@wifiextender what site is that in the screenshot?

**Comment by thomaspark** [comment]
Closing as old issue. Feel free to re-open if there's issues with the latest version.
