### ISSUE TITLE
Menu Drop Down Indicator does on display on mobile

### ISSUE THREAD

**Issue by shyamramineni** [thomaspark/bootswatch#568]
![img_0652](https://cloud.githubusercontent.com/assets/703177/15125463/9207062c-164a-11e6-9d90-a34d01c76b4a.PNG)

I opened http://bootswatch.com/paper/ in my iPhone 5. The drop indicator does not the first time when I open the site in iPhone5. After that sometimes it opens and sometimes it does not.

Is this expected behaviour.

**Comment by thomaspark** [comment]
Just tried it in Safari on iPhone 6 but wasn't able to repeat it. Not sure why it shouldn't load the first time, since it uses CSS borders instead of web fonts to draw the caret.

Anybody else run into this?

**Comment by shyam541** [comment]
BTW I am using iphone 5, I will test it on Nexus 5 in the morning.

**Comment by shyam541** [comment]
This works fine in nexus 5.

**Comment by thomaspark** [comment]
Closing due to not able to replicate. Feel free to re-open if still an issue.
