### ISSUE TITLE
Small issue with bold text

### ISSUE THREAD

**Issue by pcmill** [thomaspark/bootswatch#571]
I use Sandstone as a theme for some of my projects. It seems that the bold text does not render properly. This is because an effect called faux-bold, as described [here](http://www.metaltoad.com/blog/how-use-font-face-avoid-faux-italic-and-bold-browser-styles). A consequence of this problem is wrong kerning, some of the letters seem to melt together. 

So instead of this:
![faux-bold](https://cloud.githubusercontent.com/assets/6996854/15857216/7c3206ae-2cba-11e6-95fc-fb59dc1c0077.JPG)

We should get this:
![faux-bold-solved](https://cloud.githubusercontent.com/assets/6996854/15857221/8402382c-2cba-11e6-9376-4bfbe8537131.JPG)

I simply replaced **font-weight: bold** with **font-family: "Roboto Black"** in this example.

**Comment by thomaspark** [comment]
Thanks for the bug report. What OS / browser are you seeing this on? I checked both Mac and Windows and it's rendering fine for me:

![sandstone](https://cloud.githubusercontent.com/assets/900407/15906560/66b8399c-2d87-11e6-865a-1f6f2c451ecf.png)

Also, Google Fonts does not provide Roboto Black (only Roboto, Roboto Condensed, and Roboto Slab), so unless you have it installed locally, it should be getting replaced by another font when you declare `font-family: "Roboto Black"`.

**Comment by pcmill** [comment]
I can reproduce this bug on Firefox 46.0.1 / Windows 7. I also tried it on Chrome, Internet Explorer and Opera where this problem is not noticeable. This [article](http://alistapart.com/article/say-no-to-faux-bold) says that Firefox does "smear" a font more, but that is assuming the font does not get loaded in. I do have the font installed locally.

I did notice you only load Roboto in weight 400 and 500. On the Google Fonts page itself they refer to bold as weight 700. Maybe that has something to do with it?

**Comment by thomaspark** [comment]
Tried it on Firefox 47 / Windows 8, and didn't get the blur. FYI I don't have the font installed locally.
![capture](https://cloud.githubusercontent.com/assets/900407/15953105/14417f84-2e95-11e6-89f5-e89a63eabe4d.PNG)

Could you try the following things and see if the blur goes away for either case?
* Change `b {font-weight: strong;}` to `b {font-weight: 500;}`
* Edit the theme to load Roboto at 700 as well

**Comment by pcmill** [comment]
Both of the solutions worked in my case to get the bold text to render properly. Probably loading Roboto at 700 is a good idea so you don't have to rely on the interpretation of Firefox to much.

**Comment by thomaspark** [comment]
Done!
