### ISSUE TITLE
Separate remote fonts into their own less file?

### ISSUE THREAD

**Issue by inklesspen** [thomaspark/bootswatch#573]
I'm using bootswatch (as installed via npm) in my Electron app. It's very unfortunate for a desktop app to rely on loading fonts from a remote server, so I downloaded the fonts and have them locally. However, the Paper less files are still loading Roboto from Google Fonts.

I think the web-font rules should be moved into a separate fonts.less which can be used or not used depending on the dev's needs.

**Comment by thomaspark** [comment]
You should be able to change the value of `@web-font-path` and point it to a local copy. #507 has some info on this. Let me know if this works for you.

**Comment by inklesspen** [comment]
This does work, however since my copy of the roboto css is stored inline with my app, it ends up looking like this:

```
@import "~bootstrap/less/bootstrap.less";
@import "~bootswatch/paper/variables.less";
@import "~bootswatch/paper/bootswatch.less";
// This needs to navigate back from node_modules/bootswatch/paper to the app dir
@web-font-path: "./../../../app/roboto/fonts.css";
```


It would be nice if instead I could set `@web-font-path` to `donotinclude` and a guard inside the bootswatch css would not use the import in that case, so I could have this:

```
@import "./roboto/fonts.css";
@import "~bootstrap/less/bootstrap.less";
@import "~bootswatch/paper/variables.less";
@import "~bootswatch/paper/bootswatch.less";
@web-font-path: "donotinclude";
```

**Comment by jareware** [comment]
I'd also want this! A really simple solution should be changing

    $web-font-path: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" !default;
    @import url($web-font-path);

to

    $web-font-path: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" !default;
    @if $web-font-path {
        @import url($web-font-path);
    }

Due to the `!default` flag, you'd be able to just set

    $web-font-path: false;

before including the Paper theme.

Would you be open to a PR with this, @thomaspark ?

**Comment by thomaspark** [comment]
Definitely would be open to a PR on this.

One thing to watch out for is how it works in SASS. Currently we have to jump through hoops to get the LESS font import code working in SASS (with `grunt convert_less`) which you can see here: https://github.com/thomaspark/bootswatch/blob/gh-pages/Gruntfile.js#L233-L240

**Comment by jareware** [comment]
I have no problem implementing this in SASS, but assuming we also want to support the same thing in LESS (and them having no equivalent to !default [by choice](http://lesscss.org/features/#variables-feature-default-variables)), what's the cleanest way to do it?

    @emit-web-font: true when (not(@web-font-path = false));
    @web-font-path: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700";
    
    .web-font(@path) when (@emit-web-font) {
      @import url("@{path}");
    }
    .web-font(@web-font-path);

isn't valid LESS.

**Comment by petersmax** [comment]
Hello,

I completely understand this but why does it give an error 
```
variable @path is undefined on line 9 in file '_bootswatch.less':
  [8]: .web-font(@path) {
  [9]:   @import url("@{path}");
       --------------^
 [10]: }
```

**Comment by alex-sherwin** [comment]
I found a pretty decent solution to this scenario, when you already have a locally hosted copy of the font (i.e. Roboto etc) and don't want to bootswatch import to take place at all, this is what I did in SASS

```sass
$web-font-path: 'data:text/css;base64,';
@import '~bootswatch/paper/bootswatch';
```

So bootswatch's import turns into a `@import url([empty data url])` and never makes a real network request, and causes no warnings etc (has simply imported an inline blank stylesheet)

**Comment by schmunk42** [comment]
This worked for me "somehow":

```
@path: @web-font-path;
```
