### ISSUE TITLE
Chrome Canary Paper radio buttons not working

### ISSUE THREAD

**Issue by mikedidomizio** [thomaspark/bootswatch#578]
Just a heads up.
Possibly related to #559.  Tested with `Version 54.0.2787.0 canary (64-bit)`.

Buttons are unclickable

**Comment by mikedidomizio** [comment]
Upon further inspection, value changes but UI does not reflect the value change

**Comment by thomaspark** [comment]
Looks like the transition rule on :before/:after pseudoelements is killing the re-render. Removing the transitions gets it working again. Bug in Canary?

**Comment by mikedidomizio** [comment]
Yes, seems to be some bugs possibly being introduced in Canary.  For example, (although unrelated) even on [https://design.google.com/](url) they have some text wrapping issues with V54

**Comment by mikedidomizio** [comment]
@thomaspark This issue seems to be resolved in `Version 54.0.2796.2` of Canary.
