### ISSUE TITLE
Different colors for btn-link? (Paper theme). 

### ISSUE THREAD

**Issue by xinghengwang** [thomaspark/bootswatch#579]
Is it possible to have different colors for btn-link? 
I see that btn-link is to the way to do flat buttons, but I want to change the color, but can't. 
What is the best way to do so? 

Thanks

**Comment by thomaspark** [comment]
This is possible, but you will have to set a custom `btn-link` color in your own CSS stylesheet or in `bootswatch.less`.

**Comment by xinghengwang** [comment]
ok, I'll take a look.
