### ISSUE TITLE
Headers font too large in Cyborg theme

### ISSUE THREAD

**Issue by awalin** [thomaspark/bootswatch#580]
Hi Thomas,
we use Bootswatch and I would like to thank you for the library. Recently we found several discrepancy in using the Cyborg theme. The text are too big compared to other themes, so it can cause layout issue, which is happening in our case. 

Awalin Sopan

**Comment by awalin** [comment]
<img width="1214" alt="screen shot 2016-07-12 at 9 46 22 am" src="https://cloud.githubusercontent.com/assets/1120199/16777883/702e4eae-4839-11e6-8b5d-09a238aa5dd1.png">
<img width="1286" alt="screen shot 2016-07-12 at 9 46 37 am" src="https://cloud.githubusercontent.com/assets/1120199/16777885/704c98aa-4839-11e6-8600-32d03315a968.png">

side by side comparison of darkly and cyborg themes

**Comment by thomaspark** [comment]
Thanks for opening this issue.

Cyborg (and Paper) are based on Google design guidelines that favor large headers. I'd like to follow these guidelines and keep the themes as is, but it should be straightforward to override their styles to suit your preference.
