### ISSUE TITLE
Scroll bars formatted for light pages on Cyborg

### ISSUE THREAD

**Issue by rurabe** [thomaspark/bootswatch#582]
Possibly related to #484 ?

https://jsfiddle.net/3Ljkh5u1/

I also noticed that the _bootswatch.scss is v3.3.5 and _variables.scss is v3.3.6? Not sure if that is related either

This is my current workaround to approximate what it should be, but only webkit:

```css
.element
  height: 100%
  overflow-y: scroll

  &::-webkit-scrollbar 
    background-color: inherit
    width: 8px
  &::-webkit-scrollbar-thumb
    background-color: rgba(255,255,255,0.3)
    border-radius: 10px
```

**Comment by thomaspark** [comment]
Thanks. Can you post a screenshot of how scrollbars look and what OS you're on?

**Comment by rurabe** [comment]
Weird, it looks fine now. Must have been weirdness with chrome or something. The scrollbar was light gray and had a white track, which was very contrasty on the black background. OSX 10.11.5, Chrome 51. Not seeing it anymore though. Sorry!
