### ISSUE TITLE
Nav collapse issue in Readable theme

### ISSUE THREAD

**Issue by sevagh** [thomaspark/bootswatch#584]
Hello - I'm not great at CSS so I'm having trouble debugging this. I use Readable here: http://sevag.io/index.html

The nav collapse hamburger menu doesn't appear on mobile or when I make the desktop window too small. It used to work with the default bootstrap2 theme, and I haven't changed the HTML part.

Any ideas on what changed? The HTML can be seen here (starting line 51): https://github.com/sevagh/custom-bootstrap2/blob/master/templates/base.html

**Comment by thomaspark** [comment]
It looks like the Bootstrap and Readable versions you're using are out of sync. Specifically `bootstrap-responsive.min.css` has some rules that aren't taking effect on the navbar button like they're supposed to.

I'd make sure to update Bootstrap to the latest (v2.3.2 in your case). That includes `bootstrap-responsive.min.css` and `bootstrap.min.js`.

**Comment by sevagh** [comment]
That worked, thanks.
