### ISSUE TITLE
[Paper] Background greys practically invisible on TN panel monitors

### ISSUE THREAD

**Issue by kspeakman** [thomaspark/bootswatch#585]
The background greys on Jumbotron, Well, and to a lesser extent Panel header/footer are practically invisible on your average office monitor. I suggest that background shades be at brightest #f0f0f0.

In a similar vein, the Popover arrow is nearly invisible with a CSS border opacity of 0.075. I suggest 0.15 or so. It does pronounce the joint between the arrow and the popover a little, but worth the trade-off IMO. With the arrow currently being essentially invisible, the popover looks awkward.

**Comment by thomaspark** [comment]
Do you mind posting some screenshots and what OS/browser you're on?

Those colors are quite subtle but still clear for me. But I'm on Mac with retina display.

<img width="355" alt="screen shot 2016-08-05 at 2 02 05 pm" src="https://cloud.githubusercontent.com/assets/900407/17446003/4fe2ce42-5b15-11e6-9df5-bf4faa793c71.png">

**Comment by kspeakman** [comment]
I don't think a screen shot will show anything, because the monitor rendering will still vary. I'll try a cell phone picture.

**Comment by kspeakman** [comment]
I have two monitors, and it looks the same on both. So I thought maybe it's just that my monitors are inferior (which they may be) and I checked the Paper theme on a few more around the office. It seems to be an epidemic. The Well background particularly was invisible on all the ones I looked at. You a couple of them you could almost see the default panel header background... almost.

My eye level is an inch or so from the top of the monitor (lower than is considered ergonomic), so that's the level I took the pictures. If I lower my eye level to the bottom of the monitor, the well backgrounds are clearly visible. I had a similar experience on the other monitors I checked.

![paper well](https://cloud.githubusercontent.com/assets/4582668/17447032/ea074c5e-5b11-11e6-82cb-b295e81efe3d.jpg)

I tested some changes (via Chrome dev tools) to the rendered CSS to come up with the values I listed in the issue.

![paper popover](https://cloud.githubusercontent.com/assets/4582668/17447038/f1bad2ae-5b11-11e6-8d6f-d7d352fb91f3.jpg)

The borders in this picture look worse than in person, but the arrows are similarly imperceptible without visibly searching for them.

**Comment by kspeakman** [comment]
Oh yes, Windows 10 / Chrome 51

**Comment by thomaspark** [comment]
Thanks for the photos, they were helpful. I'm bumping up contrast on the well and jumbotron backgrounds and popover arrow based on your suggestions.

**Comment by kspeakman** [comment]
Awesome, thanks!
