### ISSUE TITLE
Flatly theme - bootstrap.min.js version doesn't seem to work.

### ISSUE THREAD

**Issue by yogeshk19** [thomaspark/bootswatch#590]
I am trying to use the Flatly theme and I downloaded the bootstrap.min.js and have included the stylesheet in my html page and doesn't change the theme, stays with the original bootstrap theme. However if use the non-minified version of this theme, which I downloaded from the bootswatch site as well and the theme changes works as expected. Any reason why the minified version wouldn't work?

Thanks,
Yogesh

**Comment by daN4cat** [comment]
The theme comes with bootstrap.min.css, not min.js.

We use Flatfly and all bootswatch themes in https://github.com/jekkos/opensourcepos/ and they all work fine.
Bootstrap.min.js comes from the official bootstrap release.

**Comment by yogeshk19** [comment]
Thanks I accidentally wrote min.js. However referencing that file still doesn't work for me. I am using the spacelab theme now instead and that works as expected. Thanks for your response.
