### ISSUE TITLE
[Spacelab] Panel title color inheritance

### ISSUE THREAD

**Issue by kamil7x** [thomaspark/bootswatch#601]
Here is the example:
https://jsfiddle.net/79amp4ea/

When I am trying to use nested panels, and parent has class panel-primary, child's panel-title inherits text color, because of CSS rule: 
```
.panel-primary .panel-title {
    color: #fff;
}
```

I am using CSS from CDN, so I would like to get it fixed.

**Comment by thomaspark** [comment]
Hey @kamil7x, it looks like this is an upstream issue with Bootstrap, as they didn't account for the use case of nested panels. See: https://jsfiddle.net/tc2hf763/

It looks like you can work around this though by adding a small bit of CSS: https://jsfiddle.net/7ypcvLuo/

```
.panel .panel-warning .panel-title {
  color: inherit;
}
```
