### ISSUE TITLE
[v4 materia] radio-inline broken layout

### ISSUE THREAD

**Issue by jipexu** [thomaspark/bootswatch#607]
we have a problem please see this :

https://jsfiddle.net/jipexu/trq4v83y/

**Comment by thomaspark** [comment]
Hi @jipexu, with Bootstrap v4 we must add a [`form-check-inline`](https://v4-alpha.getbootstrap.com/components/forms/#inline) class instead of `radio-inline`. Then it should work ok. 

https://jsfiddle.net/jwus7ksf/

**Comment by jipexu** [comment]
@thomaspark sure it's work ! thanks ! i missed this ...
