### ISSUE TITLE
[V4 cyborg] source code color in the modal same as the modal background

### ISSUE THREAD

**Issue by jipexu** [thomaspark/bootswatch#609]
Hi !
[V4 cyborg]
http://bootswatch.com/4-alpha/cyborg/
The color of the source code in the modal is the same that the modal-content background color .."# 222"

and also in [V4 slate] a little bit better ...

so can not see the source code ..
Thanks

**Comment by thomaspark** [comment]
Currently Bootstrap v4 has a `$pre-bg` variable that's not being used (https://github.com/twbs/bootstrap/issues/18623). Will have to wait and see what happens with it. But I'll add a rule to make pre's usable on dark themes for time being.
