### ISSUE TITLE
Solarized themes (Dark, Light)

### ISSUE THREAD

**Issue by lipis** [thomaspark/bootswatch#612]
I know it's a very classic color theme but still it would be nice to have them nicely polished.

http://ethanschoonover.com/solarized

- [ ] ~~Solarized Light~~
- [ ] Solarized Dark

**Comment by mika76** [comment]
This would be amazing!

**Comment by thomaspark** [comment]
Personally I'm a fan of Monokai but I will look into it. 😀

**Comment by georgekis** [comment]
This is definitely for me! 👍

**Comment by thomaspark** [comment]
Guys, don't think Solarized Light will work well as a general theme, but I've made a dark version called Solar. You can check it out on the `v4` branch!

![thumbnail](https://cloud.githubusercontent.com/assets/900407/21660484/86f03a32-d29d-11e6-87f0-36a11f339c91.png)

**Comment by lipis** [comment]
That looks neat.. but you won't have it for the Bootstrap 3?! :(

**Comment by thomaspark** [comment]
Once it's finalized, I'll see about porting it to v3. 😃

**Comment by mika76** [comment]
Could you update it on the online site please 😁

**Comment by thomaspark** [comment]
Done! https://bootswatch.com/4-alpha/solar/

**Comment by lipis** [comment]
Great stuff! Thanks... now it should be easier to port it to 3.. :)

**Comment by lipis** [comment]
No stress or anything.. just curious about this state.. will it make it to v3?

**Comment by thomaspark** [comment]
Hey @lipis, gonna port Solarized to v3 hopefully by the end of this week!

**Comment by lipis** [comment]
That's awesome man.. thank you!

**Comment by lipis** [comment]
woho!! and now the release to get it via the package manager :)

**Comment by topless** [comment]
Splendit work my friend :)
