### ISSUE TITLE
Flexbox only V4

### ISSUE THREAD

**Issue by IamManchanda** [thomaspark/bootswatch#618]
As bootstrap v4 is now flexbox only, 
request you to make bootswatch 4 the same 

( https://github.com/twbs/bootstrap/issues/20939 )

**Comment by thomaspark** [comment]
Ah, the cost of developing on top of an alpha. This was a change made in v4 alpha 6, which I will update to soon.

**Comment by jipexu** [comment]
oh cool this will be soon the v4 alpha 6 milestone is more than 90%

**Comment by IamManchanda** [comment]
95% now ... expect it within this week or two .... or simply clone to see the flex magic now @thomaspark @jipexu 

One more thing that i would like to address,
No Gutters - https://github.com/twbs/bootstrap/issues/19107 https://github.com/twbs/bootstrap/pull/21211

**Comment by IamManchanda** [comment]
Should i close this now @thomaspark ?

**Comment by thomaspark** [comment]
Yes, feel free to close this @IamManchanda.

**Comment by IamManchanda** [comment]
closing this @thomaspark sir ..... but i will come back again at the time of beta  

For eg: https://github.com/twbs/bootstrap/pull/21741 :stuck_out_tongue_closed_eyes:
