### ISSUE TITLE
Link to bootstrap v4 versions from bootswatch site

### ISSUE THREAD

**Issue by dessalines** [thomaspark/bootswatch#619]
I had some trouble finding the bootstrap v4 beta versions, I had no idea you'd been converting a lot of them. It'd be a really good idea to link to the v4 site from https://bootswatch.com/, maybe in the navbar or something. 

http://bootswatch.com/4-alpha/

**Comment by thomaspark** [comment]
Hey @dessalines, thanks for the suggestion. Right now v4 is in alpha so still undergoing lots of changes but as soon as it hits beta, I'm going to switch the main site over to it and have an alert that links to v3.

**Comment by IamManchanda** [comment]
@thomaspark Alpha 6 is the last major alpha release.

So i think , there should be linking of Mr. Alpha after alpha 6 is released

**Comment by jplaverdure** [comment]
Hello !
It seems bootstrap v4 has hit beta (Huzzah!)
I tried using the sass files associated with the v4 and sass complains with the following error:
Error: (x: 0, y: 0) isn't a valid CSS value.
    on line 146 of spacelab/_variables.scss

Any pointers ?

**Comment by ceesco53** [comment]
I think a new issue should be opened for visibility but you could try changing the sass map causing the error.

`$spacers: (
        0: (
                        ("x", 0),
                        ("y", 0)
        ),
        1: (
                        ("x", $spacer-x * .25),
                        ("y", $spacer-y * .25)
        ),`

and so on.  Problem is though whatever references the sass map would also need to be changed but it really wouldn't be too painful since each theme has the same spacer code in it.

**Comment by jplaverdure** [comment]
@ceesco53 Thanks for the suggestion.
Actually, just replacing the $spacers declaration with the new one solved it for me as there are already assignments of $spacer to $spacer-x and $spacer-y so the other variables you mention still work OK (at least on Spacelab, haven't checked the other swatches).
But you're right that some classes have changed names and slight updates are in order (navbar comes to  mind).

**Comment by tamtakoe** [comment]
@thomaspark Bootstrap is beta already, but Bootswatch still uses alpha

**Comment by thomaspark** [comment]
Bootswatch is on v4 beta now.
