### ISSUE TITLE
api.json is in .npmignore

### ISSUE THREAD

**Issue by robcresswell** [thomaspark/bootswatch#620]
It'd be rather nice if the API folder could be removed from the .npmignore. It's helpful to be able to use this data (descriptions, paths etc) for automated builds with gulp/webpack etc.

My particular use case is building a demo site with code examples and bootswatch themes for v4.

**Comment by thomaspark** [comment]
I can see how this is useful. I've made the change to npmignore, which should take effect on npm with the next version bump.

**Comment by robcresswell** [comment]
That's awesome news, thanks so much. Saves me duplicating it for appropriate linking and crediting :)
