### ISSUE TITLE
BS4 checkbox

### ISSUE THREAD

**Issue by julmot** [thomaspark/bootswatch#622]
I'm having troubles with at least the "Spacelab" theme. I'm embedding it like described in the docs:

```css
@import "bootswatch/spacelab/variables";
@import "bootstrap/scss/bootstrap";
@import "bootswatch/spacelab/bootswatch";
```

The output will be:

![example-checkbox](https://cloud.githubusercontent.com/assets/8310677/21730767/7ec224be-d451-11e6-9651-b16267fff867.png)

The checkmark is missing (you can only see the blue background). Furthermore [the example](http://bootswatch.com/4-alpha/spacelab/) shows something completely different:

![checkbox](https://cloud.githubusercontent.com/assets/8310677/21730832/d22e858e-d451-11e6-950a-71d06c23cc5a.png)

This is how it should look like and how it looks like without Bootswatch (default BS4):

![checkbox-no-bootswatch](https://cloud.githubusercontent.com/assets/8310677/21730925/493bf8b4-d452-11e6-8b1d-e5f4625152c0.png)

**Comment by jgog** [comment]
hey @julmot 

Checkboxes and Radio buttons are not styled by Bootstrap or Bootswatch, they are rendered by the browser with default styles.

This is how Spacelab looks for me:

<img width="280" alt="screen shot 2017-01-06 at 5 22 26 pm" src="https://cloud.githubusercontent.com/assets/971411/21735039/b6e256a6-d434-11e6-8755-08dab4725c8c.png">

**Comment by julmot** [comment]
> Checkboxes and Radio buttons are not styled by Bootstrap or Bootswatch, they are rendered by the browser with default styles.

I can't confirm this. As mentioned, my last screenshot above is using BS4 and it looks different to the second screenshot which shows my native checkbox. This appears due to the "custom" classes available in BS4. According to the "Migrating to v4" article:

> Added custom forms support (for checkboxes, radios, selects, and file inputs).

Have a look at [the documentation](https://v4-alpha.getbootstrap.com/components/forms/#custom-forms).

**Comment by thomaspark** [comment]
Hey @julmot, what OS/browser are you on?

Can you test some of the other themes and see if the same thing happens as Spacelab?

**Comment by julmot** [comment]
@thomaspark I've tested spacelab, flatly, sandstone and cerulean: same behavior.

**Comment by thomaspark** [comment]
I tested on 52.0a2 (Mac) and can't repeat the plain checkbox:

<img width="524" alt="screen shot 2017-01-12 at 12 43 50 pm" src="https://cloud.githubusercontent.com/assets/900407/21901295/1e4f2816-d8c5-11e6-8213-d432783f9180.png">

**Comment by jgog** [comment]
@julmot ok my bad, the v4 Bootswatch themes aren't updated to the new checkbox styles.
