### ISSUE TITLE
npm install --save-dev Bootswatch? EOM

### ISSUE THREAD

**Issue by QuantumInformation** [thomaspark/bootswatch#625]

**Comment by QuantumInformation** [comment]
Why not include the npm install to the installation guide?

**Comment by maxkoryukov** [comment]
I don't insist, but I think, maintainers will appreciate a PR for this ;)

**Comment by thomaspark** [comment]
Instructions for adding Bootswatch to your own project? Agree it would be nice to have commands for npm and other package managers as seen here: https://github.com/twbs/bootstrap/#quick-start
