### ISSUE TITLE
Superhero theme: Form input-groups within panels have same color background as panel-default

### ISSUE THREAD

**Issue by South-Paw** [thomaspark/bootswatch#627]
When you place an `input-group` within a `panel-default` on the Superhero theme, the input group's background is the same color as the panel background - where as on other themes there is contrast between the two.

Nothing major, just something I noticed.

Superhero;
![image](https://cloud.githubusercontent.com/assets/2154764/22409672/ae7db03e-e6f2-11e6-9f2e-79bd835822a6.png)

Darkly;
![image](https://cloud.githubusercontent.com/assets/2154764/22409698/0cb6f7fa-e6f3-11e6-9e82-22c9ea710588.png)

Slate;
![image](https://cloud.githubusercontent.com/assets/2154764/22409705/1facf7e2-e6f3-11e6-8e95-e47fcc02a78e.png)

To reproduce;

```html
<div class="panel panel-default" style="overflow: hidden; padding: 15px">
    <form class="form-horizontal">
        <div class="form-group" style="margin-right: 0; margin-left: 0;">
            <label class="sr-only" for="username">Username</label>
            <div class="input-group">
                <div class="input-group-addon"><i class="fa fa-fw fa-user"></i></div>
                <input type="text" class="form-control" id="username" placeholder="Username">
            </div>
        </div>
        <div class="form-group" style="margin-right: 0; margin-left: 0;">
            <label class="sr-only" for="password">Password</label>
            <div class="input-group">
                <div class="input-group-addon"><i class="fa fa-fw fa-lock"></i></div>
                <input type="password" class="form-control" id="password" placeholder="Password">
            </div>
        </div>
        <button type="button" class="btn btn-primary pull-right">Sign In</button>
    </form>
</div>
```

Cheers

**Comment by thomaspark** [comment]
Hey @South-Paw, thanks, I will lighten the wells and default panels a touch to give some contrast.

**Comment by South-Paw** [comment]
Thanks mate 👍
