### ISSUE TITLE
Cosmo Segoe UI Font

### ISSUE THREAD

**Issue by scottkuhl** [thomaspark/bootswatch#634]
The Cosmo theme currently uses Source Sans Pro as the first font option.  It seems like it would be more appropriate to use Seqoe UI as the initial option to match what the Microsoft Design Language (formerly Metro) is using.

Thoughts?

**Comment by thomaspark** [comment]
Segoe UI with Source Sans Pro as a fallback would be ideal.

But I'm hesitant to use Segoe UI as primary since I have no way of developing/testing the theme with it, whereas Google Fonts are freely available.

**Comment by scottkuhl** [comment]
Isn't Segoe UI being used in the base bootstrap 4 now as part of the native fonts initiative?

If you would like I could make the change and create a pull request.  The other option might be to use Selawik, an open source font Microsoft created for just this scenario.

**Comment by thomaspark** [comment]
A pull request would be great. Can you do Segoe UI as the first value in the font stack, and fall back to Source as the second? Hopefully nothing gets too wonky when Segoe is available..

**Comment by scottkuhl** [comment]
Changes are in [PR 635](https://github.com/thomaspark/bootswatch/pull/635)

[Screenshots](https://1drv.ms/b/s!ADldz3axExKxpewQ) running under Edge on Windows 10.

**Comment by thomaspark** [comment]
Hey Scott, many thanks for the PR, and including the screenshots. Merged #635.
