### ISSUE TITLE
No documentation about custom.min.css?

### ISSUE THREAD

**Issue by ybakos** [thomaspark/bootswatch#636]
Is _css/custom.min.css_ just the bootswatch project's css styles for presenting each theme, or are these styles a necessary part of using a particular theme?

When experimenting with a bootswatch example index.html and a particular theme, mine never look the same as the examples, until I manually copy _custom.min.css_ and link to it.

See also https://github.com/mkhairi/bootswatch-sass/issues/2.

**Comment by thomaspark** [comment]
Hey @ybakos, `custom.min.css` isn't part of the themes — it's just some additional styling for bootswatch.com. You won't need/want to include it if you're using a Bootswatch theme as you would use Bootstrap.

**Comment by ybakos** [comment]
@thomaspark I think I get it now. Thanks!
