### ISSUE TITLE
Compiling-error sonar

### ISSUE THREAD

**Issue by Marktwert** [thomaspark/bootswatch#637]
Hi,
I get a compiling error by using the sonar .less I use it for jul-shop. The message is the following. What did i wring? (i just copied the variables.less into the folder...

variable @navbar-border-dotted is undefined in file /kunden/134930_96317/rp-hosting/2016006/2016006/testshop/templates/Evo-Child-Example/themes/mytheme/less/theme.less in theme.less on line 103, column 18 101| list-style: none; 102| font-size: @font-size-small; 103| border-bottom: @navbar-border-dotted; 104| background-color: transparent; 105| 106| > li {

**Comment by thomaspark** [comment]
Does the error go away when you remove the theme or replace it with standard Bootstrap? `@navbar-border-dotted` isn't used in the theme, so I suspect it's an issue with your theme's styles.
