### ISSUE TITLE
Paper theme doesn't work with disabled controls

### ISSUE THREAD

**Issue by jkurei** [thomaspark/bootswatch#638]
When using the Paper theme, disabled controls show as enabled, not signaling in any way their disabled state.

This is how they look when disabled (the same as enabled):

<img width="259" alt="screen shot 2017-03-07 at 19 13 16" src="https://cloud.githubusercontent.com/assets/1428611/23671061/33f14ddc-036a-11e7-9558-758cd8cf4080.png">

**Comment by thomaspark** [comment]
Thanks for the bug report, nice catch. Pushing a fix for this now.

Active:
<img width="452" alt="screen shot 2017-03-10 at 2 42 39 pm" src="https://cloud.githubusercontent.com/assets/900407/23810496/e8af3d74-059f-11e7-9116-8ea9118af923.png">

Disabled:
<img width="455" alt="screen shot 2017-03-10 at 2 42 48 pm" src="https://cloud.githubusercontent.com/assets/900407/23810505/ec5ed380-059f-11e7-8c93-f0f2591cbfe6.png">
