### ISSUE TITLE
Release v4 Alpha on npm

### ISSUE THREAD

**Issue by xeoneux** [thomaspark/bootswatch#639]
Hi @thomaspark 
Could you release the npm packages for the latest alpha versions for Bootstrap 4?

**Comment by h3adache** [comment]
+1
For now I'm doing:
`yarn add https://github.com/thomaspark/bootswatch#v4`

**Comment by ridhoq** [comment]
+1
Or for npm:
`npm install thomaspark/bootswatch#v4 --save`
