### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by Jezreep** [thomaspark/bootswatch#647]
How can I run my button to popup Modal? Like this http://bit.ly/2npZbAr
I'm using http://bootswatch.com/superhero/ ♥

**Comment by Jezreep** [comment]
![image](https://cloud.githubusercontent.com/assets/17799361/24577843/653128ac-1708-11e7-9a5d-27a232e2b6ee.png)

**Comment by thomaspark** [comment]
You'll want to include Bootstrap's [`bootstrap.js`](http://getbootstrap.com/getting-started/#download) file on your page, then follow the directions here: http://getbootstrap.com/javascript/#modals

**Comment by Jezreep** [comment]
@thomaspark Thank you!

**Comment by Jezreep** [comment]
@thomaspark Thank you!
