### ISSUE TITLE
UI bug when filtering table to one row only (Chrome full screen only)

### ISSUE THREAD

**Issue by nywhere** [thomaspark/bootswatch#648]
Hi!,

I am using the paper theme and have a table like that:

![image](https://cloud.githubusercontent.com/assets/4170685/25006045/b4bacbe2-205b-11e7-85e5-9970a1a764b2.png)

If I filter the table and it returns only one row I have the following behavior. Other rows are still visible, there's also this black block appearing.

![image](https://cloud.githubusercontent.com/assets/4170685/25006110/eb905100-205b-11e7-8bf9-9cc8f1bee1c3.png)

If I resize or refresh the black block disappear, the extra rows as well and all is fine.

It appears only on Chrome when Chrome is opened full screen.

**Comment by thomaspark** [comment]
Hi, can you post a link to a live demo? Will be extremely helpful in diagnosing it.

**Comment by nywhere** [comment]
Possible. However I came back at my place and tried on my Mac and it works. So:

Chrome on Windows 10 / 1920x1080 = bug
Chrome Mac-El Capitan / 1440x900 = ok

So I guess we can reproduce the bug only in a specific environment. Do you have a Windows 10 + HD screen available?

**Comment by thomaspark** [comment]
I have Win 8 which might reproduce it, or someone else with that setup might also be able to test it.
