### ISSUE TITLE
Superhero scss not working

### ISSUE THREAD

**Issue by marceloverdijk** [thomaspark/bootswatch#649]
The superhero scss variant seems not to be working.

Using: 

```
@import "bootswatch/superhero/variables";
@import "bootstrap-3.3.7/bootstrap";
@import "bootswatch/superhero/bootswatch";
```

in a Jekyll powered site gives:

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting '/assets/css/site.scss':
                    Undefined variable: "$gray-light". on line 7
```

Other themes like solar are working without a problem.

Probably it's related to the variables in `superhero/_variables.scss`.

`$well-bg:` is define at line 764: `$well-bg:                     lighten($gray-light, 3%) !default;`
but already used at line 706: `$panel-bg:                    $well-bg !default;`

**Comment by thomaspark** [comment]
Just pushed a fix for it, can you confirm it fixes the error?

**Comment by marceloverdijk** [comment]
Yes it works! Thx!
