### ISSUE TITLE
what's the function of the first line of bootstrap.min.css? can we remove it,

### ISSUE THREAD

**Issue by herozeng** [thomaspark/bootswatch#654]
@import url("https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700");/*!

Sometimes we cannot connect outside network/or some country cannot use google,it will block a few seconds.

**Comment by jipexu** [comment]
yes you can remove and you will only not have the lib font ...

**Comment by herozeng** [comment]
thank for you response, another question is license, it is  Licensed under MIT,does it allow us to modify the source code for commercial use,I am consider to remove this line.

**Comment by thomaspark** [comment]
Yes, you can modify it and use it commercially.
