### ISSUE TITLE
[V4] whats about this ?

### ISSUE THREAD

**Issue by jipexu** [thomaspark/bootswatch#655]
https://github.com/twbs/bootstrap/pull/22551

any more problem ?

**Comment by thomaspark** [comment]
Good news, looks like that change is being rolled back a bit:

https://github.com/twbs/bootstrap/pull/22836

**Comment by jipexu** [comment]
yes !!

**Comment by mdo** [comment]
@thomaspark Let me know what you think of that PR. Looking to spend a bit of time on it this weekend.

**Comment by thomaspark** [comment]
@mdo, looks like a good solution that adds flexibility & maintainability on our end. Will play around with it for our themes and get back to you.

**Comment by jipexu** [comment]
@mdo yes really a very good way  ! thanks
