### ISSUE TITLE
Incompatible units: 'rem' and 'px'.

### ISSUE THREAD

**Issue by rafalradomski** [thomaspark/bootswatch#658]
I using Laravel 5.4 & webpack and:
    "bootstrap": "^4.0.0-alpha.6",
    "bootswatch": "^3.3.7"

When I trying to import flatly I getting error:

```php
// bootswatch template - Flatly
@import "node_modules/bootswatch/flatly/variables";

// Bootstrap
@import "node_modules/bootstrap/scss/variables";

// Bootstrap
@import "node_modules/bootstrap/dist/css/bootstrap";

// bootswatch template  - Flatly
@import "node_modules/bootswatch/flatly/bootswatch";
```

```php
 Incompatible units: 'rem' and 'px'.
      in D:\xampp2\htdocs\streetdeals\node_modules\bootstrap\scss\_variables.scss (line 444, column 34)
```

**Comment by thomaspark** [comment]
It looks like you're mixing Bootstrap v4 with Bootswatch v3. Can you try using the same major versions?

Bootswatch v4 isn't released yet but you can access the files you need here: https://github.com/thomaspark/bootswatch/tree/v4

**Comment by ScorpioCoding** [comment]
got bootstrap 4 and bootswatch 4 and I still get the error

**Comment by ScorpioCoding** [comment]
Sorry  my bad ... was using bootstrap-sass typical symfony
