### ISSUE TITLE
.text-muted is the same color as the .panel-body element

### ISSUE THREAD

**Issue by WardsParadox** [thomaspark/bootswatch#659]
I noticed this was mentioned in #306 that the body and text-muted classes are the same when they aren't but I did notice that the .text-muted class and the .panel-body class have the same rendered colors in the Superhero theme. I noticed that text-muted has #4e5d6c as the color where panel-body has #546575. I think that they are two close or are being misrendered in chrome (v58). The project is not using any overridees. Here is a gif showing the text-muted applied and then removed.
![image](https://cloud.githubusercontent.com/assets/8117192/25820646/40280432-33ef-11e7-9e65-07087edae415.png)

**Comment by thomaspark** [comment]
Pushing a fix for this. Thanks for the report!

**Comment by WardsParadox** [comment]
No problem, thanks for the fix 👍
