### ISSUE TITLE
How to prevent bootswatch modal from closing when clicking outside the modal dialog box ?

### ISSUE THREAD

**Issue by bill-goldberg** [thomaspark/bootswatch#661]

**Comment by thomaspark** [comment]
Modals work exactly the same in Bootswatch themes as they do the Bootstrap framework, so you can follow the instructions here:

http://stackoverflow.com/questions/22207377/disable-click-outside-of-bootstrap-model-area-to-close-modal

http://stackoverflow.com/questions/22207377/disable-click-outside-of-bootstrap-model-area-to-close-modal
