### ISSUE TITLE
About progress bars in each theme

### ISSUE THREAD

**Issue by karlos1113** [thomaspark/bootswatch#664]
Hello,
I am designing a small pages in my school by using bootswatch and others and I think bootswatch themes are really easy to use and helpful for me.
However, while I am using 'progress bar' in each theme, I think it can be better if this bar can support 'mouse over text'. What I meant to say is hover text feature. For example, showing text like "60%" for 60% progress bar when a cursor is hovering over a progress bar.. Can it be more readable?
Is there any reason why you didn't put this feature in the progress bar?

And is it possible to contribute to bootswatch using jquery or angular.js for a specific feature?

**Comment by thomaspark** [comment]
Hi @karlos1113, it is possible to do this by combining Bootstrap's progress bar and tooltip features:
http://getbootstrap.com/javascript/#tooltips

Here's a demo of it in action:
https://codepen.io/valencia123/pen/aOopQx

It should be no different with Bootswatch themes as it is with standard Bootstrap.
