### ISSUE TITLE
[V4] has-error should be has-danger

### ISSUE THREAD

**Issue by Brandhor** [thomaspark/bootswatch#666]
has-error has been renamed to has-danger in bootstrap v4

**Comment by thomaspark** [comment]
The v4 preview should have it switched over to `has-danger`. Are there any I missed?

https://bootswatch.com/4-alpha/

**Comment by Brandhor** [comment]
yeah materia, I assumed it was a problem with all the themes but it's just that one, the others are fine

**Comment by thomaspark** [comment]
Ah, thanks.
