### ISSUE TITLE
Allow pre-loading variables for Bootstrap 4 Flatly 

### ISSUE THREAD

**Issue by jortkoopmans** [thomaspark/bootswatch#667]
When trying to pre-load certain variables, such as a different color scheme, in some cases the Flatly styling will override this. The use case is custom styling on top of Flatly.

Example:
$brand-primary:             #2C3E50;
in file 4-alpha/flatly/_variables.scss

Reason: many of the variables do not use the '!default' flag.

All the bootstrap 3 styling seem to have this, as well as the default bootstrap 4 styling.
My guess is this just needs to be fixed, there should be no visible change for the end-users when this flag is added to all vars.
Can the pre-loading of variables be allowed, in order to permit easy customization of flatly?

**Comment by thomaspark** [comment]
Hey @jortkoopmans, thanks, this is a change I've been meaning to get around to.

But for the time being, I've been using the removal of `!default` flags as a way of tracking which variables have been changed from default Bootstrap. Eventually, once the themes (and Bootstrap v4) are stabilized, I was planning to add those flags and remove the unmodified ones.

What if we instead added the `!default` flags as you've done in #668 but also commented each changed line to indicated it's been modified. Would you be able to do this in your PR?

**Comment by jortkoopmans** [comment]
Hello @thomaspark, certainly! I've updated it now, does this match what you're looking for?

**Comment by thomaspark** [comment]
Hey @jortkoopmans, that's looking pretty good but don't wanna mess with the line numbers. Could you just append a comment like `// bootswatch` at the end of each line instead of adding a new line for the comment?

**Comment by jortkoopmans** [comment]
Hello @thomaspark, fair point on the line numbers, I've modified it now. Third time is a charm?

**Comment by thomaspark** [comment]
Looks good, thanks @jortkoopmans! Hopefully gets the vars working for you as you want.
