### ISSUE TITLE
the Bootstrap 4 version isn't available for bower install

### ISSUE THREAD

**Issue by SingingBush** [thomaspark/bootswatch#669]
any chance of a release for the Bootswatch themes that work with Bootstrap v4.0.0-alpha.6

**Comment by jipexu** [comment]
there is ..

**Comment by jipexu** [comment]
and will be probably another when when the 4 beta  will be available ....

**Comment by SingingBush** [comment]
I see the branch for it but no [tagged release](https://github.com/thomaspark/bootswatch/releases) and when I try to install with bower by adding `"bootswatch": "^4.0.0"` to my bower.json I get:

```
Available versions in https://github.com/thomaspark/bootswatch.git: 3.3.7, 3.3.6+2, 3.3.6, 3.3.6+1, 3.3.5+3, 3.3.5+2, 3.3.5+4, 3.3.5, 3.3.5+1, 3.3.4+1, 3.3.4, 3.3.2, 3.3.1+3, 3.3.1+2, 3.3.1+1, 3.3.1, 3.3.0, 3.2.0+4, 3.2.0+3, 3.2.0+2, 3.2.0+1, 3.2.0, 3.1.1+1, 3.1.1, 3.1.0, 3.1.0+1, 3.0.3+1, 3.0.3, 3.0.2+1, 3.0.2, 3.0.2+2, 3.0.1, 3.0.0, 3.0.0-rc2, 3.0.0-rc1, 2.3.2, 2.3.1+1, 2.3.1, 2.3.0+2, 2.3.0+1, 2.3.0, 2.2.2+2, 2.2.2+1, 2.2.2, 2.1.1+1, 2.1.1, 2.1.0, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0
```

I should've mentioned bower in title. will rename issue

**Comment by jipexu** [comment]
ah ok

**Comment by thomaspark** [comment]
Just tagged v4.0.0-alpha.6.

**Comment by SingingBush** [comment]
awesome, thanks
