### ISSUE TITLE
select boxes are unreadable

### ISSUE THREAD

**Issue by questsin** [thomaspark/bootswatch#671]
select boxes are unreadable in some themes like darkly, slate, superhero. Mainly do to the fontcolor being to close to the background color of the selectbox

**Comment by thomaspark** [comment]
Can you tell me what operating system and browser you're on, and post a screenshot? Thanks.

**Comment by questsin** [comment]
Looks like it only affect Chrome and not Safari on my Mac OS Sierra
v10,12,5.

[image: Inline image 2][image: Inline image 1]

**Comment by jipexu** [comment]
i have not this behavior with the same config ..??
Mac OS Sierra
v10,12,5. 
chrome Version 58.0.3029.110 (64-bit)

or i miss something ?...

**Comment by thomaspark** [comment]
I'm not able to replicate it either, on same Sierra + Chrome. Any browser extensions you have installed that might be interfering?

**Comment by questsin** [comment]
I boot in incognito mode in chrome and still have same problem :(

**Comment by questsin** [comment]
darkly and superhero are the worst.

**Comment by thomaspark** [comment]
@questin, still having this problem on the latest v4?
