### ISSUE TITLE
custom.js necessary for swatch?

### ISSUE THREAD

**Issue by N6REJ** [thomaspark/bootswatch#672]
I'm working on creating a "article" that will demonstrate the bootstrap styling.. 
I notice it loads custom.js  Is this really needed if full BS3 & theme is loaded?
I want to create a page similar but with more examples to http://getbootstrap.com/examples/theme/
If it matters it will be a joomla 3 article

**Comment by thomaspark** [comment]
Hi @N6REJ. No, custom.js is not needed at all. It just adds some functionality that's specific to bootswatch.com, like the navbar transparency effect and clicking the code button on a Bootstrap element to view source.
