### ISSUE TITLE
Conditionally Import External Font?

### ISSUE THREAD

**Issue by chay22** [thomaspark/bootswatch#675]
I caught myself feel more suitable to separate external css rather than importing them. Below is one of the kind of what I'm here talking about.

```
$web-font-path: "https://fonts.googleapis.com/css?family=Lato:400,700,400italic" !default;
@import url($web-font-path);
```
Is there any way to turn this off, either conditionally or not, so I can use HTML feature such as `dns-prefetch`, `prerender` or the like?

**Comment by thomaspark** [comment]
Hi @chay22, does the solution mentioned by @alex-sherwin here work for you?

https://github.com/thomaspark/bootswatch/issues/573

**Comment by chay22** [comment]
@thomaspark It works perfectly as described on the latest reply. Thanks! And sorry for not digging such issue beforehand. Since it's a workaround, anyway, do you have any plans in the future to fix this? You don't have to answer it.

Cheers and thank you once again!

**Comment by thomaspark** [comment]
@chay22, awesome. Once we switch to sass only for v4, it should simplify things so we can have a more elegant solution.
