### ISSUE TITLE
[Simplex theme] Radio button groups don't look properly.

### ISSUE THREAD

**Issue by hallazzang** [thomaspark/bootswatch#677]
I've been working with Bootswatch Simplex theme for several hours, and faced into a problem.

The problem is, when I try to make a radio button group, buttons don't look properly.
Here's the sample code that reproduces the problem:
http://jsfiddle.net/pwxbdbc4/1/ (worked inside of the sandbox)

```html
<h1>Simplex Button Group</h1>
<div>
  <div class="btn-group btn-group-justified" data-toggle="buttons">
    <label class="btn btn-default">
      <input type="radio" name="rating"> A
    </label>
    <label class="btn btn-default">
      <input type="radio" name="rating"> B
    </label>
    <label class="btn btn-default">
      <input type="radio" name="rating"> C
    </label>
  </div>
</div>
```

As you can see, when a click performed on a button, the graphic of the button doesn't change immediately. After moving mouse out from the button then it changes.

I'm a css(or less or sass things) noob, I can't fix it by my hand. Hope you can fix this problem, thanks.

**Comment by jipexu** [comment]
is it the same as here ?
https://github.com/twbs/bootstrap/issues/23069#issuecomment-318126573

**Comment by hallazzang** [comment]
@jipexu Um.. I think it's slightly different(If I understood the problem in that issue correctly).

Detailed problem explanation:
1. Click on the radio button. (And keep the mouse's position)
2. The button still looks 'unchecked'
3. After moving mouse out of the button, then it looks 'checked'

**Comment by thomaspark** [comment]
Seems to be because same bg style is being applied to .btn and .btn:hover. This should do the trick.
