### ISSUE TITLE
Problem with Firefox and Safari browsers 

### ISSUE THREAD

**Issue by BenSaud-CS** [thomaspark/bootswatch#679]
The theme is not working on the Firefox and Safari browsers nicely as Chrome as well! 

Best regards [M. Saud](https://twitter.com/BenSaud_CS)

**Comment by thomaspark** [comment]
@BenSaud-CS, thanks for the bug report. Which theme are you referring to? It is the form elements that are different? There will be some unavoidable differences due to differences in browser support.

**Comment by BenSaud-CS** [comment]
**Theme name** is Yeti. 
**The problem in Firefox browser:** the errors validation it doesn't appear.
**The problem in Safari browser:** the navbar doesn't look like Chrome browser and the lists are so bad.

Best regards[ M. Saud](https://twitter.com/BenSaud_CS/)

**Comment by thomaspark** [comment]
That shouldn't happen. Can you post screenshots?

**Comment by BenSaud-CS** [comment]
**This is in Safari browser** ( navbar, it should look like Chrome browser - second screenshot)
 
<img width="430" alt="screen shot 1438-11-10 at 9 38 48 pm" src="https://user-images.githubusercontent.com/13363000/28889006-4bf7ac66-77cb-11e7-8a35-21f63c435ebd.png">

<img width="294" alt="screen shot 1438-11-10 at 9 42 23 pm" src="https://user-images.githubusercontent.com/13363000/28889101-9fef6c00-77cb-11e7-9f13-c77865fcb1b5.png">

**About the problem in Firefox browser:** when I submit the form and that have a required the errors of the validation it doesn't appear to the end user and show the message!

**Comment by thomaspark** [comment]
Hmmm can you try using regular Bootstrap or a different theme and see if the problem goes away?

Also, do you have a link to a demo? That would be really helpful in figuring out the problem. I'm wondering if at least the navbar issue is RTL related.

**Comment by BenSaud-CS** [comment]
**About using regular Bootstrap:** it is working fine👍
**About the link of the demo:**  Unfortunately, No I don't have it's is a local and private project.
**About navbar issue is RTL related**: I commented the RTL bootstrap and the problem with Safari is still there!

**Comment by jipexu** [comment]
so perhaps make a little fiddle with your navbar and your html context ... ? it will be more easy ... to find
