### ISSUE TITLE
Update with new bootstrap beta version

### ISSUE THREAD

**Issue by JunkyDeLuxe** [thomaspark/bootswatch#682]
Hello,

There is actually a new bootstrap 4 release (beta one). 
Materia doesn't compile correctly anymore.

Strange because there is no breaking change displayed on release patch.

I am using bootswatch with bootstrap sass, webpack and sass-loader.
For the moment I just keep the last alpha bootstrap 4 version on my package.json

**Comment by jipexu** [comment]
?.. there is a lot of breaking change between alpha 6 and beta ... class name, variable .... no ?

**Comment by JunkyDeLuxe** [comment]
Perhaps, didn't see in detail

**Comment by nenadvicentic** [comment]
Yes, bootswatch 4-alpha themes are pretty much broken when used with Bootstrap 4 beta sass files.

**Comment by rogerlopz** [comment]
Is there a roadmap or a discussion about updating the themes to the beta? I want to get involved.

**Comment by jipexu** [comment]
"we" can (poor thomas) start but we have to care that it is already some change in the next beta ...

**Comment by Herst** [comment]
I guess one of the major reasons why quite a lot of changes are needed is twbs/bootstrap#22836

**Comment by thomaspark** [comment]
Hey guys, hoping to update to beta as soon as I get the chance. Check this issue for general v4 discussion and update on beta: https://github.com/thomaspark/bootswatch/issues/499#issuecomment-325455786

**Comment by sadikoff** [comment]
Hi all, any news on update to v4-beta?

**Comment by owenstrevor** [comment]
Can't wait for this to update to beta. FYI, beta 2 just came out with some breaking changes and beta 3 has some breaking changes already planned.

**Comment by thomaspark** [comment]
Yup, beta 2 is on its way this week. Will close this in favor of #499.

**Comment by beeman** [comment]
Thanks for your work on this @thomaspark! It's highly appreciated!
