### ISSUE TITLE
_bootswatch.scss file not compiling?

### ISSUE THREAD

**Issue by mweiczorek** [thomaspark/bootswatch#683]
The _bootswatch.scss file is not compiling for me - only the first lines:

    $web-font-path: "https://fonts.googleapis.com/css?family=Lato:400,500,700,400italic" !default;
    @import url($web-font-path);

Nothing below that gets compiled into my main css file. I noticed because the Navbar doesn't look right (the navbar-default class is not found in generated CSS).

It is the last import in the main scss file. It's a valid file because it does import the web font.

Using Darkly

**Comment by ideacco** [comment]
I also appeared on this issue, who successfully compiled it?

**Comment by thomaspark** [comment]
Are you guys trying to use it with the Bootstrap v4 beta? Themes haven't been updated from alpha yet and won't be compatible.

**Comment by mweiczorek** [comment]
Yes. But how would this affect the actual compilation? If the SASS is valid, it should compile regardless of version. Of course, I'm a Java developer so I'm a bit behind with the whole front-end ecosystem.

**Comment by thomaspark** [comment]
The Bootswatch SASS depends on certain variables and mixins provided by Bootstrap:

```
@import "bootswatch/theme/variables";
@import "bootstrap/scss/bootstrap";
@import "bootswatch/theme/bootswatch";
```

Between the alpha and beta, some of the expected variables and mixins may not be defined.
