### ISSUE TITLE
glyphicons-halflings-regular.woff2 Err_Aborted issue in ASP.Net MVC 5

### ISSUE THREAD

**Issue by tnayanam** [thomaspark/bootswatch#684]
When I switch the theme from Standard to Lumen I start getting error in chrome dev tool as "glyphicons-halflings-regular.woff2 Err_Aborted" in ASP.Net MVC 5 project. However, if I switch back to Standard Bootstrap theme, error goes away.

 ```
bundles.Add(new StyleBundle("~/Content/css").Include(
                      //"~/Content/bootstrap.css",
                      "~/Content/bootstrap-lumen.css",
                      "~/Content/superslides.css",
                      "~/Content/site.css"));
        }
```

 
![image](https://user-images.githubusercontent.com/17131576/31051276-701230ea-a632-11e7-81ad-c6827690f115.png)

![image](https://user-images.githubusercontent.com/17131576/31051312-18140066-a633-11e7-875c-36c1609c72a4.png)

**Comment by thomaspark** [comment]
Not sure why it's only happening with Lumen, but it seems like a server issue with woff file types? Can you let me know if this fixed it?

https://stackoverflow.com/questions/46508793/how-to-solve-glyphicons-halflings-regular-woff2-err-aborted-issue-in-asp-net-mvc
https://stackoverflow.com/questions/32300578/how-to-remove-error-about-glyphicons-halflings-regular-woff2-not-found

**Comment by tnayanam** [comment]
I only had asked that question on SO. and it fixed my issue. Thanks for your response.

**Comment by thomaspark** [comment]
Glad it got fixed!
