### ISSUE TITLE
Question: How I can integrate font awesome?

### ISSUE THREAD

**Issue by zer09** [thomaspark/bootswatch#687]
Hello good day, 

I am using bootswatch litera, so far it is working well on an electron test app. Then I want to use font-awesome but I don't know how. I tried looking way how to integrate it but so far the best I can find is the [StackOverflow thread](https://stackoverflow.com/questions/32612690/bootstrap-4-glyphicons-migration/33768443#33768443), but it is little vague for me.

Any advice how I can do it.
thanks.

**Comment by thomaspark** [comment]
Hi there, if you simply wanna use Font Awesome on your app, you can follow the "Using CSS" instructions [here](http://fontawesome.io/get-started/). Bootstrap should play just fine with it.

**Comment by zer09** [comment]
ohh thanks, I'll try.
