### ISSUE TITLE
limit the height of dropdown menu in index.html

### ISSUE THREAD

**Issue by jipexu** [thomaspark/bootswatch#694]
Hi
i use since long time ... because when the menu have to much item  the dropdown (themes) is to height ...and you can not select... so it will be good to add a support for this ?

so add a class scrollable-menu

`<ul class="dropdown-menu scrollable-menu" role="menu">`

and some style where we want put ...

`         .scrollable-menu {
           height: auto;
           max-height: 350px;
           overflow-x: hidden;
         }
         .scrollable-menu::-webkit-scrollbar {
           -webkit-appearance: none;
           width: 6px;
         }
         .scrollable-menu::-webkit-scrollbar-thumb {
           border-radius: 4px;
           background-color: lightgray;
           -webkit-box-shadow: 0 0 1px rgba(255,255,255,.75);
         }
`

**Comment by thomaspark** [comment]
Hey @jipexu, great point, on certain themes the menu items goes way off-screen. Scrollable seems like a good solution, or perhaps making it multi-column might reduce the mouse movement to get to the end of the list.

**Comment by jipexu** [comment]
hi @thomaspark  yep also for the 2 column (if we have enough width space on the smaller media ?)
