### ISSUE TITLE
Simplex Navbar (collapse) bug and fix.

### ISSUE THREAD

**Issue by khenrix** [thomaspark/bootswatch#700]
Hi,
I was using simplex bootstrap theme for bootstrap 4 and encountered a bug.
Not sure if i'm using it wrong but found a fix that works for me.

The problem:
The navbar closes as soon as i open (toggle) the button.
It shows for a half a second and then closes, without doing anything.

I fixed it by changing the following:

`.collapse.show{
  display: block;
}`

to

`.collapse.in {
  display: block;
}`

Might be something worth checking.

Best regards / Christoffer

**Comment by jipexu** [comment]
Hi
with BS 4 .collapse .in doesnt exist any more .. 
.collapse .show is correct
so you have to change the html not the css ...

**Comment by khenrix** [comment]
My bad, my bootstrap version reverted to 3.
Sorry about that.
