### ISSUE TITLE
css points to v4 version now

### ISSUE THREAD

**Issue by Brandhor** [thomaspark/bootswatch#702]
maybe I was wrong to use it in the first place but I used http://bootswatch.com/cerulean/bootstrap.min.css on my site and today it changed to bootstrap v4, I imagine that other people used these unversioned urls as well so I think it might be better if they would still point to the v3 and use https://bootswatch.com/4/cerulean/bootstrap.min.css for v4

**Comment by jipexu** [comment]
HI
probably is not the best way to link directly (is not a cdn ...) and as thomas has choose to switch to 4 seems to me good thing ..

**Comment by lightdot** [comment]
There's no maybe about it, it was wrong. If you want to link your .js or .css assets from an outside source, you should use a service that is designed for it, like a public CDN.

It's quite possible that you're the only one, as hotlinking like this is certainly not the norm when programming, quite the opposite. But even if you aren't, asking for a file to remain in place is simply wrong. Just fix your code, learn from it and move on...

**Comment by Brandhor** [comment]
ok then how about adding a link to the cdn in the dropdown menu in each theme page? I think that way other people wouldn't make my mistake

**Comment by alcalyn** [comment]
I did the same error !

**Comment by thomaspark** [comment]
If you wanna hotlink, [BootstrapCDN](https://www.bootstrapcdn.com/bootswatch/) is definitely the recommendation. Adding the cdn links is a good idea.

I'm also working on reorganizing the repo to clean things up and so there won't be breaking changes like this. `/dist/` will have the latest themes, while `/docs/` will have the website with versions organized under `/docs/3/`, `/docs/4/`, etc...

**Comment by thomaspark** [comment]
Repo's been reorganized and cleaned up: https://github.com/thomaspark/bootswatch
