### ISSUE TITLE
Radio buttons in Firefox

### ISSUE THREAD

**Issue by Atnode** [thomaspark/bootswatch#705]
Hello,
With Firefox 58.0a1 (2017-11-02), I have this problem:
![image](https://user-images.githubusercontent.com/28532899/32375390-b077371e-c0a1-11e7-90c1-4bffabe74c78.png)
Thank you very much for all the work you have done.

**Comment by thomaspark** [comment]
@Atnode, thanks for the bug report, fix on the way.
