### ISSUE TITLE
[Slate theme] Collapsed navbar looks weird

### ISSUE THREAD

**Issue by juampi** [thomaspark/bootswatch#706]
From the Slate theme preview page:

V3:
<img width="380" alt="screen shot 2017-11-03 at 11 39 35" src="https://user-images.githubusercontent.com/748094/32379340-0a203042-c08c-11e7-95a6-36c2e073590f.png">

V4:
<img width="380" alt="screen shot 2017-11-03 at 11 40 06" src="https://user-images.githubusercontent.com/748094/32379355-17ef5996-c08c-11e7-89f8-7fdaa1ef8ac5.png">

By the way, thanks for your hard work updating everything @thomaspark ! I already have the new V4 Slate theme in production and it looks awesome.

**Comment by thomaspark** [comment]
Hey @juampi, should be much improved now!
