### ISSUE TITLE
All theme urls are now broken!!

### ISSUE THREAD

**Issue by stevenbraham** [thomaspark/bootswatch#707]
Because you have moved the old bootstrap 3 themes into /3/ on your website, all the old theme URLs are now giving a 404. 

I'm sure that I'm not the only one currently experiencing this problem. Could you restore the old theme URLs or create a redirect to the new theme URLs?

**Comment by thomaspark** [comment]
Hi @stevenbraham,

The url structure was changed, which should make them more stable going forward.

v3: https://bootswatch.com/3/cosmo/bootstrap.css
v4: https://bootswatch.com/4/cosmo/bootstrap.css

Although if you want to hotlink, you should use BootstrapCDN for that: https://www.bootstrapcdn.com/bootswatch/

An api is also available to always point you to the right urls: https://bootswatch.com/help/#api
