### ISSUE TITLE
[V4B2] .bg-primary background-color problem in Superhero theme

### ISSUE THREAD

**Issue by Nelda4** [thomaspark/bootswatch#708]
Hi,

I've faced with the issue in the Superhero theme for 4.0.0-beta.2: .bg-primary background-color is defined twice, seems that prefered #DF691A is overridden to #4E5D6C by mistake.

P.S. Thanks for the big effort you've done to update all the themes for beta 2)

**Comment by thomaspark** [comment]
Thanks @Nelda4, small oversight on my part. Fix is incoming.
