### ISSUE TITLE
Messy page at first. Becuase of importing google font at top.

### ISSUE THREAD

**Issue by metemaddar** [thomaspark/bootswatch#711]
In my Internet connection which is not very fast, it takes time to load Google font CSS file.
So the page becomes messy at very first moment. When I commented Google font css file at top, It solved.

**Comment by thomaspark** [comment]
Hey @metemaddar, that's unfortunately a tradeoff of using web fonts, especially with slower connections. But if you'd like to comment them out, the theme should continue to work just fine.
