### ISSUE TITLE
Flatly theme: fix colors menu-entries and modal close button

### ISSUE THREAD

**Issue by jortkoopmans** [thomaspark/bootswatch#714]
Hello Thomas,

There's a few problems with the colors on the Flatly theme:
- Active menu entry ('Home') is broken for Navbar bg-primary
- Active menu entry ('Home') is broken for Navbar bg-dark
- Hover/Focus of menu entries is broken for Navbar bg-dark
- Modal close button color is broken (white on white background)

I've got a pull request you can consider as a fix.
#713

**Comment by thomaspark** [comment]
Hey @jortkoopmans, your PR is great, I'll merge it and rebuild.

**Comment by jortkoopmans** [comment]
Hello Thomas, thanks so much for your quick response and merge. Happy to contribute!
Of course I should have checked the Darkly theme directly as well, since it has the same problem.
New pull request for same fix for Darkly: #716

**Comment by thomaspark** [comment]
Thanks, Darkly is fixed now!
