### ISSUE TITLE
Feature Request: gulp version

### ISSUE THREAD

**Issue by ftred001** [thomaspark/bootswatch#715]
Hey,

first of all I really love your themes!

But have you ever considered creating a gulp version? grunt is kinda not state of the art anymore.

Keep up the good work! 👍

**Comment by thomaspark** [comment]
Hey @ftred001, thanks for the kind words and the suggestion. Agree that gulp is nice. If there comes a time to do a major overhaul or add a bunch of new tasks, I'll consider switching to it. But for now, the tasks are working and there isn't much benefit to rewriting them. Of course I'm open to a pull request for it!
