### ISSUE TITLE
Switch font-sizing from px to rem as our primary CSS unit.

### ISSUE THREAD

**Issue by andrewi** [thomaspark/bootswatch#727]
Bootstrap 4 made a global change: "Switched from px to rem as our primary CSS unit". It allows a better scaling of the application layout. I think bootswatch should consider to do the same. At the moment there are themes that use "px" units and it somewhat restrict web-accessibility options. Unless this is a thought through theme feature.

**Comment by thomaspark** [comment]
Thanks for opening an issue on this, do want to switch everything over to `em` when I get the chance.

If there are any especially egregious problems caused by using `px`, please post here and I'll make them a priority.

**Comment by andrewi** [comment]
I've noticed the problem using "Litera" theme, where menu keeps the same font size disregarding browser's font size setting change. 
It does not applies to all themes though. Superhero seems to be updated and behaves well.

**Comment by pltxtra** [comment]
This issue also affects for example radio buttons in the Materia theme. They look very off on Firefox for example. I tried changing some of the units from for example 18px to 1.5em and then it looks fine and dandy.

**Comment by andrewi** [comment]
Thank you for the fast fix for Litera!

**Comment by thomaspark** [comment]
@andrewi, no problem, thanks for opening the issue.

@pltxtra, does it look better now that font sizes have been switched to `em`? The checkboxes themselves don't scale but the spacing should be better.

**Comment by pltxtra** [comment]
@thomaspark From your patch I can see no changes to the Materia theme. Maybe I should raise a separate issue for that? Basically what I see under certain circumstances (developer version of Firefox and latest IE 11) is that the radio buttons look bad - the graphics is not properly centered.

**Comment by thomaspark** [comment]
@pltxtra, can you post a screenshot of how they look on your end? Looks pretty good to me on Firefox.

**Comment by pltxtra** [comment]
![bootswatch-radio-ff](https://user-images.githubusercontent.com/5207962/33474088-52646834-d679-11e7-8bdb-1b565459f26e.png)
![bootswatch-radio-ie](https://user-images.githubusercontent.com/5207962/33474093-5808f930-d679-11e7-826d-b89ebf3ae442.png)

**Comment by thomaspark** [comment]
@pltxtra, what font size do you have your browser set at? I wasn't able to replicate on a few different sizes for FirefoxDev.

**Comment by pltxtra** [comment]
@thomaspark I've tried multiple settings, same effect. Note that I am trying on the demo-page that you have setup, not using the latest git version.

Slightly off-topic - how often do you update NPM? The version there is quite different from git.

**Comment by thomaspark** [comment]
@pltxtra, odd, I tested the latest Firefox on Windows and it looks pixel perfect. IE11 looks similar to your screenshot though.

I'll tend to tag a new version whenever Bootstrap gets updated to a new version too.
