### ISSUE TITLE
Lux navbar item issue

### ISSUE THREAD

**Issue by XhmikosR** [thomaspark/bootswatch#737]
There's a selector `.navbar-nav .nav-item + .nav-item` which doesn't take into account a dropdown item.

See for example https://www.bootstrapcdn.com/?theme=8: the resources nav item doesn't have any `margin-left`.

**Comment by thomaspark** [comment]
It looks like you can fix it by adding a `.nav-item` class to the `.dropdown` as shown in the examples on Bootstrap docs here: http://getbootstrap.com/docs/4.0/components/navbar/#supported-content

**Comment by XhmikosR** [comment]
Hmm, indeed, I thought I had but apparently I didn't.

Thanks for the reply you can close the issue :)

**Comment by thomaspark** [comment]
Glad the issue is resolved!
