### ISSUE TITLE
use gh-pages / jekyll for bootswatch docs

### ISSUE THREAD

**Issue by m5o** [thomaspark/bootswatch#756]
Hey @thomaspark 

There is a lot of content in this repository which repeats for each theme…

I've recently discovered [bulmaswatch](https://github.com/jenil/bulmaswatch) they are heavily inspired by bootswatch themes 
and translate themes to be used with the [Bulma CSS framework](https://bulma.io).

Their Repository is really really well structured. Wonderful work done by @jenil 👏 
What do you think to also use [Github Pages](https://pages.github.com) for building the docs and kind-of be inspired/clone the structure used by the folks at bulmaswatch?

##### Ups, there was already a discussion:
🔗 https://github.com/thomaspark/bootswatch/issues/623

**Comment by jenil** [comment]
Hey @m5o thanks! I think we should continue the conversation in #623
