### ISSUE TITLE
4.0.0-beta2 does not build in Angular 5 project styles.scss

### ISSUE THREAD

**Issue by king612** [thomaspark/bootswatch#757]
I am trying to use a Bootswatch theme in an Angular 5 project.  I am using both Bootswatch and Bootstrap versions 4.0.0-beta-2.  I have installed both via npm and have imported the _variables.scss and _bootswatch.scss in my styles.scss using the usual angular-cli/webpack conventions in my main styles.scss.  I also import the relevant theme bootstrap.min.css into this file, and I add it to the styles[] array in angular.cli.json.

During build I get:

    @include box-shadow(none);
            ^
         No mixin named box-shadow

and a broken build.

I have followed the directions at the bootswatch NPM site, which are not accurate on the "@import" statements, which should read:

"@import "../node_modules/bootswatch/dist/theme/_vairables.scss""

etc.

**Comment by thomaspark** [comment]
If you want to use the themes as-is without modification, just import `bootstrap.min.css`. You don't need the scss files.

If you do want to customize a theme further, go with scss in which the `css` file isn't needed anymore. Just make sure you're also including the main bootstrap scss file.

**Comment by king612** [comment]
Thank you for the quick response.  Appreciate it very much.

I don't need to customize it, but just dropping in the bootstrap css is not working.  This is an angular app, using webpack, but even just statically referencing it in the <head> section of the index.html doesn't work either.  The CSS is included, but no colors, the cursor turns to an I-beam over a nav item, just very basic things not working.

This is on a disconnected system (so, no, I can't post the code) - is the theme trying to pull stuff from a CDN in the background?  This app will have no internet connection - is that a dealbreaker for bootswatch?  Or if it is, is there a workaround?

**Comment by king612** [comment]
I think I figured it out - I had to tweak some of my class names for ver. 4.x, add a href="" to the anchor tags, etc.  Thanks again for your help though.
