### ISSUE TITLE
Adopt nuclear theme

### ISSUE THREAD

**Issue by m5o** [thomaspark/bootswatch#758]
Nuclear is a [user contributed](https://github.com/jenil/bulmaswatch/pull/22) theme from @fenwick67 to [bulmaswatch](https://github.com/jenil/bulmaswatch)
Since Bulmaswatch is originally inspired by Bootswatch, 
this new theme is now missed in the origin repository. 

Would you accept a PR adding the nuclear theme to bootswatch?
Maybe, @fenwick67 the original author will volunteer 😉 , otherwise let's see

🎨 Nuclear Demo: https://jenil.github.io/bulmaswatch/nuclear/

**Comment by jipexu** [comment]
look like Stabilo .. i like +1

**Comment by thomaspark** [comment]
Hey @m5o, thanks for the suggestion, but I'm not adding any more themes at this time. The initial contribution is helpful but most of the work is in the ongoing maintenance, and I'm happy with where the number is at for now!
