### ISSUE TITLE
Bootswatch as a nuget package

### ISSUE THREAD

**Issue by frapontillo** [thomaspark/bootswatch#76]
Is it possibile to add Bootswatch as a [nuget](http://nuget.org/packages) package?

**Comment by superware** [comment]
Can you please update the nuget package? it's showing 3.3.5 from May 07 2015. Thanks!

**Comment by thomaspark** [comment]
Just updated to 3.3.6! https://www.nuget.org/packages/Bootswatch/3.3.6

**Comment by superware** [comment]
Thanks! but it seems the new package is causing troubles in Visual Studio 2015, getting an "Error occurred" message in the "Installed" tab, when "Show errors in output" seeing "An item with the same key has already been added.". Downgrading to 3.3.5 fixed this temporarily.
