### ISSUE TITLE
darkly theme 3.3.7 has-error issue

### ISSUE THREAD

**Issue by lonekawboy** [thomaspark/bootswatch#761]
Really like the darkly theme but when I'm attempting to apply has-error class to input it doesn't display a red border as expected. If I change to say flatly then it appears red in my app. Thanks much for taking the time to look into this as I really want to use darkly in my app!

**Comment by thomaspark** [comment]
Hey @lonekawboy, glad you're finding Darkly useful. I recommend upgrading to Bootstrap 4 as I'm shifting focus to it going forward. The latest version of Darkly does have the borders you're talking about.

**Comment by lonekawboy** [comment]
Thanks much for the response Thomas!

I switched over to Bootstrap 4 and everything looks great except for when I attempt to addon to input fields:

[cid:image002.png@01D390E3.A9088480]

This gives me this:

[cid:image004.png@01D390E3.A864A360]

So the color on the input-group-text must have some issues.

Thanks much!

Paul

**Comment by thomaspark** [comment]
Hey @lonekawboy, thanks for the bug report. A fix is on the way.
