### ISSUE TITLE
post v4.0.0-beta.3 release tasks

### ISSUE THREAD

**Issue by m5o** [thomaspark/bootswatch#766]
Hey @thomaspark 👋 

I guess your magic fingers are required for these tasks:

* [x] update [npmjs.com/package/bootswatch](https://www.npmjs.com/package/bootswatch)
* [x] add release to [bootstrapcdn.com/bootswatch](https://www.bootstrapcdn.com/bootswatch/) (fix broken link in [api.json](https://github.com/thomaspark/bootswatch/blob/master/docs/api/4.json#L11))
* [x] add release to [cdnjs.com](https://cdnjs.com/libraries/bootswatch) (resolve #738)
   * 🎫  https://github.com/cdnjs/cdnjs/pull/12410

##### other

* [x] update [bootswatch-rubygem](https://rubygems.org/gems/bootswatch) 
  > 🔔 ping @mkhairi 

🤓✌️

**Comment by thomaspark** [comment]
Hey @m5o thanks for setting up this issue. Just updated the npm package!

**Comment by m5o** [comment]
@XhmikosR Are you in charge updating https://www.bootstrapcdn.com/bootswatch/ ?

**Comment by XhmikosR** [comment]
Yeah sort of. We need to update the CDN files and I have a PR for the
front-end.

**Comment by m5o** [comment]
✨ Done ✨
