### ISSUE TITLE
Lumen Modals

### ISSUE THREAD

**Issue by TheSpartaPT** [thomaspark/bootswatch#768]
because you have this:
```
.close {
  color: #fff;
  text-decoration: none;
  opacity: 0.4;
}

.close:hover, .close:focus {
  color: #fff;
  opacity: 1;
}
```

(line 9027 to 9035 of bootstrap.css)

the "X" to close the modal is the same color as the background so it is basically invisible. I only found it on the lumen theme but i didn't look on every single one

**Comment by thomaspark** [comment]
Hey @TheSpartaPT, thanks for the bug report. Pushing a fix now.
