### ISSUE TITLE
Where did `data-toggle="buttons"` declaration go?

### ISSUE THREAD

**Issue by 3Nex** [thomaspark/bootswatch#769]
I'm a little confused. The current versions of Bootswatch themes don't have a declaration for the `[data-toggle="buttons"]>.btn input[type="radio"]` selector. I have dug up an older version of a Cosmo theme i've had on my computer, and that one does have it. The mentioned selector is (still) part of the original Bootstrap. 

Is this a bug or was it removed for some reason?

(this all refers to the new Bootstrap version 4)

**Comment by thomaspark** [comment]
Hey @3Nex, this change was just introduced in Bootstrap 4 beta 3, and reflected in the Bootswatch themes. If you check Bootstrap, you'll find it was removed too.

See here for beta 3 changes including to checkbox and radio controls: https://blog.getbootstrap.com/2017/12/28/bootstrap-4-beta-3/
