### ISSUE TITLE
Dark themes should have bg-white and bg-dark inverted

### ISSUE THREAD

**Issue by giflw** [thomaspark/bootswatch#774]
Hi

I was testing bootswatch themes with a calendar on codepen using a ligth background based theme. I've put the classes `bg-white` and `bg-dark`, and some text over `bg-white`, with no extra classes for color. The result was as expected, dark color text over light color background. But changing the theme to a dark background based one shows light text over light background.

As `bg-white` and `bg-dark` where created on light background themes, they should have inverted colors on dark themes, so can dark and light themes could be replaced without any changes.

Actual themes (light and dark):
`bg-white`: white color
`bg-dark`: dark color

Expected on dark themes:
`bg-white`: dark color
`bg-dark`: white color

**Comment by thomaspark** [comment]
Hey @giflw, thanks for your input. I've considered doing what you suggest, but it's a tough choice between making the themes easily swappable (this would make my own job easier for the Bootswatch site) and keeping the semantics of the color classes.

For now I've kept the semantics because it benefits the main use case of using a single theme. I'll keep this open for discussion though.

**Comment by giflw** [comment]
The semantics is good for light background themes, but I think the ability to swap themes is more interesting then semantics in this case. As bootstrap4 is in beta, would be a nice moment to try inverted semantics on background theme. Could be an alert on docs to let clear that semantics are ok in light backgrounds, but `light` and `dark` are inverted on dark background themes.

This change could make people discuss more about this issue, as they would be experimenting on it. 

Indeed, this experimentation could bring even more light to the subject.

**Comment by bitonic** [comment]
i think @giflw is right -- being able to change themes without changing the code is more valuable than semantics here.
