### ISSUE TITLE
Question: why depend directly on jQuery and popper.js?

### ISSUE THREAD

**Issue by sethb0** [thomaspark/bootswatch#779]
These are dependencies of Bootstrap, not direct dependencies of Bootswatch (as I understand it). Including them as direct dependencies makes it difficult to use packages like bootstrap-vue which replace the jQuery code in Bootstrap with framework-specific code.

**Comment by thomaspark** [comment]
Sure, I see no reason why jQuery and popper.js can't be moved to `devDependencies`.
