### ISSUE TITLE
Yeti: White text on white background...

### ISSUE THREAD

**Issue by webbird** [thomaspark/bootswatch#783]
It seems that all themes have a problem with the CSS hierarchy, as the font color in alerts gets overridden. (See screenshot.) On Yeti theme, using "alert alert-secondary" the result is white text (#fff) on white background (#fcfcfc). I'd suggest a darker background color and !important added to text color. (Or fix hierarchy.)

![2018-02-01 13_14_05](https://user-images.githubusercontent.com/147354/35678078-481b3bdc-0752-11e8-88d8-c314c9cb1939.png)

I used the latest build downloaded yesterday.

**Comment by webbird** [comment]
I tried the colors of btn-secondary, looks good.

.alert-secondary {
    color: #7c7c7c !important;
    background-color: #eee !important;
    border-color: #e1e1e1 !important;
}

**Comment by thomaspark** [comment]
@webbird, thanks for the bug report, pushing a fix now. Please let me know if I missed any.

**Comment by webbird** [comment]
Wow, that was fast! Checked "Yeti", looks good now! 👍  Thank you very much!

**Comment by swarthy** [comment]
@thomaspark could you please update npm version of bootswatch?
