### ISSUE TITLE
Error on navbar

### ISSUE THREAD

**Issue by tcortes55** [thomaspark/bootswatch#784]
Bootswatch themes are not being displayed correctly in ASP.NET MVC applications. The main menu bar at the top switches to a button with no text. I experienced this issue with 2 different themes - Minty and Flatly - and found some people having the same problem with other themes.

See:
https://stackoverflow.com/questions/47978065/bootstrap-template-is-not-working-in-mvc-application?noredirect=1&lq=1
https://stackoverflow.com/questions/48400768/how-to-change-asp-net-mvc-bootstrap-theme-without-view-error-like-one-on-the-pic?noredirect=1&lq=1

PS: I found an old version of Flatly theme on another user's GitHub and it worked fine. I believe this problem might be related to a recent modification.

**Comment by thomaspark** [comment]
Yup, just make sure you're on the same version as the Bootstrap being used. Right now v4 is on bootswatch.com, but you can grab older versions at https://bootswatch.com/3/ and https://bootswatch.com/2/
