### ISSUE TITLE
Provide an Official, Curated List of Swatches

### ISSUE THREAD

**Issue by Rabadash8820** [thomaspark/bootswatch#785]
Hello, I am trying to put a `<select>` on my webpage that will allow users to change the Bootswatch theme on the fly (by loading its CSS from BootstrapCDN).  I would like this dropdown to include the same options as the "Themes" dropdown of the Bootswatch [website](https://bootswatch.com/).  However, I don't want to have to check back at that website forever to see if new swatches are available, or follow some Twitter feed.

It would be nice if there were an officially curated list of swatches somewhere, preferably associating swatch versions with the version of Bootstrap that they work with.  Granted, I can always query the names of directories in the [dist/](https://github.com/thomaspark/bootswatch/tree/master/dist) directory of this repository's master branch, but that feels a bit hackish.  It would be really great if I could just HTTP GET some file like "bootswatch-list.json" that would have entries like those below.  Does what I'm describing already exist somewhere?  If not, consider this a feature request!

```json
{
  "boostrap-4.0.0-beta.2": [
    {
      "name": "cerulean",
      "href": "...",
      "integrity": "sha384-..."
    },
    {
      "name": "cosmo",
      "href": "...",
      "integrity": "sha384-..."
    },
    ...
  ],
  "boostrap-4.0.0-beta.3": [
    {
      "name": "cerulean",
      "href": "...",
      "integrity": "sha384-..."
    },
    {
      "name": "cosmo",
      "href": "...",
      "integrity": "sha384-..."
    },
    ...
  ],
  "boostrap-4.0.0": [
    {
      "name": "cerulean",
      "href": "...",
      "integrity": "sha384-..."
    },
    {
      "name": "cosmo",
      "href": "...",
      "integrity": "sha384-..."
    },
    ...
  ],
  ...
}
```

**Comment by thomaspark** [comment]
Hey @Rabadash8820, check out https://bootswatch.com/api/4.json.

**Comment by Rabadash8820** [comment]
@thomaspark Yes that's exactly the sort of thing I'm looking for!  I'm still on BS 4 beta 2; what would be the URL for that?  And is there a way to also get the SRI hashes?

**Comment by thomaspark** [comment]
That file is updated with the latest. For earlier versions like 4.0.0-beta.2, you might be able to query a CDN:

https://www.bootstrapcdn.com/bootswatch/
https://cdnjs.com/libraries/bootswatch

They should provide hashes as well.

**Comment by Rabadash8820** [comment]
Okay, looks like the `cdnjs` one has what I'll need.  I've never used a CDN's api before but it shouldn't be too hard to figure out :)  I can close this comment once I do.
