### ISSUE TITLE
Some skins broken right now

### ISSUE THREAD

**Issue by dangerusslee** [thomaspark/bootswatch#786]
https://community.nodebb.org/ looks like the below screen shot right now when using Spacelab.  Works fine in some themes, not in others.  

![image](https://user-images.githubusercontent.com/24903887/35782416-a29768c2-09c5-11e8-9976-d6872be387d4.png)

**Comment by thomaspark** [comment]
One suggestion is to check that you're using the correct version of Bootswatch.

Also assuming there's custom CSS on top of Bootstrap, themes won't work perfectly out of the box and will require tweaking.

**Comment by dangerusslee** [comment]
@thomaspark apparently you guys just switched /latest to another version of bootstrap which broke older version of bootstrap.
