### ISSUE TITLE
Unicode Emoji Variation Selector does not work

### ISSUE THREAD

**Issue by NickLavrov** [thomaspark/bootswatch#787]
My own (ugly) bootstrap theme can properly render a character as an emoji when `U+FE0F` follows the character. For example, see `<h1>🅱&#xFE0F;😎</h1>`. With the FEOF character, the "B" will normally render as a black box with a white "B", but the FEOF character forces it to render as (for Apple) the red emoji box with the letter "B" in it. More info on the unicode selector here: http://mts.io/2015/04/21/unicode-symbol-render-text-emoji/

I switched to use the Minty theme, and now the "B" always renders in the text style, not the emoji style. I tried commenting out some font choices in the bootstrap.css file, but this did not fix anything.

I would consider the acceptance criteria for resolving this issue as either:
1. Provide information on what parts of the theme are making this fail, or
2. Modify the themes to allow the emoji selector to function properly.

**Comment by thomaspark** [comment]
Looks like an issue in Bootstrap's default font stack, namely `BlinkMacSystemFont` (Apple's San Francisco). Recommend opening an upstream issue with Bootstrap or submitting a ticket to Apple.

In the meantime, you can override it in your theme to show the variations.
