### ISSUE TITLE
contrast on darkly theme with text-dark class

### ISSUE THREAD

**Issue by jipexu** [thomaspark/bootswatch#790]
Hi there
on
https://bootswatch.com/darkly/

the contrast is not enough ?...

the .card-body .text-dark

```
<div class="card border-dark mb-3" style="max-width: 20rem;">
  <div class="card-header">Header</div>
  <div class="card-body text-dark">
    <h4 class="card-title">Dark card title</h4>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>
```

**Comment by thomaspark** [comment]
`.text-light` or `.text-white` would work better. But in the interest of keeping the preview page markup as uniform as possible, I'll remove the text color classes from the bordered cards.
