### ISSUE TITLE
.input-group-text same color as .background-color in Darkly Theme

### ISSUE THREAD

**Issue by jakob153** [thomaspark/bootswatch#794]
The input group text has the same color as the background color in the Darkly Theme. Issue found in npm & cdn versions.
The css downloaded from the website is fine though.

![capture](https://user-images.githubusercontent.com/17678207/36357537-c61f01fc-14ff-11e8-9e32-2fa6cc3456de.PNG)
![capture2](https://user-images.githubusercontent.com/17678207/36357541-cc44a08c-14ff-11e8-8a1a-36a5e99a95c7.PNG)

**Comment by thomaspark** [comment]
Thanks for the heads up @jakob153. It looks like this was fixed at some point but it won't be updated on npm and cdn until the Bootstrap version number is ticked.
