### ISSUE TITLE
CSS not applied

### ISSUE THREAD

**Issue by paulpottertasd** [thomaspark/bootswatch#795]
ng build --prod isn't applying bootswatch. Angular CLI 1.7. Are you aware of a fix?

**Comment by thatnini** [comment]
is this still an issue?

Don't use Angular myself, but it looks like they updated Angular CLI to fix a dependency issue with clean-css.

[https://github.com/angular/angular-cli/releases/tag/v1.7.3](https://github.com/angular/angular-cli/releases/tag/v1.7.3)
