### ISSUE TITLE
Lumen navbar-dark is not consistence with bg-dark 

### ISSUE THREAD

**Issue by truongan** [thomaspark/bootswatch#798]
AFAIK, the bootstrap document in **https://getbootstrap.com/docs/4.0/components/navbar/#color-schemes** specify that 
>  Choose from .navbar-light for use with light background colors, or .navbar-dark for dark background colors.

That would mean `navbar-dark` style should be used with a dark background color. 
In the rest of the themes, `bg-dark` will provide a dark background-color, thus conforming pretty well to the document. However lumen appears to use quite bright color for `bg-dakr` style (`f0f0f0` should not be considered a dark color). This makes fonts in `navbar-dark` style unreadable.

**Comment by thomaspark** [comment]
Hey @truongan, thanks for opening an issue for this. I'll change `.bg-dark` to a dark gray option. Will be updated in the next release.
