### ISSUE TITLE
Dark theme style should not style <pre> tag dark color.

### ISSUE THREAD

**Issue by truongan** [thomaspark/bootswatch#799]
I just notice that on Dark theme (cyborg, darkly, slate, superhero, solar) `<pre>` tag is styled with dark color, making them illegible on the dark background. 
I have to temporarily fixed that with one additional line in my own css
`
pre {
	color: inherit;
}
`

As I'm looking around, it seems that bootstrap documentation doesn't specify any color semantic for `<pre>` tag. However, the default boostrap 4 and the majority of bootswatch light theme style `<pre>` tag to be the same color with `<body>` tag, dark theme should follow suit.

**Comment by thomaspark** [comment]
@truongan, thanks for the bug report and the suggested fix. Pushing a commit for this now.
