### ISSUE TITLE
Bootswatchlet for Bootstrap 3 doesn't work

### ISSUE THREAD

**Issue by ivansammartino** [thomaspark/bootswatch#800]
[Bootswatchlet for Bootstrap 3.*](https://bootswatch.com/3/help/#bookmarklet) doesn't work anymore.
All CSS point to unexistent file (i.e. https://bootswatch.com/cerulean/bootstrap.min.css) leading to an Error 404 page
Please, can you fix this? Thank you :-)

**Comment by thomaspark** [comment]
Thanks @ivansammartino, I'll fix the bookmarklet at the link now.
