### ISSUE TITLE
style doesn't match preview image on bootstrap cdn

### ISSUE THREAD

**Issue by schmidlop** [thomaspark/bootswatch#802]
steps to reproduce
1. go to the bootswatch examples here:
https://www.bootstrapcdn.com/bootswatch
1. scroll down to minty
1. click try it

**expected result**: minty green top nav bar
**actual result**: peachy orange top nav bar

**Comment by thomaspark** [comment]
Hey @schmidlop, both navbar colors are available in Minty. It depends on which classes you use: BoostrapCDN uses `.bg-dark` for peachy orange but you can apply `.bg-primary` to get minty green.

Check out https://bootswatch.com/minty/ for all the options.
