### ISSUE TITLE
Issue with Lumen tabs active state.

### ISSUE THREAD

**Issue by vemuez** [thomaspark/bootswatch#804]
I've attempted with a few other themes and it seems to be working. 
The issue is that the tabs do not remain active, even when the css is applied. I've implemented this into my angular project, the code initializes the tabs with the active class. However, it does not stay as active.

An example to test this on, go on the link at the bottom, this should take you to the official bootswatch page. On the Tabs section, click on a tab to activate it. Note that the tab raises and visually looks active. Now, right click anywhere on the screen. You should notice that the tab drops back down to an inactive state visually however, the active class remains in the element. As long as the active class remains on the element, the tab should visually look active too. 

https://bootswatch.com/lumen/#navs

**Comment by thomaspark** [comment]
Thanks @vemuez, I'm pushing a fix for this and some other tweaks to active tabs now.
