### ISSUE TITLE
tabs not apply css

### ISSUE THREAD

**Issue by lonekawboy** [thomaspark/bootswatch#807]
I really like the Sandstone theme but I don't like the nav-tabs as I don't want the full "tab" and only want underlines with different colors under the text. I have created css to do this but I cannot get rid of the tab border and gray background for the non-active and non-hover tabs. When I remove the sandstone css from the styles and go back to default bootstrap everything works as expected so I'm assuming it is something in the sandstone css. Thanks much!

**Comment by thomaspark** [comment]
Hey @lonekawboy, I was able to get rid of the tab borders and background by just setting `border: none;` and `background: none;`. Can you make a demo on JSFiddle showing what you've got?

**Comment by lonekawboy** [comment]
Forgot to mention that I'm using ngx-bootstrap tabset for the actual tabs but I'm assuming that they are using the bootstrap navs so that shouldn't matter.

**Comment by lonekawboy** [comment]
I would really like to see your example as nothing I try removes anything for the border or background.

<div class="row mb-sm-4">
<div class="col-8">
<ul class="nav nav-tabs">
<li class="nav-item tabCustom">
<a href="" class="nav-link">Test</a>
</li>
<li class="nav-item">
<a href="" class="nav-link">Payment</a>
</li>
</ul>
</div>
</div>


.tabCustom {
border: none;
background: none;
}

All show this:

[cid:9b496e53-39b7-4b6c-b482-fe0be4e25554]
________________________________

**Comment by thomaspark** [comment]
Can you make a live demo on JSFiddle and post the link here?

**Comment by lonekawboy** [comment]
Figured it out. Started 100% from scratch on the CSS and it worked. Thanks much and sorry for bringing you into what ended up being my problem! Thanks for all that you do as this is an excellent resource!
________________________________

**Comment by thomaspark** [comment]
Glad you got it figured out!
