### ISSUE TITLE
flatly is not using navy blue

### ISSUE THREAD

**Issue by wcataldo** [thomaspark/bootswatch#808]
Hi
Thank you for your heavy lifting with bootswatch.

When I applied flatly html this morning it was using an aqua blue instead of navy, Not sure if that was intended or not.

`<link href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0/flatly/bootstrap.min.css" rel="stylesheet" integrity="sha384-jb1k1ntK2AaXuVTIiFXgcGvjcWQrYlrsxipJRLPdwnr1sHBRqSLowOD2q3dIL5KG" crossorigin="anonymous">`

hmm

Looks like maxcdn bootstrap.css.min has

```
.bg-dark {
    background-color: #18BC9C !important;
}
```
With flatly, think it should be

```
.bg-dark {
    background-color: #2c3e50 !important;
}
```

That's not all. After that the hover on menu items go to what I am calling navy blue #2c3e50, causing them to disappear.

```
.bg-dark.navbar-dark .navbar-nav .nav-link:focus, .bg-dark.navbar-dark .navbar-nav .nav-link:hover, .bg-dark.navbar-dark .navbar-nav .active>.nav-link {
    color: #2C3E50 !important;
}
```
maybe minus the !importants.
Best regards

**Comment by thomaspark** [comment]
Hey @wcataldo, for the navy blue navbar, use `.bg-primary` instead of `.bg-dark` See here for the navbar options: https://bootswatch.com/flatly/#navbars

**Comment by wcataldo** [comment]
Well color me purple. I did not know that....
