### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by muellmanns** [thomaspark/bootswatch#814]
[This package](https://www.jsdelivr.com/package/npm/bootswatch) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by thomaspark** [comment]
Would be nice to have it set to get rid of the warnings but there isn't a file that makes sense for it. See also #324 and #473.

**Comment by muellmanns** [comment]
Hello, Tom, 

thank you very much for your quick answer and the great theme. Maybe I misunderstand, but _https://cdn.jsdelivr.net/npm/bootswatch@4.0.0/cyborg/bootstrap.min.css doesn't exist or is the URL wrong?

**Comment by thomaspark** [comment]
Hey @muellmanns, thanks for the follow-up. The URL has changed slightly. All CSS files have been moved to a `dist/` directory so you can access them at https://cdn.jsdelivr.net/npm/bootswatch@4.0.0/dist/cyborg/bootstrap.min.css.
