### ISSUE TITLE
inconsistent $progress-height value from rem to px 

### ISSUE THREAD

**Issue by JavaTMP** [thomaspark/bootswatch#818]
Hello, and thank you a lot for beautiful and awesome set of standard bootstrap 4 themes. we applied most of your theme quickly as you described in github welcome page. But we noticed a broken behavior of our custom progress bar plugin Ion Range Slider which caused by changing the metric used in standard bootstrap 4 sass `$progress-height` which was rem; and you override it to px meanly in:
`bootswatch/dist/cosmo/_variables.scss` 
`bootswatch/dist/darkly/_variables.scss`
`bootswatch/dist/flatly/_variables.scss`
`bootswatch/dist/materia/_variables.scss`

We think it is better to keep rem instead of converting it to px.

For example in cosmo instead of overriding 
`$progress-height: 1rem` to `$progress-height: 8px;` you can use 
`$progress-height: .5rem;` 
and so on.

our live demo is http://demo.javatmp.com/JavaTMP-Static-Ajax-Starter/#pages/themes/bootswatch.html
select cosmo theme and after site updated its style to it press to plugins/Ion Range Slider menu item on the sidebar.

**Comment by thomaspark** [comment]
Hi, thanks for the bug report. All the units should be converted to `rem` but there are some `px` holdovers from v3. I'm pushing a fix for this now -- it should be updated in the packages with the next release.
