### ISSUE TITLE
Materia .input-group-sm/lg button addons broken

### ISSUE THREAD

**Issue by skylarmt** [thomaspark/bootswatch#819]
This minimal page:
```
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://bootswatch.com/4/materia/bootstrap.min.css" rel="stylesheet" />

<div class="input-group input-group-sm">
    <div class="input-group-prepend">
        <button class="btn btn-primary" type="button">Left</button>
    </div>
    <input type="text" class="form-control" value="Hello World" />
    <div class="input-group-append">
        <button class="btn btn-success" type="button">Right</button>
    </div>
</div>
```
Results in this:
![glitchy screenshot](https://user-images.githubusercontent.com/6668965/38762599-ca37f6a2-3f4a-11e8-9aca-076d50429a16.png)

The same thing but scaled up happens with `.input-group-lg`:
![another glitch](https://user-images.githubusercontent.com/6668965/38762592-b34276d4-3f4a-11e8-98e8-c1a56c1d73c1.png)

Tested with the latest CSS, as evidenced by the stylesheet URL.

**Comment by skylarmt** [comment]
In some cases, I've seen part of the first character in the input field get cut off by the button.  It seems the horizontal margins are all screwy, as well as the vertical button size.

**Comment by thomaspark** [comment]
Hey @skylarmt, thanks for the bug report. Pushing a fix for this now.

**Comment by skylarmt** [comment]
Looks like your commit is missing some padding for `.input-group-text`, so having one of them causes the original problem again:

```
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://bootswatch.com/4/materia/bootstrap.min.css" rel="stylesheet" />

<div class="input-group input-group-sm">
    <div class="input-group-prepend">
        <button class="btn btn-primary" type="button">Left</button>
    </div>
    <input type="text" class="form-control" value="Hello World" />
    <div class="input-group-append">
        <button class="btn btn-success" type="button">Right</button>
    </div>
</div>

<br />

<div class="input-group input-group-sm">
    <div class="input-group-prepend">
        <span class="input-group-text bg-primary text-light">Left</span>
    </div>
    <input type="text" class="form-control" value="Hello World" />
    <div class="input-group-append">
        <button class="btn btn-success" type="button">Right</button>
    </div>
</div>

<br />

<div class="input-group input-group-sm">
    <div class="input-group-prepend">
        <span class="input-group-text bg-primary text-light" style="padding: 0.25rem 0.5rem;">Left</span>
    </div>
    <input type="text" class="form-control" value="Hello World" />
    <div class="input-group-append">
        <button class="btn btn-success" type="button">Right</button>
    </div>
</div>
```

![screenshot-2018-4-16 http localhost](https://user-images.githubusercontent.com/6668965/38833988-5115c92a-4184-11e8-8e8d-d1f4f47b8845.png)

**Comment by thomaspark** [comment]
The padding does differ between buttons and text so the text is flush with the left and right edges. This is in line (no pun intended) with the [Material Design guidelines](https://material.io/guidelines/components/text-fields.html#text-fields-states).

I'm expecting in most cases `input-group-text` will be used without a background color, which imo looks better:

<img width="395" alt="screen shot 2018-04-16 at 4 53 54 pm" src="https://user-images.githubusercontent.com/900407/38834611-f22df122-4196-11e8-9ce3-c64bc6e75ad2.png">

If you want a background color, I recommend adding your own padding like you've done or using a button.

**Comment by skylarmt** [comment]
The issue is regarding using an `input-group-text` and a button in the same `input-group`.  I only used the background color to better show the issue.  Look closely at the middle row in the screenshot I posted above.

**Comment by thomaspark** [comment]
I see, I'll push a fix for that now.
