### ISSUE TITLE
sandstone alert-primary not displaying correct color

### ISSUE THREAD

**Issue by lonekawboy** [thomaspark/bootswatch#828]
In sandstone 4.0.0 if I do this:

```
<div class="alert alert-primary">
</div>
```

I do not get the expected primary color displayed.

Thanks much!

**Comment by thomaspark** [comment]
Hey @lonekawboy, it's working for me. Can you post a JSFiddle of what you're getting?

https://jsfiddle.net/o9vswbue/

<img width="539" alt="screen shot 2018-04-24 at 3 24 42 pm" src="https://user-images.githubusercontent.com/900407/39209352-a2536a5e-47d3-11e8-9e75-dee0d6a03489.png">

**Comment by lonekawboy** [comment]
It works just fine for me with 4.1 so I'm good to go.

Thanks much!
________________________________

**Comment by thomaspark** [comment]
No problem!
