### ISSUE TITLE
Bootstrap 4.1.1

### ISSUE THREAD

**Issue by XhmikosR** [thomaspark/bootswatch#832]
@thomaspark: 4.1.1 is out, not sure if it's worth making a new release here or not.

I just wanted to track it in case you make a release.

**Comment by IAmHopp** [comment]
As an user, I'd say it's worth it. I was about to open this issue if it wasn't already here.

**Comment by thomaspark** [comment]
@XhmikosR, thanks for the heads up. Pushing update now.

**Comment by XhmikosR** [comment]
Damn, just made a production release on BootstrapCDN a few minutes ago :/

Oh, well, thanks, I'll update it tomorrow.

**Comment by thomaspark** [comment]
Figures, that's always how my timings work out. 😛
