### ISSUE TITLE
Can't get the Navigation Bars to work properly from copied code

### ISSUE THREAD

**Issue by Bwest981** [thomaspark/bootswatch#836]
**Am I missing something?

Can't get the simple navigation bars to work properly. Maybe I am just overlooking it?
Can't get the hamburger menu or the drop-down menus working...**

**With https://bootswatch.com/4/cerulean/bootstrap.min.css 
then Copied Code:**

_> <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
>   <a class="navbar-brand" href="#">Navbar</a>
>   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
>     <span class="navbar-toggler-icon"></span>
>   </button>
> 
>   <div class="collapse navbar-collapse" id="navbarColor01">
>     <ul class="navbar-nav mr-auto">
>       <li class="nav-item active">
>         <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
>       </li>
>       <li class="nav-item">
>         <a class="nav-link" href="#">Features</a>
>       </li>
>       <li class="nav-item">
>         <a class="nav-link" href="#">Pricing</a>
>       </li>
>       <li class="nav-item">
>         <a class="nav-link" href="#">About</a>
>       </li>
>     </ul>
>     <form class="form-inline my-2 my-lg-0">
>       <input class="form-control mr-sm-2" type="text" placeholder="Search">
>       <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
>     </form>
>   </div>
> </nav>_

**Comment by thomaspark** [comment]
You also need these js files to get dropdowns and other components working:

http://getbootstrap.com/docs/4.1/getting-started/introduction/#js

**Comment by Bwest981** [comment]
I copied the html directly from the website for the navigation bar.

Maybe I am missing a file? All I have is below for reference.
  <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.0/cerulean/bootstrap.min.css" rel="stylesheet" integrity="sha384-KZYvDM6uZ38YbkIu7BXKA/PnGrwKacp5/NXQ8UoYr3ZBgXBbI2ybVID/YMoBUmoa" crossorigin="anonymous">

**Comment by Bwest981** [comment]
Thank you it worked!
