### ISSUE TITLE
Map file for minified css

### ISSUE THREAD

**Issue by cdoole** [thomaspark/bootswatch#838]
I am using the slate theme for coursework in a Coursera specialisation but you don't seem to have the .map files in the download list. Could you provide me with the bootstrap.min.css.map file for the slate theme so I can include it in my project please

**Comment by thomaspark** [comment]
No problem, here's a zip with the source maps. Good luck with your assignment.

[slate.zip](https://github.com/thomaspark/bootswatch/files/2064667/slate.zip)

**Comment by cdoole** [comment]
many thanks I'm making a multi-album photo collection but I prefer to use my own images rather than the basic images they provided
