### ISSUE TITLE
bootswatch themes 3.3.7 with web-font fails to compile with less 3.0.4

### ISSUE THREAD

**Issue by kitsguru** [thomaspark/bootswatch#841]
Trying to recompile the 3.3.7 less themes with less 3.0.4 fails with the following error:

```
/themes/cosmo/bootswatch.less: [L10:C0] variable @path is undefined
Warning: Error compiling www/_src/less/theme-cosmo.less Use --force to continue.
```
Code in question is:
```
@web-font-path: "https://fonts.googleapis.com/css?family=Roboto:400,700";

.web-font(@path) {
  @import url("@{path}");
}
.web-font(@web-font-path);
```
I can't see why this would fail or why @path is now considered undefined. Any ideas would be appreciated.

**Comment by thomaspark** [comment]
Maybe related to https://github.com/less/less.js/issues/3188?

Can you try `@import (css) url("@{path}");` and see if it fixes it for you?

**Comment by kitsguru** [comment]
Bingo - that did it. Are you going to fix the various themes will I need to manually do it each time I download them. I am slowing converting to Bootstrap 4 but not ready yet. Also I see that they are going to do a bootstrap 3.4.

**Comment by zeraien** [comment]
So, i'm using bootswatch 3.4.1 and this issue is still present... :-(
Looks like there was a regression in 3.4: https://github.com/thomaspark/bootswatch/blame/99712ea1efd9fd42fd008ecd36023db5f15c92e1/docs/3/lumen/bootswatch.less#L8

Any chance this can be fixed?

**Comment by batje** [comment]
If you ever get here, this patch has never been deployed to bootswatch.com
see https://bootswatch.com/3/cosmo/bootswatch.less
