### ISSUE TITLE
Make the version 3 themes work with Less v3

### ISSUE THREAD

**Issue by lipis** [thomaspark/bootswatch#842]
The old themes are generating an error when compiled with Less v3.
https://github.com/less/less.js/issues/3218

Would it be possible to simplify them as I'm sure there are plenty of people still using the version 3.3.7?

We could simply change this

```less
.web-font(@path) {
  @import url("@{path}");
}
.web-font(@web-font-path);
```

to that

```less
@import url("@{web-font-path}");
```

**Comment by thomaspark** [comment]
Oops, just saw this issue. @lipis, did the change at the bottom of #841 fix this error for you?

**Comment by lipis** [comment]
Will have to check next week! :) Thanks..
