### ISSUE TITLE
Can you remove Dependency on Bootstrap

### ISSUE THREAD

**Issue by chris31389** [thomaspark/bootswatch#843]
Is bootstrap really a dependency?

I've just seen [ng-bootstrap](https://ng-bootstrap.github.io/#/getting-started) which looks to remove the javascript part of Bootstrap.  Seeing as one of your theme overrides the css, could I use bootswatch with ng-bootstrap without using any bootstrap implementation?

**Comment by thomaspark** [comment]
This point has been brought up a few times before — seeing as Bootstrap isn't a strict requirement to use the themes, I can move it to `devDependencies`.
