### ISSUE TITLE
Yeti - Pagination first page item missing left border radius

### ISSUE THREAD

**Issue by rkubik** [thomaspark/bootswatch#844]
On the Yeti demo page you can see the issue by using Developer Tools to change the first page item to active: https://bootswatch.com/yeti.

<img width="446" alt="screen shot 2018-06-28 at 9 58 24 pm" src="https://user-images.githubusercontent.com/927179/42072583-8039c9c6-7b1e-11e8-8087-127d6d69ccb3.png">

**Comment by thomaspark** [comment]
Thanks @rkubik, fix on the way.

**Comment by rkubik** [comment]
Thanks @thomaspark!
