### ISSUE TITLE
Styling issues with custom-file-input

### ISSUE THREAD

**Issue by wattsbn** [thomaspark/bootswatch#846]
Bootstrap supports overriding the browser's default file input design by using the 'custom-file', 'custom-file-input', and 'custom-file-label' class names.

https://getbootstrap.com/docs/4.0/components/forms/#file-browser
```
<div class="custom-file">
  <input type="file" class="custom-file-input" id="customFile">
  <label class="custom-file-label" for="customFile">Choose file</label>
</div>
```

When using this, the styles for the cyborg, darkly, superhero themes render the 'Browse' button incorrectly. The text on the button in these themes is almost invisible.

![image](https://user-images.githubusercontent.com/850664/42128287-cb082684-7c5c-11e8-9dfd-d120ec51229c.png)
![image](https://user-images.githubusercontent.com/850664/42128280-b260c9c4-7c5c-11e8-87a2-5ab5b23d07b3.png)
![image](https://user-images.githubusercontent.com/850664/42128293-de72c67a-7c5c-11e8-84ce-eb10dab2cf99.png)

**Comment by thomaspark** [comment]
@wattsbn, thanks for the bug report. Fix on the way.

**Comment by wattsbn** [comment]
Thanks. How often do you bump the package version and release a new version on the cdn (that is how I currently consume it)?

**Comment by thomaspark** [comment]
It gets bumped whenever Bootstrap does.
