### ISSUE TITLE
Materia indistinguishable disabled and readonly inputs on forms

### ISSUE THREAD

**Issue by rolandoisidoro** [thomaspark/bootswatch#847]
Hi,

as is, both `disabled` and `readonly` inputs are indistinguishable from regular inputs, since the styles set to tell them apart are simply `dotted` instead of `solid` `border-bottom` and the override of an unnoticeable `inset 0 -1px 0 #ddd` `box-shadow`.

I consider this to be a problem regarding User Experience (UX) in an overall stupendous theme. I've made a few tests and came up with 2 possible solutions:

1. **Preferred** - Set the element's `color` and `::placeholder color` to `#ddd`;
2. Set the element's `background color` to `#ddd`.

Thanks in advance, keep up the great work,
Rolando Isidoro

**Comment by thomaspark** [comment]
My first thought was to adjust the `readonly` input's color too, so we're in agreement about that. Pushing a fix for it now.

Thanks for opening this. Let me know if you run into any other issues with Materia.
