### ISSUE TITLE
bootswatch.com ssl certificate revoked and not accessible via http

### ISSUE THREAD

**Issue by Brandhor** [thomaspark/bootswatch#848]

**Comment by GramThanos** [comment]
Some more information.

Mozilla Firefox error code: `SEC_ERROR_REVOKED_CERTIFICATE`
Google Chrome error code: `NET::ERR_CERT_REVOKED`

Chrome gives the following certificate information (I trimmed the PEM to be smaller)
```
Subject: sni97964.cloudflaressl.com

Issuer: COMODO ECC Domain Validation Secure Server CA 2

Expires on: Jan 7, 2019

Current date: Jul 5, 2018

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIKoTCCC...
...UORvxw==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDnzCCA...
...0eLLUg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIID0DCCA...
...rV1aug=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIENjCCA...
...x49OhgQ=
-----END CERTIFICATE-----
```

**Comment by rolandoisidoro** [comment]
You could use [Let’s Encrypt](https://letsencrypt.org/) as a temporary solution while you don't solve it with your current CA.

**Comment by BigChief45** [comment]
Seems like it's back and running again.

**Comment by thomaspark** [comment]
Opened a ticket with Cloudflare and it seems to have been resolved. Hopefully no more outages like this come anytime soon. Thanks for your patience.
