### ISSUE TITLE
Flatly and Darkly font-size inconsistent

### ISSUE THREAD

**Issue by aderrose** [thomaspark/bootswatch#852]
Hi,

I'm currently building a dark mode for one of my sites and noticed that H1, H2 and H3 are different font sizes and it is causing some screen jump as I switch themes

H1 is 48px and 37.5px (Flatly and Darkly respectively), H2 is 40px and 30px, H3 is 32px and 26.25px.

I'm guessing (as I just used compiled css files from the Bootstrap CDN) that is caused by the _variables.scss file where Flatly has the following lines of code but Darkly doesn't.

$h1-font-size:                3rem !default;
$h2-font-size:                2.5rem !default;
$h3-font-size:                2rem !default;

I don't mind which size wins out but it would be nice to be consistent between the two.

**Comment by thomaspark** [comment]
Hi @aderrose, thanks for opening this ticket — definitely an oversight. Fix is on the way.

**Comment by thomaspark** [comment]
f19cf9a6a122d0225bf3d89c81ff978c9057afff

**Comment by aderrose** [comment]
Thanks for the quick turnaround

**Comment by aderrose** [comment]
Just a quick follow up, how long does it take for BootstrapCDN to update?

Is it a manual task or just a matter of waiting a bit?

**Comment by thomaspark** [comment]
It'll get updated on BootstrapCDN the next time the version number gets bumped here.

**Comment by aderrose** [comment]
And the version bumps are inline with Bootstrap updates?  Just wondering whether I need to revert back to downloaded versions rather than the CDN for a little while.

**Comment by thomaspark** [comment]
Yup, versions are inline with Bootstrap, so you should download in the meantime.

**Comment by aderrose** [comment]
Thanks for the clarification, I'll switch over the sources.
