### ISSUE TITLE
.table-sm not working in Lux theme version 4.1.2

### ISSUE THREAD

**Issue by tsmith-dev** [thomaspark/bootswatch#853]
The .table-sm class isn't working with the Lux theme in version 4.1.2. I've tried a few other themes from the CDN files and they seem to be find (Cyborg and Flatly, for example).

using...

`<link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.2/lux/bootstrap.min.css" rel="stylesheet" integrity="sha384-58Vxhfld+b/l9kgnC3BTqFfoqWobrpZKMIaWTgND+yN43GDm0zBTE+j3BpPQAuTb" crossorigin="anonymous">`

**Comment by thomaspark** [comment]
@tsmith-dev, thanks for the heads up.
