### ISSUE TITLE
Add crossorigin and integrity

### ISSUE THREAD

**Issue by laurentmuller** [thomaspark/bootswatch#859]
This will be nice if the `crossorigin` and `integrity` attributes are embended within the JSON file like this:

```
{
...
"cssCdn": "https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0/cerulean/bootstrap.min.css",
"crossoriginCdn: "anonymous",
"integrityCdn": "sha256-xruBsld6Jatcc6F/apXkADl+PVaUqUopEohlYxlDgdo=",
...
}
```
This attributes can then be used within the head declarations.

**Comment by thomaspark** [comment]
Nice idea. It would be great to add these to `api.json` and add a grunt task that updates the values. Just noticing that this file's out of date as well. Anyone up for a pull request?
