### ISSUE TITLE
Cyborg, Superhero: Low constrast on .thead-light th

### ISSUE THREAD

**Issue by truongan** [thomaspark/bootswatch#863]
Superhero features
```
.table .thead-light th {
    color: #495057;
    background-color: #4E5D6C;
}
```
And cyborg features
```
.table .thead-light th {
    color: #fff;
    background-color: #e9ecef;
}
```

Both of which is quite low contrast IMHO. Other dark theme handle `.thead-light` pretty well so I guess cyborg and superhero should follow them.

**Comment by thomaspark** [comment]
@truongan, thanks for the bug reports. I'm pushing some improvements now.
