### ISSUE TITLE
.list-group-flush doesn't remove last element bottom border

### ISSUE THREAD

**Issue by prymitive** [thomaspark/bootswatch#866]
As on [bootstrap docs](https://getbootstrap.com/docs/4.1/components/list-group/#flush) I expect last element in `.list-group .list-group-flush` to have no bottom border:

<img width="867" alt="screen shot 2018-10-11 at 08 51 54" src="https://user-images.githubusercontent.com/114288/46788865-0e323e00-cd33-11e8-9865-0f75b3e509fe.png">

But I've noticed that this is not the case here (added `.list-group-flush` in dev tools on the example page):
<img width="591" alt="screen shot 2018-10-11 at 08 50 51" src="https://user-images.githubusercontent.com/114288/46788908-21dda480-cd33-11e8-8a25-e6fcacc374fa.png">

Looks like `.list-group-item.list-group-flush:last-child {border-bottom: 0}` is missing ?

**Comment by thomaspark** [comment]
Thanks for the bug report. It breaks on hover for the example pages because the code preview button gets appended and `list-group.item.list-group-flush` is no longer last child. But it should work ok for you in practice.

**Comment by prymitive** [comment]
I don’t think that button is a ‘ul’ child, so not sure why would it matter.
I was looking at it because I’ve noticed same on my project, I’ll double check and come back with a better example if I can reproduce it, thanks!

**Comment by thomaspark** [comment]
I believe the full selector is `.list-group-flush:last-child .list-group-item:last-child`.

Any counter examples are appreciated!

**Comment by prymitive** [comment]
You're absolutely right, I had bottom border because there was another element after `ul`.
Moving `ul` under a dedicated `div` removed it.
Thanks!
