### ISSUE TITLE
Theme Idea: Brutalist/Swiss

### ISSUE THREAD

**Issue by Immortalin** [thomaspark/bootswatch#869]
With a couple minor modifications, a Brutalist/Swiss theme can be created from the Lux theme.

Some examples:

https://bloomberg.com
https://engine.xyz
https://turing.ac.uk

**Comment by Immortalin** [comment]
The key is that the font should be Helvetica or one of its variants.

**Comment by Immortalin** [comment]
https://knightfoundation.org

@thomaspark what do you think of a Swiss theme?

**Comment by thomaspark** [comment]
Hey @Immortalin, a theme like this would be a nice foundation, though would require a lot of work from users on top to look as good as some of those examples.

Have you tried playing around with Journal? With some tweaks to the fonts and buttons, you could get close.
