### ISSUE TITLE
Radio button now showing in Chrome or Firefox after upgrade to v4.1.3

### ISSUE THREAD

**Issue by fabou78** [thomaspark/bootswatch#871]
I was running with the united theme on my website and decided to update from v4.0.0-beta.2 to v4.1.3 so I have updated all files according to v4.1.3 only to find out that the following code; 

```
<div class="form-group">
    <div class="custom-control custom-radio">
      <input type="radio" id="customRadio1" name="customRadio" class="custom-control-input" checked="">
      <label class="custom-control-label" for="customRadio1">Toggle this custom radio</label>
    </div>
    <div class="custom-control custom-radio">
      <input type="radio" id="customRadio2" name="customRadio" class="custom-control-input">
      <label class="custom-control-label" for="customRadio2">Or toggle this other custom radio</label>
    </div>
    <div class="custom-control custom-radio">
      <input type="radio" id="customRadio3" name="customRadio" class="custom-control-input" disabled="">
      <label class="custom-control-label" for="customRadio3">Disabled custom radio</label>
    </div>
  </div>
```
  

Would not display the radio button on chrome and Firefox however if you click on the place where the button would be it is actually working, so they are not displaying but are present on the page.

Right now I have reverted back the bootswatch CSS file to v4.0.0-beta.2 and kept the other upgraded file to as below;
jquery-3.2.1.min.js --> jquery-3.3.1.min.js
poper-1.13.0.min.js --> poper-1.14.3.min.js
bootstrap.min.js v4.0.0-beta.2 --> bootstrap.min.js  v4.1.3 

All is working fine for now but I still wish to upgrade the bootswatch CSS file (bootstrap.min.css) to v4.1.3

Does anyone knows why I am facing this is issue with the radio button as shown above?

**Comment by thomaspark** [comment]
Hi @fabou78, I wasn't able to replicate your issue. Does this display ok for you?

https://jsfiddle.net/azwn49jd/

**Comment by fabou78** [comment]
Yes it does work. I wonder what's going on on my side. Any tools I can use to try troubleshooting this?
