### ISSUE TITLE
Parse error with calc command

### ISSUE THREAD

**Issue by josh-byster** [thomaspark/bootswatch#878]
I believe there's a conflict with PostCSS and current bootswatch 4.1.3. 
When I run `npm run build`, which uses Webpack and I believe PostCSS, I get the following compile error:
```
Creating an optimized production build...
Failed to compile.

Parse error on line 1:
255px 25px 225px 25px/25px
------^
Expecting 'EOF', 'ADD', 'SUB', 'MUL', 'DIV', 'RPAREN', got 'LENGTH'
```

I have tried building the SASS separately but it always errors out with this message specifically when it does the minifying of the CSS. This happens with modified and unmodified CSS/SCSS files. We are using `sketchy`. It seems like this is an issue with using `calc`. [Create React App](https://github.com/facebook/create-react-app/issues/6004) has also confirmed that this is likely a problem with the bootswatch CSS rather than any of their modules. 
A minimum reproducible example is:

```
.popover-header {
   padding: 0.5rem 0.75rem;
   margin-bottom: 0;
   font-size: 1rem;
   color: inherit;
   background-color: #f7f7f7;
   border-bottom: 2px solid #ebebeb;
   border-top-left-radius: calc(555px 25px 15px 25px/25px 5px 35px 555px - 2px);
   border-top-right-radius: calc(555px 25px 15px 25px/25px 5px 35px 555px - 2px);
 }
```
will say:

```
Parse error on line 1:
555px 25px 15px 25px/25px
------^
Expecting 'EOF', 'ADD', 'SUB', 'MUL', 'DIV', 'RPAREN', got 'LENGTH'
```

**Comment by Segev95** [comment]
Got the same problem as well while trying to use Sketchy in production. I'm using vue-cli3.
I went over the file and putted under comment all the lines that caused the build to fail.

Here is the file that worked for me: [working sketchy.txt](https://github.com/thomaspark/bootswatch/files/2845250/working.sketchy.txt)

 Hope it will help you till this problem will be fixed.

**Comment by simondubois** [comment]
The issue is not solved.

**Comment by thomaspark** [comment]
Let me know if this fixes the build issue for you guys...

**Comment by simondubois** [comment]
Hi Thomas,

Thank you for this rapid and proper fix.
I can now compile this theme in with `npm run prod`.

Thank you for maintaining such great project.

**Comment by simondubois** [comment]
@thomaspark I have noticed something broken since : 28eefa3 or a7c0f9d.
The class `img-thumbnail` has lost the sketchy typical border radius.

Before the two commits on class `img-thumbnail`: `border-radius: 255px 25px 225px 25px/25px 225px 25px 255px;`
After the two commits on class `img-thumbnail`: `border-radius: 25px;`

Is it something you can fix?

**Comment by thomaspark** [comment]
@simondubois, no problem, I'll push a fix for that. Let me know if you spot any other regressions.

**Comment by simondubois** [comment]
@thomaspark It works thank you!

**Comment by josh-byster** [comment]
Thanks for the fix!
