### ISSUE TITLE
Undefined variable: "$theme-colors".

### ISSUE THREAD

**Issue by Irrgeist** [thomaspark/bootswatch#879]
I copied the `_variables.scss` and `_bootswatch.scss` to my project and included it like this:
```
@import "_bootswatch_variables.scss";
@import "~bootstrap/dist/css/bootstrap";
@import "_bootswatch.scss";
```
I get this error:
```
Undefined variable: "$theme-colors".
      in E:\git\Frontend\src\styles\_bootswatch.scss (line 160, column 27)
```

Using the npm version like this works:
```
@import "~bootswatch/dist/flatly/variables";
@import "~bootstrap/scss/bootstrap";
@import "~bootswatch/dist/flatly/bootswatch";
```
I really don't know why this happens oO

**Comment by dleffler** [comment]
What compiler are you using?

**Comment by henhen724** [comment]
I am having a similar error.
Error: Undefined variable.
  font-size: $font-size-sm;
             ^^^^^^^^^^^^^
  source\_bootswatch.scss 13:14  root stylesheet

I am using dart2js 2.1.0 .

I am using the command "sass source/_bootswatch.scss:default-bootstrap.css --load-path="source/_variables.scss".

**Comment by henhen724** [comment]
The issue was import statement order.

**Comment by elliot-sawyer** [comment]
I am having the same issue with 4.2.1

@henhen724 what did you change about the import statement order to get it to work?

**Comment by henhen724** [comment]
You're is different you should write:
```
import "bootswatch/dist/yeti/variables.scss";
import "bootstrap/scss/bootstrap.scss";
import "bootswatch/dist/yeti/bootswatch.scss";
```
Underscores just let sass know that the file is partial you don't include them in imports.

**Comment by henhen724** [comment]
I actually believe this is the same issue that the original post is having this error can be closed.
