### ISSUE TITLE
bootswatch for bootstrap 3.4.0

### ISSUE THREAD

**Issue by slolo2000** [thomaspark/bootswatch#880]
Hello,

Do you planned to release a new version of bootswatch for the last release of bootstrap 3 (v3.4.0)?

Thanks in advance and have a nice day.

**Comment by thomaspark** [comment]
Hi @slolo2000, I just pushed a release for 3.4.0.

https://github.com/thomaspark/bootswatch/releases/tag/v3.4.0
https://www.npmjs.com/package/bootswatch/v/3.4.0

**Comment by slolo2000** [comment]
Thank you very much for your great work!
