### ISSUE TITLE
custom-switch

### ISSUE THREAD

**Issue by coliff** [thomaspark/bootswatch#884]
Bootstrap 4.2.x introduces `custom-switch` which has an iOS look about it.
https://getbootstrap.com/docs/4.2/components/forms/#switches

It'd be nice to see an Android look to this for the Materia theme. In any case it might be good idea to add `custom-switch` to the demo pages.

**Comment by coliff** [comment]
For reference/inspiration for the Materia theme:
https://material-components.github.io/material-components-web-catalog/#/component/switch

**Comment by thomaspark** [comment]
Hey @coliff, thanks for the suggestion. Adding these custom switches:

<img width="270" alt="screen shot 2019-01-10 at 9 18 07 pm" src="https://user-images.githubusercontent.com/900407/51009283-9506da80-151d-11e9-9e1b-62189a885844.png">
