### ISSUE TITLE
Bootswatch theme doesn't use my own theme-color

### ISSUE THREAD

**Issue by drauch** [thomaspark/bootswatch#885]
I'm setting a theme-color for bootstrap like so:

    /* Set the primary color to our blue */
    $theme-colors: ( "primary": $ContosoBlue );

Unfortunately, the included spacelab theme doesn't use this color. It uses its own (very darkish) blue. How to properly override a theme color for a bootswatch theme? According to the Bootstrap docs it should suffice to do the code above, however, I have to manually perform:

    $blue: $ContosoBlue !default;

now. Is this a bug? I haven't observed this behavior in 4.1.3, this seems to be new in 4.2.1.

**Comment by thomaspark** [comment]
Hey @drauch, odd that it worked before but now doesn't. This should work for you:

```sass
$primary: $ContosoBlue;
```

**Comment by drauch** [comment]
Yep, this works. But I still think this is a problem in bootswatch. It should use Bootstrap's `$theme-colors` instead. Don't you think so?

**Comment by thomaspark** [comment]
Can you give this a try?

**Comment by drauch** [comment]
How? Is there some pre-release feed I can obtain the new version from?

**Comment by marinameth** [comment]
this color. It uses its own (very darkish) blue. How to properly override a theme color for a bootswatch theme,,

**Comment by thomaspark** [comment]
You can grab from this commit (https://github.com/thomaspark/bootswatch/tree/cdd1bf6d36ab84540ecbf6ed86883c2c2b57ef3d) or wait for 4.3.0 which will be released shortly.

**Comment by drauch** [comment]
I finally came around to test this - it works now! Thank you very much 👍
