### ISSUE TITLE
Lux: btn-sm and input-group-sm > btn are inconsistent

### ISSUE THREAD

**Issue by Crote** [thomaspark/bootswatch#891]
I'm currently using Lux in a situation where a `form-control-sm` is next to a `btn-sm`, and the sizing is _slightly_ off. Interestingly, although unusable in my situation, the sizing is identical when used as a `btn` and `form-control` wrapped in a `input-group-sm`.

I believe that the current `btn-sm` size is caused by a bug. Note that it is defined twice: the first definition ([here](https://github.com/thomaspark/bootswatch/blob/master/dist/lux/bootstrap.css#L3199) sets the font-size to `0.765625rem`, which is the same value used [here](https://github.com/thomaspark/bootswatch/blob/master/dist/lux/bootstrap.css#L3828) for `btn` wrapped in a `input-group-sm`.
However, this value is overwritten by the second definition [here](https://github.com/thomaspark/bootswatch/blob/master/dist/lux/bootstrap.css#L10421), which sets the the font-size to `10px`. This second definition should probably not exist.

It might be better to go the other way, setting the font-size for `input-group-sm > btn` to `10px` as well, but setting the line-height for both to `1.1484375rem`: the current font size for `btn-sm` does seem to be a better fit for an `input-group-sm`, and that line-height would fix the height mismatch.

**Comment by thomaspark** [comment]
Hey @Crote, thanks for the bug report. This should fix the problem. Let me know if it works for you.
