### ISSUE TITLE
Upgrade to Bootstrap 3.4.1 and 4.3.1

### ISSUE THREAD

**Issue by IAmHopp** [thomaspark/bootswatch#892]
It's [4.3](https://blog.getbootstrap.com/2019/02/11/bootstrap-4-3-0) time! Please upgrade at your earliest convenience.

Much appreciated!

**Update:** 4.3.1 is live as well.

**Comment by markcarver** [comment]
https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/

Can you change the title to `Upgrade to latest Bootstrap (3.4.1 and 4.3.1)`?

**Comment by markcarver** [comment]
Thanks 😄 

Hope this happens soon, need to compile need overrides for https://www.drupal.org/project/bootstrap

**Comment by IAmHopp** [comment]
For what it's worth, I did try to do it myself, but the Lux theme is erroring out.

One of the changes brought by the RFS implementation in 4.3.1 caused an rem * rem to become an em * rem, which isn't valid.

So the Lux theme might need a refactor.

**Comment by thomaspark** [comment]
Thanks for your patience guys. [3.4.1](5041607d808fee36be6e8b8713ec799a062f7d35) and [4.3.1](f42e9299c01cb800d99f6664e20363dc1859c6b9_ are up!

I did need to tweak Lux to fix the error so all should be good now @IAmHopp.

**Comment by markcarver** [comment]
Did something happen during the build process for 3.4.1? See ^

**Comment by markcarver** [comment]
According to https://github.com/jsdelivr/data.jsdelivr.com/issues/12#issuecomment-463670635, there appears to be a new `docs` folder included with `3.4.1`.

**Comment by thomaspark** [comment]
@markcarver, yikes, I don't know how that happened. I'll have it removed. I don't know if there's a way to push a new version to npm/jsdelivr until Bootstrap goes `3.4.2` unfortunately.

**Comment by markcarver** [comment]
Maybe do a `3.4.1.1`?

**Comment by thomaspark** [comment]
npm won't accept four digits, and also ignores the build number (`+`) if added to a semver.

You should be ok staying on 3.4.0 for Bootswatch for time being, even if you get on 3.4.1 for Bootstrap due to the XSS issue. Nothing in the CSS has changed.

**Comment by markcarver** [comment]
Unfortunately, that's not how https://drupal-bootstrap.org/api/bootstrap/src%21Plugin%21Provider%21JsDelivr.php/function/JsDelivr%3A%3AgetCdnThemes/8#source.84-87 works...

It's tied to the Bootstrap version selected in the UI

**Comment by markcarver** [comment]
Ok, I suppose I'll just have to introduce some sort of `mapVersion` method specifically targing the bootswatch package.

I noticed there's no `4.3.0` release either... so I guess it should use `4.3.1` as well.

**Comment by markcarver** [comment]
Ok, I think I've figured something out https://www.drupal.org/project/bootstrap/issues/3033135

Thanks for the responsiveness though 😄

**Comment by thomaspark** [comment]
Glad you were able to find a solution, and apologies for the 3.4.1 mishap!

**Comment by markcarver** [comment]
No worries, things happen 👍 Yesterday was just a very long day lol
