### ISSUE TITLE
npm package too big for jsDelivr

### ISSUE THREAD

**Issue by 12smc120** [thomaspark/bootswatch#893]
I'm trying to load this package from [jsDelivr CDN](https://www.jsdelivr.com/package/npm/bootswatch) but it fails because the package is over 50 MB. Are there any files that could be removed to reduce the package size?

**Comment by thomaspark** [comment]
Hey @12smc120, steps were taken to reduce the size but it won't get pushed to jsDelivr until there's a new version update. See https://github.com/thomaspark/bootswatch/issues/892#issuecomment-463744842.
