### ISSUE TITLE
Contrast issue in Slate Theme in <TH>

### ISSUE THREAD

**Issue by slookabill** [thomaspark/bootswatch#894]
Using a <th></th> The text is black on a dark grey background in the Slate Theme

**Comment by slookabill** [comment]
<table class="table table-striped table-hover table-sm">
          <thead class="d-print-none">
            <tr>
              <th>Shift</th>
              <th>Person</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>06:00</td>
              <td>Person name</td>
            </tr>
        </table>

**Comment by slookabill** [comment]
Looks like it's affecting all text in tables, and also multiple themes. Currently using the CDN for bootstrap 4.3.1, and on the element per inspect element on Google Chrome, it appears that _table.scss is forcing itself to go over the theme css file.

**Comment by slookabill** [comment]
After more checking it appears I included the bootstrap.css file  and didn't need to, as well as the a copy of the theme file... which has been working for years, and finally stopped working this upgrade guess something stopped working. I removed the link to bootstrap.css and kept the theme file and appears to be working.

**Comment by thomaspark** [comment]
Thanks for the update, glad you have it working now.
