### ISSUE TITLE
Dark/Light switch

### ISSUE THREAD

**Issue by alighasemzadeh** [thomaspark/bootswatch#899]
I think it would be good idea to have Dark/Light switch.

**Comment by thomaspark** [comment]
Hi @alighasemzadeh, do you mean bootswatch.com or a particular theme?

**Comment by alighasemzadeh** [comment]
Bootswatch

**Comment by Chistabo** [comment]
i vote for this.

**Comment by alighasemzadeh** [comment]
@thomaspark 
All themes.
