### ISSUE TITLE
Darkly input select background/text color

### ISSUE THREAD

**Issue by Chistabo** [thomaspark/bootswatch#901]
using darkly, input fields are rendered with dark background and light text.
but, if one uses input group or input select (multiple choices, i.e. browser's input history, like login user), the background is light (white), and text is dark (dark gray).
when input is selected, background stays light (white), and text is dark (dark color).

i would expect background to be dark (dark color), and text to be light (white color).

here is youtube short video.
https://www.youtube.com/watch?v=C5gALEzrv2w&feature=youtu.be

am i missing here something?

**Comment by thomaspark** [comment]
Hey @Chistabo, can you post a link to JSBin or JSFiddle with a demo of what you're seeing? The YouTube link isn't working for me, but a live demo would be helpful.
