### ISSUE TITLE
"is-invalid" class make IE11 crash in Materia theme

### ISSUE THREAD

**Issue by Skuair** [thomaspark/bootswatch#903]
On IE11, if I switch on/off "is-invalid" class, it crashes IE.

To reproduce : 
- go to the materia preview page : _https://bootswatch.com/materia/_ with IE11.
- scroll to the example invalid input
- with IE developer tool (F12), remove the "is-invalid" class : it'ok, the red cross disapears
- add manually the class with developer tools : IE crashes

Only reproductible with this theme : all others that have a square border on inputs are OK.
Note : applies to "is-valid" class as well.
Tested on IE11 on Windows 10 and Windows 7.
![isinvalid](https://user-images.githubusercontent.com/49756503/56365736-daf4ce00-61f1-11e9-83b7-194fb3ee1ad8.png)

**Comment by thomaspark** [comment]
Hi @Skuair, thanks for the detailed report. This is bizarre but I was able to replicate it on IE11/Win8. It also crashes when the class is toggled programmatically.

I'll see if I can narrow down exactly which style is causing the crash.

**Comment by Skuair** [comment]
Yes, I discovered it programmatically when I wanted to toggle it with a Angular ngClass.

**Comment by Skuair** [comment]
Hi @thomaspark,
Any news of this problem ?

**Comment by thomaspark** [comment]
Hey @Skuair, thanks for the ping, I've tracked down the issue.

IE11 will crash under these conditions. Element has:
* `background-image`
* `background-position` with calcs
* `background-size` with calcs
* `transition` on `background-position`

Then toggling `background-position` to crash. You can try it here: https://output.jsbin.com/juxudadozo/1

I'll push a fix that limits transition to `box-shadow`. Let me know if this fixes it for you.

**Comment by Skuair** [comment]
It works, thank you.
