### ISSUE TITLE
fonts.google.com is not accessable in China

### ISSUE THREAD

**Issue by jinfagang** [thomaspark/bootswatch#904]
Thanks for this wonderful project.

As you may notice, all sites related with google can not be accessed in China....
we want to use bootswatch but it just can not load, because it loads fonts from google...

Does there any plan to help poor chinese people out?

**Comment by thomaspark** [comment]
Hi @jinfagang, you can set the option to remove Google fonts in SASS (#573) and rebuild the themes. This also gives you the option to self-host the fonts.
