### ISSUE TITLE
Materia theme - form-control and btn placed in the input-group have different box-shadow

### ISSUE THREAD

**Issue by konstantinmaximov** [thomaspark/bootswatch#908]
Hi,
The following markup 
```
<div class="input-group">
	<div class="">
		<input class="form-control" type="text"><span></span>
	</div>
	<div class="input-group-append">
		<span class="btn btn-secondary dropdown-toggle"></span>
	</div>
</div>
```
looks as follows
![image](https://user-images.githubusercontent.com/24777861/58025269-c2434500-7b1c-11e9-9a2f-b8f2a2f1aa0b.png)

**Comment by thomaspark** [comment]
This is as expected since the inputs don't have any shadow or depth while the button does. If you have a material design reference that handles it better, please share here.
