### ISSUE TITLE
css

### ISSUE THREAD

**Issue by nightw0lv** [thomaspark/bootswatch#911]
journal: font-size: 18px; on .nav is too big
general letter-spacing: 1px; on body breaks almost all theme navs
superhero, spacelab: background text on pre tag is white same as background bg-secondary not work
sketchy, simplex, sandstone, minty, cosmo: bg-secondary not work
materia: menu hover (background) is white and text is also white
flatly, darkly: background text on pre tag is white same as background

**Comment by thomaspark** [comment]
Hey @nightw0lv, thanks for the bug reports. Can you post demos of these bugs on JSFiddle/JSBin/Codepen?  Not able to replicate the issues.
