### ISSUE TITLE
Newb: How do I activate your themes?

### ISSUE THREAD

**Issue by s-r-martin** [thomaspark/bootswatch#912]
Thomas,

Sorry for such a basic question...

I have done < npm install bootswatch > in my Drupal 8 project. (A subtheme of Radix) and I can see the Bootswatch directory inside my nodemodules directory.

Now what? How do I actually use the 'Sketchy' theme for instance?

I'm using Radix 4.3 (Bootstrap 4).

Thanks :-)

Simon

**Comment by thomaspark** [comment]
Hi Simon,

I'm not very familiar with how themes work in Drupal, but if the styles are built from sass, you can replace or override the Bootstrap files with the two (`_variables.scss` & `_bootswatch.scss`) included with Sketchy or whatever theme you go with.

**Comment by s-r-martin** [comment]
Thomas,

I really appreciate you getting back to me... I think I have fathomed it out :-) I switched to another theme and once I had my subtheme properly set up , replacing the style.css file seemed to do the trick.

Hope I haven't spoken too soon...

Simon

**Comment by thomaspark** [comment]
Glad you got things working!
