### ISSUE TITLE
choose the input css to show the code source ,it will redircet

### ISSUE THREAD

**Issue by kzq666666** [thomaspark/bootswatch#913]
when i click the button to show the source code of input css ,but it only show only about one or two seconds,then it will redircet to the top of the page . and the code will disappear
![image](https://user-images.githubusercontent.com/36102279/59437578-6bcbdc80-8e24-11e9-80ec-9dea5dc46e76.png)
then it will go to the top
![image](https://user-images.githubusercontent.com/36102279/59437614-7b4b2580-8e24-11e9-9335-99ee8f999020.png)

**Comment by thomaspark** [comment]
Hi @kzq666666, what browser/version are you using?

**Comment by kzq666666** [comment]
> Hi @kzq666666, what browser/version are you using?

![image](https://user-images.githubusercontent.com/36102279/59437893-04faf300-8e25-11e9-862e-2e346826be99.png)

**Comment by kzq666666** [comment]
I try it in other browser ,the bug is still exists

**Comment by thomaspark** [comment]
I'm not able to replicate it, but I'm pushing an attempted fix now.
