### ISSUE TITLE
`-webkit-appearance` is not defined for materia theme

### ISSUE THREAD

**Issue by Samemura** [thomaspark/bootswatch#920]
I using bootswatch with sass integration and `select.form-control`  is not showing correctly like this.

![9F0E4956-95F7-4FDA-9875-641A809D8797](https://user-images.githubusercontent.com/7892834/61791849-18eb3900-ae56-11e9-9c8f-08995aba91f7.png)

It looks `-webkit-appearance: none` is not define in 
https://github.com/thomaspark/bootswatch/blob/0630a48f32fa8ae040861fd91c99b332784291b8/dist/materia/_bootswatch.scss#L295

Here is my scss:
```
@import "bootswatch/dist/flatly/variables";
@import "bootstrap/scss/bootstrap";
@import "bootswatch/dist/flatly/bootswatch";

```

**Comment by thomaspark** [comment]
Hi @Samemura, as part of your build process, you should use something like [autoprefixer](https://github.com/postcss/autoprefixer) to add vendor prefixes.

You can see the script we use here: https://github.com/thomaspark/bootswatch/blob/master/package.json#L16

**Comment by Samemura** [comment]
@thomaspark Sorry for late reply, but thank you for the comment. I will try it.
