### ISSUE TITLE
Darkly on CDN seems to have bg-dark and bg-light swapped

### ISSUE THREAD

**Issue by parnic** [thomaspark/bootswatch#925]
The version of Darkly for Bootstrap 4.3.1 posted on bootswatch.com has swapped values for bg-dark and bg-light compared to the CDN version.

From CDN:
```
.bg-light {
  background-color: #303030 !important;
}

.bg-dark {
  background-color: #00bc8c !important;
}
```
Ref:
* https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.3.1/darkly/bootstrap.css
* https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/darkly/bootstrap.css

From bootswatch.com:
```
.bg-light.navbar {
  background-color: #00bc8c !important;
}

.bg-dark {
  background-color: #303030 !important;
}
```
Ref:
* https://bootswatch.com/4/darkly/bootstrap.css

The bootswatch.com version seems like what I would expect to be correct values.

**Comment by thomaspark** [comment]
Hi @parnic, the version on bootswatch.com is a little ahead of the cdns. For the same version, you should check releases: https://github.com/thomaspark/bootswatch/releases The cdns will get updated on the next version number bump.

**Comment by parnic** [comment]
Thanks @thomaspark. I will plan on hotlinking to the bootswatch version until the CDN gets the next rev.

**Comment by TexasSwede** [comment]
A similar issue can be found in Flatly and Litera. There .bg-dark is using the color for success.
In Sandstone .bg-dark is using the color for secondary.
