### ISSUE TITLE
Materia email input placeholder text not visible on dark background

### ISSUE THREAD

**Issue by parnic** [thomaspark/bootswatch#926]
I have a login form on my dark navbar and the placeholder text is black (very hard to read) with the Materia theme when the input type is set to "email".
```
<form action="/login" method="post" class="form-inline my-auto">
    <input type="email" name="email" id="email" placeholder="Email" class="form-control mr-sm-2">
    <input type="submit" class="btn btn-success" value="Sign in">
</form>
```
=> 
![image](https://user-images.githubusercontent.com/888126/63481238-73c67f00-c45a-11e9-995e-e11b6a8ef84a.png)

Input `type="text"` works fine:
![image](https://user-images.githubusercontent.com/888126/63481257-82ad3180-c45a-11e9-8587-a670522f517f.png)

Same problem is present with other non-text html5 input types such as "tel" and "number". Since the Materia theme has these input backgrounds transparent, it's hard to tell that there's a form there at all without the placeholder text visible.

**Comment by thomaspark** [comment]
Hey @parnic, pushing a fix for this now.
