### ISSUE TITLE
Switch in Solar theme difficult to see when in "off" position

### ISSUE THREAD

**Issue by aaronhudon** [thomaspark/bootswatch#932]
v4.3.1 - Solar theme

When in the "off" position, the switch does not have ideal colors.

![image](https://user-images.githubusercontent.com/4406811/68096428-82231500-fe65-11e9-929f-e80ae8d00c01.png)

**Comment by thomaspark** [comment]
Thanks for pointing that out. I'll increase contrast on it:

<img width="227" alt="Screen Shot 2019-11-04 at 9 39 51 PM" src="https://user-images.githubusercontent.com/900407/68174324-ae18c600-ff4b-11e9-919b-172efe0d5c42.png">
