### ISSUE TITLE
input-group-prepend and -append height mismatch on Darkly theme

### ISSUE THREAD

**Issue by lwestfall** [thomaspark/bootswatch#933]
Greetings,

There seems to be a height mismatch for the input group prepend and append against the input itself in the Darkly theme. I'm unsure if any other themes are affected (Flatly seems to be okay, at least).

It's quite minor, but enough for me to notice. I added .border and .border-danger to the input-group div in the screenshot below to help illustrate the difference in height.

![image](https://user-images.githubusercontent.com/15251311/68313462-a1e35480-0082-11ea-966f-dabcf6eb19e2.png)

Thanks

**Comment by thomaspark** [comment]
Thanks for the bug report. I'm adding a border-color to inputs (it was transparent before) to put Darkly more inline with Flatly.

**Comment by thomaspark** [comment]
Fixed in 8cb385c1a83a5850c3f3fe79d3042be687412b41.
