### ISSUE TITLE
Darkly: bg-light for navbar.

### ISSUE THREAD

**Issue by walidbagh** [thomaspark/bootswatch#940]
Why the color for bg-light on navbars is set to 'green' $success ?
This prevents me from upgrading to the latest bootstrap.
This issue is related to https://github.com/thomaspark/bootswatch/blob/89d6ae6c161cb74aa4b11f8bec74f730e764ecbd/dist/darkly/_bootswatch.scss#L20

**Comment by walidbagh** [comment]
Any news on this issue ?

**Comment by jdoubleu** [comment]
What color do you expect/want it to have?

I'd guess the `!important` modifier is required to override Bootstrap's default style.

However, you should be able to override this rule easily in a custom stylesheet:
```CSS
.bg-light.navbar {
  background-color: #fff !important;
}
```

**Comment by walidbagh** [comment]
Hey @jdoubleu , thank you for your reply.

I expect it to have the value `background-color: #303030 !important;`. as this was it's value in the `^4.3.1` version.

This commit is what messed things up (was intended to fix https://github.com/thomaspark/bootswatch/issues/915) : https://github.com/thomaspark/bootswatch/commit/75794debc6c40ef7c511bc4e04fd6cddf1a78c27

 It changed the light navbar `background-color` and also the style of the nav-links color and on hover color (`$navbar-light-color`, `$navbar-light-hover-color`).

**Comment by thomaspark** [comment]
I'm changing `bg-light` to pull from `$light`, and have lightened it to improve contrast. This is more consistent with Bootstrap and the rest of the themes.

**Comment by septatrix** [comment]
Would you mind to release a new version / publish an update to npm? @thomaspark

**Comment by Rabadash8820** [comment]
I second that request, really hoping to see an update with this fix deployed soon!
