### ISSUE TITLE
Dropdowns not working?

### ISSUE THREAD

**Issue by Sarseth** [thomaspark/bootswatch#942]
https://jsfiddle.net/gcfet8n7/
I'm not sure if I'm missing something. But I've included css file and copy-pasted first dropdown buttons.
And it won't work. Do I miss some scripts? But then main page is only saying about one css file.

Chrome, opera tested

**Comment by thomaspark** [comment]
You'll also need to include some js files for dropdowns:
https://getbootstrap.com/docs/4.4/components/dropdowns/

**Comment by Sarseth** [comment]
Ah ok, bootstrap bundle and jquery. Thanks. My problem was I've started learning bootstrap mostly from bootswatch and there is no info about this, yet only usage.
Anyway, thanks!
