### ISSUE TITLE
Sketchy theme issue with Check Boxes and Radio Buttons Inline

### ISSUE THREAD

**Issue by GaryG54** [thomaspark/bootswatch#946]
When I setup simple check boxes or radio buttons with the sketchy theme and use inline setting, the check/radio buttons are skewed from the item "labels" on all devices.  This does not happen with any of the other themes.  I just updated to 4.4.1 of all the themes, and the problem persists only in theme sketchy.

**Comment by thomaspark** [comment]
Can you post the markup you're using, either here or on JSBin/JSFiddle?

**Comment by GaryG54** [comment]
Thomas,

I'm generating the project using AppStudio 8.0.4, of which George just
updated to the latest Bootswatch.  Here is an example of a simple app with
sketchy for check box and radio button.

https://www.theweedwerx.com/Project21b/index.html

This app works with all other themes.

Gary

**Comment by thomaspark** [comment]
Great, pushing a fix for this now.

**Comment by GaryG54** [comment]
Thomas,

Looks good.  Thanks. Keep up the good work.  :)

Gary

**Comment by GaryG54** [comment]
Thomas,

You didn't change the version number on the new sketchy.  George noticed
it.  Are you going to change the version #, or is this not worth the
trouble?

Thanks

Gary

**Comment by thomaspark** [comment]
The version number will be bumped with Bootstrap's next release.

**Comment by GaryG54** [comment]
I just noticed it is in sync with Bootstrap.  May I suggest you add
something to the versioning header that shows it's updated.  Just a
suggestion.  May help you track down issues easier in the future.
