### ISSUE TITLE
btn-outline-primary

### ISSUE THREAD

**Issue by Mevira** [thomaspark/bootswatch#948]
Hi!
While using the Slate theme I noticed it doesn't have any parameters for bootstraps "btn-outline-primary" class. I have a few dialog windows that use these buttons and you can hardly read the button text as the theme is right now. 

![image](https://user-images.githubusercontent.com/23071314/75232003-220f0080-57bf-11ea-8138-3a7c9c13a38c.png)

Version: Slate 4.3.1

**Comment by thomaspark** [comment]
Thanks for the report @Mevira, just pushed a fix.
