### ISSUE TITLE
I change navbars's backcolor and it works properly on my computer but the color doesn't change after I upload the files to my Server

### ISSUE THREAD

**Issue by shadowfish07** [thomaspark/bootswatch#949]
```
.bg-primary {
  background-color: #413c69 !important;
}
```
I change this color.I'm so confused why it works properly only on my computer.

**Comment by thomaspark** [comment]
Please post a link to your hosted version so we can take a look.

**Comment by shadowfish07** [comment]
http://videoshare.shadowfish0.top/index2.html

**Comment by thomaspark** [comment]
It's working for me:
<img width="1409" alt="Screen Shot 2020-03-10 at 9 56 02 PM" src="https://user-images.githubusercontent.com/900407/76374571-01e05500-631a-11ea-8f37-23fd3624911a.png">


You may need to reload to refresh your cache.

**Comment by shadowfish07** [comment]
okay,thank you
