### ISSUE TITLE
[Flatly theme] white close button on toasts' headers

### ISSUE THREAD

**Issue by Odyseus** [thomaspark/bootswatch#950]
Hello, everybody.

While creating my own variation of the Flatly theme, I found that the close buttons are white on toasts headers white backgrounds.

![Flatly](https://user-images.githubusercontent.com/3822556/76526922-0e18ff00-644d-11ea-85fd-4c353b6f8a7f.png)

A simple fix would be:

```patch
--- a/dist/flatly/_bootswatch.scss
+++ b/dist/flatly/_bootswatch.scss
@@ -237,6 +237,7 @@ $web-font-path: "https://fonts.googleapis.com/css?family=Lato:400,700,400italic&
 // Progress bars ===============================================================
 
 // Containers ==================================================================
+.toast .close,
 .modal .close{
   color: $black;
 
```

Thank you very much @thomaspark and contributors for your work. :+1:

**Comment by thomaspark** [comment]
@Odyseus, thanks for the bug report. Fix for Flatly and Lumen incoming.
