### ISSUE TITLE
small mode

### ISSUE THREAD

**Issue by gtbu** [thomaspark/bootswatch#951]
At https://bootswatch.com/litera/ the Hamburger mode already happens at 1000 px - the width of the  titel 'Bootswatch' counts some how - just click at the nav in firefox - then inspect element - and You see the width of the navbar ... this is an unwantable behaviour of bootstrap 4. 
Do You know  a solution ? ( The media min-width and breakpoint should be included into a variable with  class="navbar-brand")

**Comment by thomaspark** [comment]
Hey @gtbu, check the Bootstrap docs for how to set when the navbar collapses:

https://getbootstrap.com/docs/4.3/components/navbar/#responsive-behaviors
