### ISSUE TITLE
Again - middle mode Bootstrap 4

### ISSUE THREAD

**Issue by gtbu** [thomaspark/bootswatch#952]
At https://bootswatch.com/litera/ the Hamburger mode already happens **at 1000 px** - the width of the titel 'Bootswatch' counts some how - just click at the top-nav of the site in firefox - then inspect element - and You see the width of the navbar(document body width) .

In Your above site is <div class="navbar navbar-expand-lg  . 
If You change it to <div class="navbar navbar-expand-sm,   then the navbar collapses later....as it should do ! This is not a joke !

**Comment by gtbu** [comment]
The navigation of https://getbootstrap.com/ is much better than Yours - and also than Your too mall letters in table-mode.  - so i dont need Your solution....

**Comment by thomaspark** [comment]
👍
