### ISSUE TITLE
[sketchy] radioboxes & checkboxes displayed incorrectly on iOS Safari

### ISSUE THREAD

**Issue by avo7** [thomaspark/bootswatch#955]
Hi!

When the Sketchy theme is opened in Safari on iOS (possibly also desktop, I don't have a way to test it) the radioboxes and checkboxes are off. Additionally, when they're unchecked, there's a extra "shadow" box where they should be. See screenshot:

![image](https://user-images.githubusercontent.com/8046095/77854129-a69ed580-71e8-11ea-84ca-c3b43a872757.png)

Seems to be fine in other browsers.

**Comment by thomaspark** [comment]
Thanks @avo7, this seems to only affect iOS, not Mac. Fix coming.

**Comment by avo7** [comment]
thanks for the fix!
