### ISSUE TITLE
Bootstrap v5

### ISSUE THREAD

**Issue by InstanceOfMichael** [thomaspark/bootswatch#958]

**Comment by dleffler** [comment]
Bootstrap 5.0.0alpha1 is now out

**Comment by XhmikosR** [comment]
@thomaspark are there any plans to work on this before Bootstrap hits beta or stable? I'm not sure when we'll get to that, but we do plan to release a new alpha soon.

**Comment by Xmetalfanx** [comment]
i know it's alpha still and i am not one of those "is it ready yet?! is it ready yet!?" users ... just curious if IN GENERAL bootswatch will have a 5.x release after boostrap 5 FINAL (non alpha, non-beta) is out

**Comment by thomaspark** [comment]
Bootswatch will definitely support v5! Will start work when Bootstrap hits beta.

**Comment by Xmetalfanx** [comment]
that makes complete sense ... no sense in doing it with say alpha1 and then they change a number of things, before the beta (unlikely IMHO but it could happen) ... the beta is what is likely 100% going to be close to the final release

**Comment by septatrix** [comment]
> Bootswatch will definitely support v5! Will start work when Bootstrap hits beta.

Beta was just released yesterday :D

**Comment by thomaspark** [comment]
Just updated the themes to 5.0.0 very very beta 1.

Check out the v5 branch for more:
https://github.com/thomaspark/bootswatch/tree/v5
