### ISSUE TITLE
slate background colors

### ISSUE THREAD

**Issue by vision10** [thomaspark/bootswatch#959]
I don't know if this is necessary an issue but
I think I spotted an inconsistensy with the background colors in the slate theme

the .active class in a dropdown does not have a background color like :hover
also the custom form radio and checkbox colors are too similar to the theme background color

And I want to ask why are the input and buttons bigger now than the bootstrap 3 equivalent?

**Comment by thomaspark** [comment]
Hey @vision10, thanks for reporting these issues. A fix for dropdown active links is coming.

Bootstrap 4 increased the size of inputs and buttons, and Slate reflects that.
