### ISSUE TITLE
Darkly: Navbar active link is white instead of green in v4.4.1

### ISSUE THREAD

**Issue by Techwolfy** [thomaspark/bootswatch#962]
It looks like this was changed in 4c38972004c61db6de2fdbd5e956dca0346fa510, which removed the below code from Darkly's `_bootswatch.scss`.

```
.bg-primary {
  .navbar-nav .active > .nav-link {
    color: $success !important;
  }
}

.bg-light {
  &.navbar-light .navbar-nav {
    .nav-link:focus,
    .nav-link:hover,
    .active > .nav-link {
      color: $primary !important;
    }
  }
}
```

There's some related discussion in #940, but I'm not sure if this change was intended.

**Comment by thomaspark** [comment]
Hey @Techwolfy, yes this was a deliberate design decision to make it more consistent with Bootstrap.
