### ISSUE TITLE
Best Way to Change Themes on the Fly

### ISSUE THREAD

**Issue by GaryG54** [thomaspark/bootswatch#966]
Thomas,

I've not been able to find any reference to changing themes on the fly.  My current hack to change themes involves modifying this LINK tag:

<link href="toolbox/bs4/dist/css/bootstrap.min.css" rel="stylesheet">

I just change the bootstrap.min.css to the bootswatch theme.  It's worked so far.

Now that I've incorporated DataTables by DataTables into the app, when changing to a dark theme (Cyborg, etc.) from a light theme (Sandstone, etc.) on the fly, the DataTables data area background does not change and the foreground color does change to the background color, making the data invisible.  Changing back to a light theme, the data becomes visible.

Am I changing the themes correctly?  Or is this a problem with DataTables?

Thanks

Gary

**Comment by GaryG54** [comment]
The Link tag missing from the original post:

`<link href="toolbox/bs4/dist/css/bootstrap.min.css" rel="stylesheet">`

**Comment by GaryG54** [comment]
Since I'm still looking around, I just noticed that Solar, a dark theme, does work using my hack.  Slate doesn't work.  Superhero works, but it's almost invisible.

Again, the big question is: How to switch bootswatch themes?

The secondary question is:  Is DataTables  BS4 compliant or not as far as Bootswatch>

And are some themes just not compatible with DataTables?

**Comment by GaryG54** [comment]
Hey Thomas

Was really hoping you could provide me with some information :)

Thanks in advance

Gary

**Comment by thomaspark** [comment]
Hey Gary, this is probably a small incompatibility between DataTables and the Bootswatch themes. However, it should be possible to add some of your own base CSS to deal with it.

Can you share a link to your page or a live demo? I can take a look and suggest some CSS.

**Comment by GaryG54** [comment]
Thomas

Thanks for the reply.  

I've noticed some others having a similar issue on the Datatables forum as noted here, with a "fix".  

https://datatables.net/forums/discussion/51073

I have an alpha of the app at   mycannabisclinicaltrial.com    The data table, if you want to see it in action, would require you to register.  This is totally a test system and you can make up any data you want.  The data will be blown away before release.

If you do login, go to my journal and that will show observations, but you have to create one to get a list of them.  Geezee, it's quite a pain to get there.

The setting menu is where the theme setting is.  In device settings.  

But that's a lot of work.  So here's the tags to look for:   
The themes are set via a click on a drop down   see ThemesDropDown.onclick  function.   
function SetDarkModeTheme(IsDark) is where the fun is.  

I know I have a hardcoded reference to the link tag - I was going to fix that, and forgot.  Good time to do it, as I'm messing with some extensions which will probably move the location of the link tag.

This is built in AppStudio.

Gary

**Comment by thomaspark** [comment]
Thanks for the info. I think something like this might work with both light and dark themes:

```css
div.dts div.dataTables_scrollBody {
  background: none;
}

.table-striped tbody tr:nth-of-type(odd) {
    background-color: rgba(0, 0, 0, 0.05);
}
```

Hope that gets you on the right track.

**Comment by GaryG54** [comment]
I think that would work nicely - I'll try it.  I not using striped, but that could be a nice solution too, so striped may make sense now.  hmm

Concerning the title of this post, is the way I am changing themes on the fly in the SetDarkModTheme fucntion (modifying the link tag) the recommended way of changing themes?

Gary

**Comment by thomaspark** [comment]
Great. Yup, that's the way to do it.

**Comment by GaryG54** [comment]
The CSS seems to work nicely.  

Thanks again.

**Comment by thomaspark** [comment]
You're welcome. Glad it worked out!
