### ISSUE TITLE
[Cerulean]render of a title tag class or title class on an active background  class - same color

### ISSUE THREAD

**Issue by jipexu** [thomaspark/bootswatch#969]
Hi
so the result is you can not see the title ...
i dont remember if we already discuss of this limitation ? and how to fix (or not ) ?

Thanks

sequence example :
`<a class="list-group-item list-group-item-action active" href="forum.php?catid=1"><h5>Demo</h5></a>`

**Comment by thomaspark** [comment]
Hey @jipexu, I'd say this is just a limitation of this particular theme.

There are a few workarounds. You could override `color` of `.list-group-item h5`. Or you could avoid using the `h5` and set your own `font-size` and `font-weight` on `list-group-item`.

**Comment by jipexu** [comment]
@thomaspark 

thanks
yes they are few case ...in our cms context
so to adjust we have for each theme (skin) an little extra.css (usually empty...)

where for this theme i just patch with this the color ...
```
/* extra css for cerulean */
div.list-group-item.list-group-item-action.active h5 {
color:white;
}
a.list-group-item.list-group-item-action.active h5 {
color:white;
}
```

so we can close this 

thanks
