### ISSUE TITLE
Drop down item: white text on light gray background in Yeti theme

### ISSUE THREAD

**Issue by pavelovcharov** [thomaspark/bootswatch#970]
Hello, 

I've faced a following issue with the Yeti theme. When a dropdown menu is shown from the 'btn-secondary' button, drop down items have a white color on a a light gray background, therefore the text is not very visible. And the nested dropdown items in turn have a white color on a white background. They are not visible at all.

I believe the issue is caused by this css selector:
```
.btn-group .dropdown-toggle.btn-secondary ~ .dropdown-menu .dropdown-item {
    color: #fff;
}
```

I've prepeared a small example to demonstrate this issue in action: https://jsfiddle.net/s000581/5nw0kav4/9/

![chrome_JpEwdflssb](https://user-images.githubusercontent.com/1357165/86922302-16502500-c135-11ea-8a1f-91799ca42ec9.png)

**Comment by thomaspark** [comment]
Hey @pavelovcharov, thanks for the bug report. Pushing a fix for this now.
