### ISSUE TITLE
Adding dropdowns to the navigation examples

### ISSUE THREAD

**Issue by GamerBene19** [thomaspark/bootswatch#971]
I think that compared to the [Bootstrap Navbar examples](https://getbootstrap.com/docs/4.5/components/navbar/) and the other navigation examples (tabs and pills) of the Bootswatch themes, it would only make sense to add a dropdown menu to the example navbars in the top aswell (see picture).
![grafik](https://user-images.githubusercontent.com/20821976/87645883-65f2aa00-c74e-11ea-9ab6-bed8743bee28.png)

If needed/wanted I could also open a PR for this change (as I already 'solved' this 'issue')

Edit: Changed wording.

**Comment by thomaspark** [comment]
Hey @GamerBene19, this would be a helpful addition. A PR would be welcome!

**Comment by GamerBene19** [comment]
@thomaspark PR is created and ready to be merged. The dropdowns look like in the picture (they are the same layout as the ones of the pills/tabs examples).

**Comment by thomaspark** [comment]
Looks good, merging now. Thanks!

**Comment by GamerBene19** [comment]
No problem, you're welcome. Glad if i can contribute to this project (even if its very very very simple and little).
