### ISSUE TITLE
Update to Google Fonts css2

### ISSUE THREAD

**Issue by ozgurg** [thomaspark/bootswatch#974]
Google updated Google Font with new base URL.
https://developers.google.com/fonts/docs/css2

I think Bootswatch needs to be updated.

**Comment by thomaspark** [comment]
Agree we should move to the new API. Thanks for the heads up @ozgurg.

**Comment by XhmikosR** [comment]
@thomaspark are you sure this works like before? I don't see the fonts loaded at least for the cosmo theme,  the issue might be present in more themes.
