### ISSUE TITLE
Implement / support existing capabilities for an admin / backend theme (i.e. AdminLTE)

### ISSUE THREAD

**Issue by distributev** [thomaspark/bootswatch#988]
It will be great if bootswatch would offer the existing capabilities for an admin theme (or will offer its own admin theme). This will make the framework twice as useful being able to use your theme switcher in backend apps also (business apps).

One approach could be to build your own admin theme, another approach could be to integrate / support a well known open source admin theme such as AdminLTE.

I already opened a similar feature request to integrate / support bootswatch on the AdminLTE repository - curious to see what people think about this.

https://github.com/ColorlibHQ/AdminLTE/issues/2976

**Comment by thomaspark** [comment]
If the admin theme supports Bootstrap sass, you should be able to drop in Bootswatch to get decent results. It'd require additional tweaking to look its best, especially for custom components, but that's beyond our scope. Could be a good opportunity for AdminLTE to support Bootswatch or someone to start a new project that does it.

**Comment by aaronhudon** [comment]
> It will be great if bootswatch would offer the existing capabilities for an admin theme (or will offer its own admin theme). This will make the framework twice as useful being able to use your theme switcher in backend apps also (business apps).
> 
> One approach could be to build your own admin theme, another approach could be to integrate / support a well known open source admin theme such as AdminLTE.
> 
> I already opened a similar feature request to integrate / support bootswatch on the AdminLTE repository - curious to see what people think about this.
> 
> [ColorlibHQ/AdminLTE#2976](https://github.com/ColorlibHQ/AdminLTE/issues/2976)

@distributev unless AdminLTE switches to pure Bootstrap CSS, this won't be feasible.  They have their own layer of custom css.
