### ISSUE TITLE
Change some default settings in the simplex theme

### ISSUE THREAD

**Issue by ikatenov** [thomaspark/bootswatch#993]
I am using the [YAF](https://yetanotherforum.net/) forum engine to run forum for my customers. One of the built-in themes is the _simplex_ theme. When I install a new version of YAF, I always modify the _variables.scss and _bootswatch.scss files in the YAF source code to get the desired bootstrap-forum.min.css for my forum. I do this because I find some default settings in the simplex theme not relevant to the whole color/size scheme. You can find the details [here](https://yetanotherforum.net/forum/Posts/t21804-Simplex-theme-improvements).
To explain briefly, I do the following:
> _variables.scss:
> $warning: $purple !default --> change $purple to $orange
> $font-size-base: 0.8125rem !default; --> change 0.8125rem to 1rem
> _bootswatch.scss:
> .text-secondary {color: $gray-700 !important;} --> change $gray-700 to $gray-600

The developer of YAF told me that I could ask you to make these improvements in your source files so that we will never think about these changes on our side again with every release of YAF.
May I ask you to do this? TIA

**Comment by thomaspark** [comment]
Hey @ikatenov, can't promise I'll make all dthose exact changes, but I'll take a look and see what I can do. Some of those make sense for consistency sake (changing warning back to orange) but others are the styles that make Simplex unique from the other themes.

**Comment by ikatenov** [comment]
@thomaspark, is it possible to set the $font-size-base parameter to 1rem by default too? I've recently upgraded to the latest version of YAF (2.31.9) and found that all texts look very small again. This happened because the $font-size-base was set to 0.8125rem again after your improved theme was integrated into the YAF source. All texts look really small, it's hard to read them. 1rem is a much better choice, believe me. Can you fix that too, PLEASE?
